### ISSUE TITLE
[studio] Error in logs when starting the delivery environment

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1080]
1. Start the delivery environment
`./gradlew start -Penv=delivery`

2. Look at the catalina logs for the delivery environment, notice the error messages:
```
[WARN] 2017-07-10 13:46:25,306 [localhost-startStop-1] [support.XmlWebApplicationContext] | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'studioConfiguration' defined in class path resource [crafter/studio/studio-services-context.xml]: Invocation of init method failed; nested exception is while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 41, column 17:
    studio.db.port: @MARIADB_PORT@
                    ^

[ERROR] 2017-07-10 13:46:25,309 [localhost-startStop-1] [context.ContextLoader] | Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'studioConfiguration' defined in class path resource [crafter/studio/studio-services-context.xml]: Invocation of init method failed; nested exception is while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 41, column 17:
    studio.db.port: @MARIADB_PORT@
                    ^

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 41, column 17:
    studio.db.port: @MARIADB_PORT@
                    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:444)
	at org.craftercms.studio.impl.v1.util.StudioConfigurationImpl.loadConfig(StudioConfigurationImpl.java:65)
	at org.craftercms.studio.impl.v1.util.StudioConfigurationImpl.init(StudioConfigurationImpl.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 31 more
10-Jul-2017 13:46:25.313 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
10-Jul-2017 13:46:25.313 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/studio] startup failed due to previous errors
ERROR: error shutting down embedded database:
10-Jul-2017 13:46:25.341 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /Users/vita/temp/test2/craftercms/crafter-delivery-env/bin/apache-tomcat/webapps/studio.war has finished in 12,439 ms
10-Jul-2017 13:46:25.345 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-9080]
10-Jul-2017 13:46:25.350 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-9009]
10-Jul-2017 13:46:25.351 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 60916 ms
```

**Comment by jdrossl** [comment]
@alhambrav do you have the studio.war in delivery? please check if it is in this path: `crafter-delivery-env/bin/apache-tomcat/webapps/studio.war`

I just build the env and I'm not getting the error because studio is not supposed to be deployed for delivery.

**Comment by alhambrav** [comment]
@jdrossl 
I see the studio.war in the path you mentioned:
```
➜  craftercms git:(master) ls crafter-delivery-env/bin/apache-tomcat/webapps
ROOT                              crafter-profile-admin-console     crafter-search                    crafter-social-admin              studio
ROOT.war                          crafter-profile-admin-console.war crafter-search.war                crafter-social-admin.war          studio.war
crafter-profile                   crafter-profile.war               crafter-social                    crafter-social.war
```

I see the error in the delivery catalina logs whenever I start:
```
./gradlew start
```
or
```
./gradlew start -Penv=delivery
```

Then, tail the delivery catalina logs:
```
➜  craftercms git:(master) tail -f crafter-delivery-env/logs/tomcat/catalina.out
```

**Comment by alhambrav** [comment]
@jdrossl I did a fresh install, I deleted my whole craftercms folder, and did a git clone, then ran:
```
./gradlew init build deploy
```

The studio.war file is still in the delivery folder after running the command above (so I still see the error in the catalina logs when starting the delivery):

```
➜  craftercms git:(master) find . -name "studio.war"
./crafter-auth-env/bin/apache-tomcat/webapps/studio.war
./crafter-delivery-env/bin/apache-tomcat/webapps/studio.war
```

**Comment by alhambrav** [comment]
Verified fixed.
