### ISSUE TITLE
[social] API parameters marked as optional are required

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1106]
Calling `GET api/3/comments/moderation/:status` without parameters `sortBy` & `sortOrder` causes an exception:

```
java.lang.NullPointerException: null
	at org.craftercms.commons.mongo.AbstractJongoRepository.createSortQuery(AbstractJongoRepository.java:616) ~[crafter-commons-mongo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.craftercms.social.repositories.ugc.impl.UGCRepositoryImpl.findByModerationStatus(UGCRepositoryImpl.java:309) ~[classes/:3.0.0-SNAPSHOT]
	at org.craftercms.social.services.social.impl.SocialServicesImpl.findByModerationStatus(SocialServicesImpl.java:166) ~[classes/:3.0.0-SNAPSHOT]
```

**Comment by cortiz** [comment]
https://github.com/craftercms/social/pull/315

**Comment by jdrossl** [comment]
Verified
