### ISSUE TITLE
[studio] Copy/cut items with the same name as a child and paste to the parent breaks

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1117]
* Create a structure like this: 'Folder A' > 'Folder B' > 'Item A'. Then create another folder alongside 'Folder A' called 'Folder B', then cut 'Folder B' then paste it in 'Folder A', do same test with copy. Stack trace:
```	[ERROR] 2017-07-18 15:22:12,172 [ajp-nio-8009-exec-8] [content.ContentServiceImpl] | Content not found while moving content for site load-test from /site/website/tester-russ/harness/new/big-tree1 to /site/website/tester-russ/harness, new name is null 
	org.craftercms.studio.api.v1.exception.ServiceException: Unable to generate an alternative path for name collision: /site/website/tester-russ/harness/big-tree1
		at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.constructNewPathforCutCopy(ContentServiceImpl.java:957)
		at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.moveContent(ContentServiceImpl.java:639)
		at org.craftercms.studio.impl.v1.service.clipboard.ClipboardServiceImpl.pasteItems(ClipboardServiceImpl.java:113)
		at org.craftercms.studio.impl.v1.service.clipboard.ClipboardServiceImpl.paste(ClipboardServiceImpl.java:89)
		at org.craftercms.studio.api.v1.service.clipboard.ClipboardService$paste$1.call(Unknown Source)
		at scripts.api.impl.clipboard.SpringClipboardServices.paste(SpringClipboardServices.groovy:43)
		at scripts.api.impl.clipboard.SpringClipboardServices$paste$1.call(Unknown Source)
		at scripts.api.ClipboardServices.paste(ClipboardServices.groovy:31)
		at scripts.api.ClipboardServices$paste$2.call(Unknown Source)
		at paste-item_get.run(paste-item.get.groovy:11)
		at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:605)
		at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
		at org.craftercms.engine.controller.rest.RestScriptsController.executeScript(RestScriptsController.java:163)
		at org.craftercms.engine.controller.rest.RestScriptsController.handleRequestInternal(RestScriptsController.java:97)
		at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
		at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.craftercms.studio.impl.v1.web.security.access.StudioAuthenticationTokenProcessingFilter.doFilter(StudioAuthenticationTokenProcessingFilter.java:74)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:46)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:56)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:79)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.craftercms.studio.impl.v1.web.filter.MultiReadHttpServletRequestWrapperFilter.doFilter(MultiReadHttpServletRequestWrapperFilter.java:34)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
		at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:476)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
		at java.lang.String.substring(String.java:1967)
		at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.constructNewPathforCutCopy(ContentServiceImpl.java:932)
		... 86 more
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/790

**Comment by russdanner** [comment]
Verified
