### ISSUE TITLE
[studio-ui] Site preview and dashboard UI are broken in Chrome

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1160]
UI works fine in Firefox, Safari and Chrome incognito mode.
In Chrome normal window, cleaning cache (browsing data) helps once, after creating new site, it breaks again and after that not even clear cache helps.

**Comment by sumerjabri** [comment]
@dejan-brkic please add screenshots

**Comment by dejan-brkic** [comment]
Issue too unpredictable and i can not consistently reproduce it to get screenshots.

**Comment by dejan-brkic** [comment]
Dashboard:
![dashboard_error](https://user-images.githubusercontent.com/4053827/28631196-b560e9f0-722c-11e7-82e6-d7c0cea6fe39.png)

Preview:
![preview_error](https://user-images.githubusercontent.com/4053827/28631201-bb7c6dbe-722c-11e7-840a-c7f6a4643a96.png)
Log:
```
26-Jul-2017 17:53:48.039 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:735)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:879)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:594)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jvega-crafter** [comment]
This has been tested for several days, but it was not reproducible (using chrome as main browser), I also asked the team but nobody had the problem. Moving to test.

**Comment by dejan-brkic** [comment]
Closing ticket. I haven't seen this issue for a long time
