### ISSUE TITLE
[Studio] On Windows Approve and publish throws a NPE and shutdown processor.

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1209]
Steps:
1. Download and use  VM with windows 10 x64 from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ of phisical windows machine

2. Download and install the latest java 8 JDK from oracle page http://www.oracle.com/technetwork/java/javase/downloads/index.html

3. Set the JAVA_HOME environment variable to point the jdk just installed.

4. Download and unzip the crafter authoring bundle from http://downloads.craftersoftware.com/craftercms/community/3.0.0/crafter-cms-authoring.zip

5. Start it by running CRAFTER_HOME/bin/startup.sh (as an administrator the first time)
5.1 Ignore the mongodb issue

6. Once it's up, go to http://localhost:8080/studio

7. Log in and create a site using the editorial blueprint.

8. Approve and Publish the Home page from the upper toolbar.
 a NPE will be thrown 
`[ERROR] 2017-08-14 12:55:21,815 [studioSchedulerFactoryBean_Worker-7] [job.DeployContentToEnvironmentStore] | Unexpected error while executing deployment to environment store for site "site", number of items "1" 
java.lang.NullPointerException
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processItem(PublishingManagerImpl.java:185)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:130)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:72)
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ERROR] 2017-08-14 12:55:21,825 [studioSchedulerFactoryBean_Worker-7] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site: site 
java.lang.NullPointerException
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processItem(PublishingManagerImpl.java:185)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:130)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:72)
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)`

After pages are stuck are stuck in the `Processing` state and site becomes useless, server restart does not solve the problem.

Logs:
[logs.zip](https://github.com/craftercms/craftercms/files/1223299/logs.zip)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/847
