### ISSUE TITLE
[studio] Pull from published without -x and pub breaks

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1227]
Steps to Reproduce
===============
* Create a site
* Make changes
* Git pull on `published`
* Publish

**Comment by dejan-brkic** [comment]
Exact steps to reproduce:

1. create site from editorial BP
2. create new content
3. edit content from step 2
4. execute on published repo `git pull origin master`
5. publish content from step 2 using studio ui

Stack trace:
```
[ERROR] 2017-08-18 18:31:44,626 [studioSchedulerFactoryBean_Worker-7] [git.GitContentRepository] | Error when publishing site craftercms1227a to environment live
org.craftercms.studio.api.v1.service.deployment.DeploymentException: Conflict while cherry-pick commit id: 5ad66faff3b13335513a9fd26620449b8a24f933 for site craftercms1227a
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:847)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.deploy(DeployContentToEnvironmentStore.java:223)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:144)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:70)
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ERROR] 2017-08-18 18:31:44,627 [studioSchedulerFactoryBean_Worker-7] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site "craftercms1227a", number of items "1"
org.craftercms.studio.api.v1.service.deployment.DeploymentException: Error when publishing site craftercms1227a to environment live [commit ID = 5ad66faff3b13335513a9fd26620449b8a24f933]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:917)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.deploy(DeployContentToEnvironmentStore.java:223)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:144)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:70)
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ERROR] 2017-08-18 18:31:44,631 [studioSchedulerFactoryBean_Worker-7] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site: craftercms1227a
org.craftercms.studio.api.v1.service.deployment.DeploymentException: Error when publishing site craftercms1227a to environment live [commit ID = 5ad66faff3b13335513a9fd26620449b8a24f933]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:917)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.deploy(DeployContentToEnvironmentStore.java:223)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:144)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:70)
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/836

**Comment by dejan-brkic** [comment]
Solution steps (Git CLI)
0. git cherry-pick -> failed
1. git checkout --ours path/to/failed/content
2. git add .
3. git commit
