### ISSUE TITLE
[studio-ui] Error when clicking on "Search" from the context nav

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1356]
Create a site in Studio.
Click on the **Search** (magnifying glass) in the context nav

After clicking, all you get is a blank screen
![screen shot 2017-09-20 at 11 40 24 am](https://user-images.githubusercontent.com/25483966/30653286-ac116634-9df8-11e7-9766-8eddbd746545.png)

Here's the url listed on the blank screen:

```
http://localhost:8080/studio/search?site=myawesomesite&s=&context=default&includeAspects=cstudio-core:pageMetadata|cstudio-core:documentMetadata&selection=-1&mode=act&ipp=20&page=1&presearch=false&firstTime=true&searchId=4460b9e3-c2ad-5973-3ecc-3829f5fa3dea
```

 Here's the tomcat log when I click on the **Search** icon from an incognito chrome browser:
```
20-Sep-2017 13:33:53.388 INFO [http-nio-8080-exec-4] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:472)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:683)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jvega-crafter** [comment]
Hi @alhambrav, can you specify a little bit more? I'm not being able to reproduce it, I have the latest build, tested on google chrome with editorial and empty blueprints sites, thanks!

**Comment by alhambrav** [comment]
Hi @jvega-crafter .
I did a fresh install today of Studio (git clone) and just clicked on the magnifying glass (Search) from the context nav, which should have taken me to the search screen, but now just displays a blank screen.

Here's a short clip.
https://www.useloom.com/share/8bacf97a2ab94a05af0080a96d0db0c7

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/597

**Comment by alhambrav** [comment]
Verified fixed.
