### ISSUE TITLE
[test-suite] Errors when running the test suite in Windows OS

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1451]
There are errors when running the test-suite in Windows OS.

Here's the screenshot of the test report and the zip of the test report:

![screen shot 2017-10-16 at 2 00 34 pm](https://user-images.githubusercontent.com/25483966/31627219-7bd53a04-b27a-11e7-82df-73e854ab8b27.png)

[surefire-reports.zip](https://github.com/craftercms/craftercms/files/1388530/surefire-reports.zip)

Here's the output from the command line after running `gradlew.bat test`
```
:test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building studio-test-suite 2.5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ studio-test-suite ---
[INFO] Deleting C:\temp\craftercms\src\test-suite\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ studio-test-suite ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ studio-test-suite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ studio-test-suite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\temp\craftercms\src\test-suite\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ studio-test-suite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ studio-test-suite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 132 source files to C:\temp\craftercms\src\test-suite\target\test-classes
[WARNING] /C:/temp/craftercms/src/test-suite/src/test/java/org/craftercms/studio/test/utils/JsonResponse.java: C:\temp\craftercms\src\test-suite\src\test\java\org\craftercms\studio\test\utils\JsonResponse.java uses unchecked or unsafe operations.
[WARNING] /C:/temp/craftercms/src/test-suite/src/test/java/org/craftercms/studio/test/utils/JsonResponse.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ studio-test-suite ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
...
... TestNG 6.8beta 20120825_1010 by C?dric Beust (cedric@beust.com)
...

[TestNG] Running:
  C:\temp\craftercms\src\test-suite\src\test\resources\testng.xml

PASSED: try_to_delete_user

===============================================
    Try to delete user connected test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

PASSED: login_Test
PASSED: logOut_Test

===============================================
    Login Test
    Tests run: 2, Failures: 0, Skips: 0
===============================================

PASSED: createSiteEmpty
PASSED: logOut_Test
PASSED: delete_site

===============================================
    LogOut Test
    Tests run: 3, Failures: 0, Skips: 0
===============================================

PASSED: createSiteEmpty
PASSED: delete_site
FAILED: addNewContentEntry
org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (105, -109)
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MSEDGEWIN10', ip: '10.0.2.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=XP, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8), userDataDir=C:\Users\IEUser\AppData\Local\Temp\scoped_dir5900_24726}, takesHeapSnapshot=true, pageLoadStrategy=normal, unhandledPromptBehavior=, databaseEnabled=false, handlesAlerts=true, version=61.0.3163.100, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: c0b9e124be5653724e4d47de839fe82a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:275)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at org.craftercms.studio.test.cases.sitecontentbartestcases.AddNewContentEntryTest.createContent(AddNewContentEntryTest.java:106)
	at org.craftercms.studio.test.cases.sitecontentbartestcases.AddNewContentEntryTest.addNewContentEntry(AddNewContentEntryTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)


===============================================
    Add New Content Entry Test
    Tests run: 3, Failures: 1, Skips: 0
===============================================

PASSED: createSiteEmpty
PASSED: Add_New_Folder_test
PASSED: delete_site

===============================================
    Add New Folder Test
    Tests run: 3, Failures: 0, Skips: 0
===============================================

PASSED: cancel_create_site_process

===============================================
    Cancel Create Site Process Test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

PASSED: createSiteEmpty
PASSED: delete_site
FAILED: copyAndPasteContentTest
org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (105, -109)
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MSEDGEWIN10', ip: '10.0.2.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=XP, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8), userDataDir=C:\Users\IEUser\AppData\Local\Temp\scoped_dir6060_12886}, takesHeapSnapshot=true, pageLoadStrategy=normal, unhandledPromptBehavior=, databaseEnabled=false, handlesAlerts=true, version=61.0.3163.100, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: fc3c068cf6ed6c3c2815bec4416db379
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:275)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at org.craftercms.studio.test.cases.sitecontentbartestcases.CopyPasteContentTest.createContent(CopyPasteContentTest.java:110)
	at org.craftercms.studio.test.cases.sitecontentbartestcases.CopyPasteContentTest.copyAndPasteContentTest(CopyPasteContentTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)


===============================================
    Copy Paste Content Test
    Tests run: 3, Failures: 1, Skips: 0
===============================================

Terminate batch job (Y/N)? 

```

**Comment by sumerjabri** [comment]
@luishernandezmonge ping @alhambrav for access to a Windows server to help you figure this out.

**Comment by luishernandezmonge** [comment]
Currently, we opened the next ticket related to failed test cases of API suite: https://github.com/craftercms/craftercms/issues/1465
And for the studio UI failed test cases, I'm working on the fixes for those.

**Comment by luishernandezmonge** [comment]
Resolved with the refactoring of the test framework, it should works ok now

**Comment by alhambrav** [comment]
Hi!  There are still some errors when running the test suite in Windows and it seems to be stuck at the same place at the time I filed the ticket (It's been running for 3 hours and it displays the same thing as listed below for over 2 hours). 

```
===============================================
    Copy Paste Content Test
    Tests run: 3, Failures: 1, Skips: 0
===============================================
```

**Comment by luishernandezmonge** [comment]
@alhambrav Seems like when a test case fails, all the verbose (print of the current activity by terminal) of the execution gets stuck until the end of the execution, that think is that behavior does not happen on linux/mac.... continue reviewing this. will send the execution output to a text file to see of there is something that helps to see what's happen there.

**Comment by luishernandezmonge** [comment]
Currently, I executed it and notice something related to gradlew (watch this ticket: https://github.com/craftercms/craftercms/issues/1749).
However, running the test-suite using mvn command... I find that some test cases fails, I will work on the fixes for this test cases.

**Comment by alhambrav** [comment]
Verified the Windows test runs all the test suites all the way to the end and does not hang anymore.  There are still some test case failures, so, we'll file separate tickets for the test case failures encountered.  My main concern when I filed the ticket was that the test does not finish and just hangs.  

Closing the ticket.
