### ISSUE TITLE
[studio-ui] No menu appears when you right click on {id}.get.groovy script in headless bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1472]
Create a site using either the headless_blog or headless_store bp.
Open the **Sidebar** and navigate to the **scripts/rest/1** folder.
Expand all the folders, then right click on **{id}.get.groovy**
Notice that there is no menu (Upload, Delete, Edit, etc.) that appears when you right click.
There are no error messages in the tomcat log when you right click on **{id}.get.groovy**  usually, but sometimes, when you refresh the page and try to right click again, this message appears in the tomcat log:
```
19-Oct-2017 10:25:20.695 INFO [http-nio-8080-exec-10] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:472)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:683)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Here's a short clip:
https://www.useloom.com/share/10999ff687ce4d60a0a56f74eef3c16b

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/650

**Comment by alhambrav** [comment]
Verified fixed.
