### ISSUE TITLE
[craftercms] Error when running init-site.sh

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1523]
Cannot setup a site for delivery.  Error when running the init-site.sh script.

Run the init-site.sh script:
```
➜  bin git:(master) ./init-site.sh myawesomesite /Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/sites/myawesomesite/published
Creating Solr Core
{"message":"OK"}
Creating Deployer Target
{"message":"OK"}
Done
```

Look at the delivery tomcat log, notice the error message:
```
[INFO] 2017-11-01 12:15:04,377 [http-nio-9080-exec-5] [default] [context.SiteContextManager] | ==================================================
[INFO] 2017-11-01 12:15:04,377 [http-nio-9080-exec-5] [default] [context.SiteContextManager] | </Creating site context: default>
[INFO] 2017-11-01 12:15:04,377 [http-nio-9080-exec-5] [default] [context.SiteContextManager] | ==================================================
[INFO] 2017-11-01 12:15:04,451 [http-nio-9080-exec-6] [] [context.SiteContextManager] | ==================================================
[INFO] 2017-11-01 12:15:04,452 [http-nio-9080-exec-6] [] [context.SiteContextManager] | <Creating site context: myawesomesite>
[INFO] 2017-11-01 12:15:04,452 [http-nio-9080-exec-6] [] [context.SiteContextManager] | ==================================================
[ERROR] 2017-11-01 12:15:04,452 [http-nio-9080-exec-6] [] [context.SiteContextManager] | Cannot resolve root folder for site 'myawesomesite'
org.craftercms.core.exception.RootFolderNotFoundException: Root folder file:../data/repos/sites/myawesomesite/sandbox/ not found (make sure that it has a valid URL prefix (e.g. file:))
	at org.craftercms.core.store.impl.filesystem.FileSystemContentStoreAdapter.createContext(FileSystemContentStoreAdapter.java:68)
	at org.craftercms.engine.targeting.impl.TargetedContentStoreAdapter.createContext(TargetedContentStoreAdapter.java:75)
	at org.craftercms.core.service.impl.ContentStoreServiceImpl.createContext(ContentStoreServiceImpl.java:159)
	at org.craftercms.engine.service.context.SiteContextFactory.createContext(SiteContextFactory.java:257)
	at org.craftercms.engine.service.context.SiteContextManager.getContext(SiteContextManager.java:203)
	at org.craftercms.engine.service.context.SiteContextResolverImpl.getContext(SiteContextResolverImpl.java:77)
	at org.craftercms.engine.service.context.SiteContextResolverImpl.getContext(SiteContextResolverImpl.java:60)
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:39)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[WARN] 2017-11-01 12:15:04,453 [http-nio-9080-exec-6] [] [context.SiteContextResolverImpl] | Unable to retrieve context for site name 'myawesomesite'. Using fallback site
```

**Comment by cortiz** [comment]
Solve in #1529
