### ISSUE TITLE
[studio] FileNotFoundException when restoring Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1524]
FileNotFoundException when restoring Studio.
Studio runs okay after restoring but there are exceptions on the output screen when you restore a backup.

1. Create two sites in Studio.
2. Backup Studio by running
```
./crafter.sh backup
```

3.Stop Studio. 
4. Restore using the backup file you just created.  Notice the FileNotFoundException messages on your screen.  Here's some sample exceptions:

```
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/fd/764cae672db72446fd84f4471e6b3081bbf7b0
java.io.FileNotFoundException: /Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/fe/1a9696eb564a78884a4f5679fd7777cd70ce00 (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.craftercms.bundle.utils.actions.Unzip.execute(Unzip.java:60)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/fe/1a9696eb564a78884a4f5679fd7777cd70ce00
java.io.FileNotFoundException: /Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/1d5d80b86c4d97b0f32c016679e93c078dcfa2 (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.craftercms.bundle.utils.actions.Unzip.execute(Unzip.java:60)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/1d5d80b86c4d97b0f32c016679e93c078dcfa2
java.io.FileNotFoundException: /Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/88dbf70374a9e04db9ef15c2437f66022c353a (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.craftercms.bundle.utils.actions.Unzip.execute(Unzip.java:60)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/88dbf70374a9e04db9ef15c2437f66022c353a
java.io.FileNotFoundException: /Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/ad3ce446b2d34e7834bf36d056616ab266a333 (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.craftercms.bundle.utils.actions.Unzip.execute(Unzip.java:60)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/objects/ff/ad3ce446b2d34e7834bf36d056616ab266a333
/Users/vita/temp/test2/craftercms/crafter-authoring/data/repos/./sites/myawesomesite/sandbox/.git/refs/heads/master
```

Also notice the notes listed:
```
2017-11-01 11:08:36 140737173017536 [Note] Using unique option prefix 'pid' is error-prone and can break in the future. Please use the full name 'pid_file' instead.
2017-11-01 11:08:36 140737173017536 [Note] /Users/vita/temp/test2/craftercms/crafter-authoring/bin/dbms/bin/mysqld (mysqld 10.1.28-MariaDB) starting as process 55734 ...
2017-11-01 11:08:36 140737173017536 [Warning] Setting lower_case_table_names=2 because file system for /Users/vita/temp/test2/craftercms/crafter-authoring/data/db/ is case insensitive
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: The InnoDB memory heap is disabled
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Compressed tables use zlib 1.2.3
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Using SSE crc32 instructions
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Completed initialization of buffer pool
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Highest supported file format is Barracuda.
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: 128 rollback segment(s) are active.
2017-11-01 11:08:36 140737173017536 [Note] InnoDB: Waiting for purge to start
2017-11-01 11:08:36 140737173017536 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.36-82.2 started; log sequence number 3064941
2017-11-01 11:08:36 123145412075520 [Note] InnoDB: Dumping buffer pool(s) not yet started
2017-11-01 11:08:36 140737173017536 [Note] Plugin 'FEEDBACK' is disabled.
2017-11-01 11:08:36 140737173017536 [Note] Server socket created on IP: '::'.
2017-11-01 11:08:36 140737173017536 [Note] /Users/vita/temp/test2/craftercms/crafter-authoring/bin/dbms/bin/mysqld: ready for connections.
Version: '10.1.28-MariaDB'  socket: '/tmp/mysql.sock'  port: 33306  CrafterCms
2017-11-01 11:08:41 123145414221824 [Note] /Users/vita/temp/test2/craftercms/crafter-authoring/bin/dbms/bin/mysqld: Normal shutdown
```

Here's another scenario where you get the FileNotFound Exception.   It would also be nice if we give the user a warning that the current state of Studio will be clobbered when we restore a backup file or something to that effect:

1. Create a site in Studio say, `myawesomesite`
2. Backup Studio.
3. Create another site, say `helloworld`
4. Stop Studio.
5. Restore using the backup file we created on step 2.  Notice the error message in the output:
```
Waiting for studio to start
Running sync for site helloworld
Calling 'http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json' with body: { "site_id":"helloworld" }
java.io.FileNotFoundException: http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at org.craftercms.bundle.utils.actions.ApiPost.execute(ApiPost.java:36)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
Running sync for site myawesomesite
Calling 'http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json' with body: { "site_id":"myawesomesite" }
{"message":"OK"}Restore completed
```

It looks like Studio data or something is not being wiped before restoring the backup file, since from the message above, it is looking for the `helloworld` site, which is not in the backup file we are trying to restore.  Now, after the restore, if you try to create a site called `helloworld` again, it will give you this error: on your browser:

![screen shot 2017-11-01 at 2 55 12 pm](https://user-images.githubusercontent.com/25483966/32291870-be7b4e42-bf14-11e7-8a05-d01e4710cf5a.png)

And, if you look at your tomcat log for authoring, notice the error message:
 
```
[ERROR] 2017-11-01 14:55:08,182 [http-nio-8080-exec-9] [controller.ExceptionHandlers] | Request /crafter-search/api/2/admin/index/create failed with status 500
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8694/solr: Core with name 'helloworld' already exists.
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:610)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:166)
	at org.craftercms.search.service.impl.SolrAdminService.createIndex(SolrAdminService.java:122)
	at org.craftercms.search.rest.controller.v2.AdminRestController.createIndex(AdminRestController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2017-11-01 14:55:08,210 [http-nio-8080-exec-10] [site.SiteServiceImpl] | Error while creating site: helloworld ID: helloworld from blueprint: empty. Is the Search running and configured correctly in Studio?
org.craftercms.studio.api.v1.exception.ServiceException: Error while creating search index for site helloworld. Request URL: http://localhost:8080/crafter-search/api/2/admin/index/create. Request Body: { "id" : "helloworld" }. Response: {"message":"Error from server at http://localhost:8694/solr: Core with name 'helloworld' already exists."}
	at org.craftercms.studio.impl.v1.service.search.SearchServiceImpl.createIndex(SearchServiceImpl.java:62)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSiteFromBlueprint(SiteServiceImpl.java:277)
	at org.craftercms.studio.api.v1.service.site.SiteService$createSiteFromBlueprint$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at scripts.api.impl.site.SpringSiteServices.createSiteFromBlueprint(SpringSiteServices.groovy:64)
	at scripts.api.impl.site.SpringSiteServices$createSiteFromBlueprint$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at scripts.api.SiteServices.createSiteFromBlueprint(SiteServices.groovy:67)
	at scripts.api.SiteServices$createSiteFromBlueprint$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at create_post.run(create.post.groovy:68)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:605)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
	at org.craftercms.engine.controller.rest.RestScriptsController.executeScript(RestScriptsController.java:163)
	at org.craftercms.engine.controller.rest.RestScriptsController.handleRequestInternal(RestScriptsController.java:97)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.craftercms.studio.impl.v1.web.security.access.StudioAuthenticationTokenProcessingFilter.doFilter(StudioAuthenticationTokenProcessingFilter.java:77)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:46)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:56)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.craftercms.studio.impl.v1.web.filter.MultiReadHttpServletRequestWrapperFilter.doFilter(MultiReadHttpServletRequestWrapperFilter.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdrossl** [comment]
@sumerjabri how should we handle the second example? should the restore wipe all data before starting to make sure that studio will be in the exact state from the backup?

**Comment by sumerjabri** [comment]
@jdrossl We must warn the user that we're about to do that.

"Warning, you're about to restore Crafter Studio from a backup, which will wipe the existing sites and associated database and replace everything with the restored data. If you care about the existing state of the system then stop this process, backup the system, and then attempt the restore. Are you sure you want to proceed? [y/N]"

See if you can capture a "y" (or "Y") to proceed, otherwise cancel.

**Comment by alhambrav** [comment]
Verified fixed.
