### ISSUE TITLE
[craftercms] Can't create a site : SolrException section of solr.xml contains duplicated 'coreRootDirectory'

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1530]
Sometimes you cannot create a site because of a SolrException that a section of solr.xml contains duplicated 'coreRootDirectory'.  

Here's the Solr Log:
```
2017-11-02 17:40:20.209 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8694
2017-11-02 17:40:20.225 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: C:\temp\craftercms\crafter-authoring\bin\solr
2017-11-02 17:40:20.366 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2017-11-02T17:40:20.241Z
2017-11-02 17:40:20.444 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: C:\temp\craftercms\crafter-authoring\bin\solr\server\solr
2017-11-02 17:40:20.538 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from C:\temp\craftercms\crafter-authoring\bin\solr\server\solr\solr.xml
2017-11-02 17:40:21.804 ERROR (main) [   ] o.a.s.s.SolrDispatchFilter Could not start Solr. Check solr/home property and the logs
2017-11-02 17:40:22.178 ERROR (main) [   ] o.a.s.c.SolrCore null:org.apache.solr.common.SolrException: <solr> section of solr.xml contains duplicated 'coreRootDirectory'
        at org.apache.solr.core.SolrXmlConfig.checkForDuplicates(SolrXmlConfig.java:207)
        at org.apache.solr.core.SolrXmlConfig.readNodeListAsNamedList(SolrXmlConfig.java:199)
        at org.apache.solr.core.SolrXmlConfig.fromConfig(SolrXmlConfig.java:74)
        at org.apache.solr.core.SolrXmlConfig.fromInputStream(SolrXmlConfig.java:131)
        at org.apache.solr.core.SolrXmlConfig.fromFile(SolrXmlConfig.java:113)
        at org.apache.solr.core.SolrXmlConfig.fromSolrHome(SolrXmlConfig.java:141)
        at org.apache.solr.servlet.SolrDispatchFilter.loadNodeConfig(SolrDispatchFilter.java:265)
        at org.apache.solr.servlet.SolrDispatchFilter.createCoreContainer(SolrDispatchFilter.java:233)
        at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:167)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:873)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:458)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
        at org.eclipse.jetty.start.Main.start(Main.java:457)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
```

If you look at the solr.xml file, you see the duplicates mentioned in the log:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<solr>
<solrcloud>
<str name="host">${host:}</str>
<int name="hostPort">${jetty.port:8983}</int>
<str name="hostContext">${hostContext:solr}</str>
<bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>
<int name="zkClientTimeout">${zkClientTimeout:30000}</int>
<int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
<int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>
<str name="zkCredentialsProvider">
${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}
</str>
<str name="zkACLProvider">
${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}
</str>
</solrcloud>
<shardHandlerFactory name="shardHandlerFactory" class="HttpShardHandlerFactory">
<int name="socketTimeout">${socketTimeout:600000}</int>
<int name="connTimeout">${connTimeout:60000}</int>
</shardHandlerFactory>
<str name="coreRootDirectory">${crafter.solr.index:data/indexes}</str>
<str name="coreRootDirectory">${crafter.solr.index:data/indexes}</str>
<str name="coreRootDirectory">${crafter.solr.index:data/indexes}</str>
</solr>

```

I have encountered it at least 5 times, but it does not happen all the time.  All the times I encountered it, was a fresh install.  Twice on OS X and three times on Windows.  
All three times in Windows, I sent a ctrl + c command to stop it while deploying, and then I ran:
```
gradlew.bat build deploy start
```
Once Studio starts, I try to create a site and I get the error mentioned above.

**Comment by alhambrav** [comment]
Cannot reproduce anymore on Windows.  
Fixed by PR https://github.com/craftercms/craftercms/pull/1529
