### ISSUE TITLE
[craftercms] "IOException" when backing up Studio in Windows OS

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1561]
Backup and restore seems to be working okay, but there is a `java.io.IOException` when you run the backup script.

Using Windows OS, create a site.
Backup Studio.  Notice the output:

```
"Adding solr indexes"
Writing file: C:\temp\craftercms\crafter-authoring\temp\indexes.zip
Adding .\myawesomesite\core.properties
Adding .\myawesomesite\data\index\segments_2
Adding .\myawesomesite\data\index\write.lock
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at org.craftercms.bundle.utils.actions.Zip.copy(Zip.java:64)
        at org.craftercms.bundle.utils.actions.Zip.lambda$execute$0(Zip.java:43)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.craftercms.bundle.utils.actions.Zip.execute(Zip.java:38)
        at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
Adding .\myawesomesite\data\index\_u.fdt
Adding .\myawesomesite\data\index\_u.fdx
Adding .\myawesomesite\data\index\_u.fnm
Adding .\myawesomesite\data\index\_u.nvd
Adding .\myawesomesite\data\index\_u.nvm
Adding .\myawesomesite\data\index\_u.si
```

**Comment by jdrossl** [comment]
@sumerjabri `write.lock` is an empty file that solr uses, should we add any validation or can we just ignore the exception?

**Comment by alhambrav** [comment]
Verified fixed.
