### ISSUE TITLE
[headless-blueprints] blog and store blueprints do not work with 3.0.5 build

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1864]
### Expected behavior
Rest calls should return proper responses

### Actual behavior
Rest calls fail due groovy exceptions related to .text and .toInstant()

```
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: No such property: text for class: java.lang.String
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
```

```
Caused by: groovy.lang.MissingMethodException: No signature of method: org.dom4j.tree.DefaultElement.toInstant() is applicable for argument types: () values: []
Possible solutions: content()
```

**Comment by avasquez614** [comment]
PR craftercms/studio#1041

**Comment by russdanner** [comment]
VERIFIED
