### ISSUE TITLE
CRAFTERCMS-2126: Uploading images to /static-assets/images/ will throw a DB exception

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#190]
Original JIRA Fix Versions:
2.5.2, 2.6.0, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Configure a Image Upload data source
Configure the path to be /static-assets/images/
Try to upload a image
Stack trace:

{noformat}
[ERROR] 2016-08-22 11:48:51,946 [http-nio-9080-exec-3] [content.ContentServiceImpl] | Error processing content
org.springframework.dao.DuplicateKeyException:
### Cause: java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160822110851171' defined on 'CSTUDIO_OBJECTSTATE'.
; SQL []; The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160822110851171' defined on 'CSTUDIO_OBJECTSTATE'.; nested exception is java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160822110851171' defined on 'CSTUDIO_OBJECTSTATE'.
       	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
       	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
       	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
       	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
{noformat}

{noformat}
Caused by: groovy.lang.MissingPropertyException: No such property: name for class: java.lang.String
       	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
       	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
       	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293)
       	at asset-upload.run(asset-upload.groovy:119)
       	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:589)
       	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
       	... 82 more
[ERROR] 2016-08-22 11:48:51,951 [http-nio-9080-exec-3] [impl.DefaultExceptionHandler] | POST http://localhost:9080/studio/asset-upload?nocache=Mon%20Aug%2022%202016%2011:48:51%20GMT-0600%20(CST) failed
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.craftercms.engine.exception.ScriptException: No such property: name for class: java.lang.String
       	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:973)
       	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
       	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       	at org.craftercms.studio.impl.v1.repository.cached.ResponseCacheFilter.doFilter(ResponseCacheFilter.java:44)
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
{noformat}

HTTP Request:
{noformat}
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,es;q=0.6
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:5291
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryjsryTX4650ZFeNRd
Cookie:JSESSIONID=319F5195576D36BBAAE821CD2DDDEAA1; tst-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22%2Fsite%2Fwebsite%2Fen%22%5D%7D; JSESSIONID=D899A0957E47277A68581778DA4B7733; wcm-site-dropdown-prefs-default=%7B%22height%22%3A%22180px%22%2C%22width%22%3A%22225px%22%2C%22visible%22%3Atrue%2C%22scrollX%22%3A0%2C%22scrollY%22%3A0%7D; crafterSite=tst
Host:localhost:9080
Origin:http://localhost:9080
Referer:http://localhost:9080/studio/form?site=tst&form=/page/generic&path=/site/website/en/about-us/index.xml&iceComponent=true&edit=true&editorId=3fd08d80-35fa-779b-a8fa-bd253659cc2a
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

------WebKitFormBoundaryjsryTX4650ZFeNRd
Content-Disposition: form-data; name="site"

tst
------WebKitFormBoundaryjsryTX4650ZFeNRd
Content-Disposition: form-data; name="path"

/static-assets/images/
------WebKitFormBoundaryjsryTX4650ZFeNRd
Content-Disposition: form-data; name="file"; filename="image003.png"
Content-Type: image/png

------WebKitFormBoundaryjsryTX4650ZFeNRd--
{noformat}:
----------
Original JIRA Comments:
Check the data source. For some reason the trailing / on the image path gives an issue
If that's it this is a duplicate ticket.
----------
please check per comments
----------
correct without the trailing / works fine 
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2126
----------

**Comment by russdanner** [comment]
Duplicate of // bug

Paths in data sources cannot end in /, studio is not tolerant of this.  Ticket requests an update to allow this.
