### ISSUE TITLE
[docs] Add error that appears when using proxies for Deployer Troubleshoot doc

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1971]
http://docs.craftercms.org/en/3.0/system-administrators/deployer/debugging-deployer-issues.html. Add a section that explains that if the Deployer is not able to clone the remote repository and an error like this one appears in the logs

```
org.eclipse.jgit.errors.TransportException: ssh://jdoe@server2.example.com:63022/path/to/repo: Connection timed out (Connection timed out)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:137)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:274)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:169)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
    ... 15 common frames omitted
```
and doing a manual `git clone ssh://jdoe@server2.example.com:63022/path/to/repo` from the command line works, it's very probable that there's a proxy between the servers. Right now the deployer doesn't support connections through proxies, but it might in a future update.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/496

**Comment by avasquez614** [comment]
Verified
