### ISSUE TITLE
[studio] update publishing log messages to indicate environment

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2333]
### Expected behavior
include the environment in the log messages for publishing:

Example:

```
[INFO] 2018-08-06 17:24:19,265 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Starting Bulk Publish to 'Staging' for path / site testx
[INFO] 2018-08-06 17:24:19,316 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Deploying package of 1 items to 'Statging' for site testx path /config/studio/site-config.xml
[INFO] 2018-08-06 17:24:19,348 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Finished Bulk Publish for 'Staging' for path / site testx
```
* change "Go Live" to  publishing
* add enviroment

### Actual behavior
Current format:
```
[INFO] 2018-08-06 17:24:19,265 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Starting Bulk Go Live for path / site testx
[INFO] 2018-08-06 17:24:19,316 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Deploying package of 1 items for site testx path /config/studio/site-config.xml
[INFO] 2018-08-06 17:24:19,348 [http-nio-8080-exec-7] [deployment.DmPublishServiceImpl] | Finished Bulk Go Live for path / site testx
```

### Steps to reproduce the problem
* Create a new site 
* Got to site-config -> publishing
* Bulk publish to Live (and staging)

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-604717
Build Number: 60471700b8bdb6d25f7b93e23d710e061c18fd23
Build Date/Time: 08-06-2018 17:15:09 -0400

#### OS
Any

#### Browser
ANy

**Comment by dejan-brkic** [comment]
Done
PR:
3.0.x: https://github.com/craftercms/studio/pull/1227
3.1.x: https://github.com/craftercms/studio/pull/1228

**Comment by russdanner** [comment]
Error message does not indicate what environment:
```
[ERROR] 2018-09-05 23:15:38,931 [studioSchedulerFactoryBean_Worker-2] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site: dazzle-new
org.craftercms.studio.api.v1.service.deployment.DeploymentException: Error when publishing site dazzle-new to environment live [commit ID = f8d296cd3509a5189fca67d5c3b293af7ec42010]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:1317)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.deploy(DeployContentToEnvironmentStore.java:320)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.processJobs(DeployContentToEnvironmentStore.java:169)
	at org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore.execute(DeployContentToEnvironmentStore.java:103)
	at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:265)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)```

Update to include
Error while executing deployment to environment (ENVIRONMENT) store for site: dazzle-new

**Comment by russdanner** [comment]
```[ERROR] 2018-09-05 23:15:38,931 [studioSchedulerFactoryBean_Worker-2] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site: dazzle-new
org.craftercms.studio.api.v1.service.deployment.DeploymentException: Error when publishing site dazzle-new to environment live [commit ID = f8d296cd3509a5189fca67d5c3b293af7ec42010]
```
