### ISSUE TITLE
[studio] NPE on API 2 operations

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2435]
### Expected behavior
Operations that allow usernames and ids should work if one of them is empty if both of them are empty the result should be a `400 BAD_REQUEST`.

### Actual behavior
If any of the fields is null or empty a `500 INTERNAL_ERROR` is returned.

### Steps to reproduce the problem
* Call https://app.swaggerhub.com/apis/craftercms/studio/2.0.2#/groups/addGroupMembers, https://app.swaggerhub.com/apis/craftercms/studio/2.0.2#/groups/removeGroupMembers, https://app.swaggerhub.com/apis/craftercms/studio/2.0.2#/users/enableUser or https://app.swaggerhub.com/apis/craftercms/studio/2.0.2#/users/disableUser with only one of the fields in the request body.

### Log/stack trace (use https://gist.github.com)

```
Caused by: java.lang.NullPointerException
    at java.util.ArrayList.addAll(ArrayList.java:581)
    at org.craftercms.studio.impl.v2.service.security.DbSecurityProvider.addGroupMembers(DbSecurityProvider.java:297)
    at org.craftercms.studio.impl.v2.service.security.MappedSecurityProvider.addGroupMembers(MappedSecurityProvider.java:168)
    at org.craftercms.studio.impl.v2.service.security.GroupServiceImpl.addGroupMembers(GroupServiceImpl.java:104)
    at org.craftercms.studio.controller.rest.v2.GroupsController.addGroupMembers(GroupsController.java:190)
```

#### Version
3.1.0-SNAPSHOT

#### OS
MacOS

#### Browser
Chrome

**Comment by avasquez614** [comment]
Verified
