### ISSUE TITLE
[studio] Upgrades should rollback when a db script fails

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2656]
## Describe the bug
During upgrades, if a db script fails to execute the system will commit some of the changes and then throw an exception

## Expected behavior
All changes made by the db script should be discarted when there is an error.

### Version
3.1.x

### OS
MacOS

**Comment by jdrossl** [comment]
@sumerjabri after some testing the code is doing the rollback, the issue is that MariaDB doesn't support rollback for [DDL statments](https://mariadb.com/kb/en/library/start-transaction/#ddl-statements) so there is no way for us to handle this case

**Comment by jdrossl** [comment]
@alhambrav This is a summary of the issue:

Because MariaDB doesn't support rollback for schema changes, if one of our upgrade scripts fails our only option is to collect the data from the logs and recover the db manually (checking which statement failed and completing the upgrade).

For example these are the log messages of a script that failed because of a special case with existing data in a table that needed to be changed as part of the upgrade:

```
Caused by: org.craftercms.studio.api.v2.exception.UpgradeException: Error executing sql script upgrade-3.1.0.6-to-3.1.0.7.sql
	at org.craftercms.studio.impl.v2.upgrade.operations.DbScriptUpgradeOperation.execute(DbScriptUpgradeOperation.java:122)
	at org.craftercms.studio.impl.v2.upgrade.pipeline.DefaultUpgradePipelineImpl.execute(DefaultUpgradePipelineImpl.java:67)
	at org.craftercms.studio.api.v2.upgrade.UpgradePipeline.execute(UpgradePipeline.java:42)
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.upgradeDatabaseAndConfiguration(DefaultUpgradeManagerImpl.java:87)
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.init(DefaultUpgradeManagerImpl.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1763)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1700)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	... 45 more
Caused by: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: ALTER TABLE `cluster` ADD UNIQUE IF NOT EXISTS `uq_cl_git_remote_name` (`git_remote_name`)
.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:12) Duplicate entry '' for key 'uq_cl_git_remote_name'
```

For this case the solution would be to manually set unique values for the existing rows in the table and then execute the remaining statements in the script.

Because the script was not executed completely the system is in an undefined state between the two versions and if it is restarted the upgrade will be attempted again resulting in a different message:

```
Caused by: org.craftercms.studio.api.v2.exception.UpgradeNotSupportedException: The current database version can't be upgraded
	at org.craftercms.studio.impl.v2.upgrade.operations.DbScriptUpgradeOperation.execute(DbScriptUpgradeOperation.java:105)
	at org.craftercms.studio.impl.v2.upgrade.pipeline.DefaultUpgradePipelineImpl.execute(DefaultUpgradePipelineImpl.java:67)
	at org.craftercms.studio.api.v2.upgrade.UpgradePipeline.execute(UpgradePipeline.java:42)
```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/651
