### ISSUE TITLE
[search] Error while performing search indexing

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2828]
## Describe the bug
An error is shown when a site is created and a search indexing is performed

## To Reproduce
1. Clone, init build start authoring from develop branch
2. Create a site from any BP
3. Check `crafter-authoring/logs/deployer/crafter-deployer.out`

## Expected behavior
No errors while search indexing 

## Logs
```
2019-02-05 18:56:07.525  INFO 22019 --- [   deployment-2] .c.d.i.p.AbstractSearchIndexingProcessor : Performing search indexing...
2019-02-05 18:56:07.630  INFO 22019 --- [   deployment-2] o.c.s.e.impl.ElasticSearchServiceImpl    : [test] Indexing document /site/website/crafter-level-descriptor.level.xml
2019-02-05 18:56:07.630  INFO 22019 --- [   deployment-2] o.c.s.e.impl.ElasticSearchServiceImpl    : [test] Deleting document /site/website/crafter-level-descriptor.level.xml
2019-02-05 18:56:07.632  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Indexing document /site/website/crafter-level-descriptor.level.xml
2019-02-05 18:56:07.632  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Deleting document /site/website/crafter-level-descriptor.level.xml
2019-02-05 18:56:07.868  INFO 22019 --- [   deployment-2] o.c.s.e.impl.ElasticSearchServiceImpl    : [test] Indexing document /site/website/index.xml
2019-02-05 18:56:07.868  INFO 22019 --- [   deployment-2] o.c.s.e.impl.ElasticSearchServiceImpl    : [test] Deleting document /site/website/index.xml
2019-02-05 18:56:07.873  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Indexing document /site/website/index.xml
2019-02-05 18:56:07.874  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Deleting document /site/website/index.xml
2019-02-05 18:56:07.969  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Search values for field _id
2019-02-05 18:56:07.975  INFO 22019 --- [   deployment-2] o.c.s.e.impl.ElasticSearchServiceImpl    : [test] Flushing index
2019-02-05 18:56:08.006  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Found 0 matching documents
2019-02-05 18:56:08.012  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Search values for field _id
2019-02-05 18:56:08.026  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Found 0 matching documents
2019-02-05 18:56:08.032  INFO 22019 --- [   deployment-1] o.c.s.b.i.AbstractMetadataBatchIndexer   : Start processing @ test-authoring
2019-02-05 18:56:08.057  INFO 22019 --- [   deployment-1] o.c.s.e.impl.ElasticSearchServiceImpl    : [test-authoring] Search for id /site/website/crafter-level-descriptor.level.xml
2019-02-05 18:56:08.070 ERROR 22019 --- [   deployment-1] .c.d.i.p.AbstractMainDeploymentProcessor : Processor 'authoringElasticSearchIndexingProcessor' for target 'test-authoring' failed

org.craftercms.deployer.api.exceptions.DeployerException: Error while performing search indexing; nested exception is org.craftercms.search.elasticsearch.exception.ElasticSearchException: [test-authoring] Error executing search SearchRe
quest{searchType=QUERY_THEN_FETCH, indices=[test-authoring], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=tru
e, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=null, source={"query":{"term":{"localId":{"value":"/site/website/crafter-level-descriptor.level.xml","boost":1.0}}}}}
        at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.doExecute(AbstractSearchIndexingProcessor.java:246)
        at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.execute(AbstractMainDeploymentProcessor.java:71)
        at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:76)
        at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:68)
        at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:305)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.craftercms.search.elasticsearch.exception.ElasticSearchException: [test-authoring] Error executing search SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test-authoring], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=null, source={"query":{"term":{"localId":{"value":"/site/website/crafter-level-descriptor.level.xml","boost":1.0}}}}}
        at org.craftercms.search.elasticsearch.impl.ElasticSearchServiceImpl.searchId(ElasticSearchServiceImpl.java:144)
        at org.craftercms.search.elasticsearch.batch.ElasticSearchIndexingUtils.doSearchById(ElasticSearchIndexingUtils.java:42)
        at org.craftercms.search.elasticsearch.batch.ElasticSearchContentTypeMetadataBatchIndexer.getCurrentData(ElasticSearchContentTypeMetadataBatchIndexer.java:56)
        at org.craftercms.search.batch.impl.AbstractMetadataBatchIndexer.lambda$updateIndex$2(AbstractMetadataBatchIndexer.java:103)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.craftercms.search.batch.impl.AbstractMetadataBatchIndexer.updateIndex(AbstractMetadataBatchIndexer.java:93)
        at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.doExecute(AbstractSearchIndexingProcessor.java:238)
        ... 9 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.craftercms.search.elasticsearch.impl.ElasticSearchServiceImpl.searchId(ElasticSearchServiceImpl.java:142)
        ... 15 common frames omitted

2019-02-05 18:56:08.071  INFO 22019 --- [   deployment-1] .c.d.i.p.AbstractMainDeploymentProcessor : ----- </ authoringElasticSearchIndexingProcessor @ test-authoring > -----
2019-02-05 18:56:08.071  INFO 22019 --- [   deployment-1] .c.d.i.p.AbstractPostDeploymentProcessor : ----- < fileOutputProcessor @ test-authoring > -----
```

### Version
Studio Version Number: 3.1.0-SNAPSHOT-fc34e0
Build Number: fc34e02e9c80f65a25dd880080c844425df7d994
Build Date/Time: 02-05-2019 12:50:09 -0600

### OS
Linux

### Browser
What browser did you use to produce the bug.

**Comment by yacdaniel** [comment]
Verified fixed.
