### ISSUE TITLE
cluster: deployer doesn't run in sites that get synced

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2861]
## Describe the bug
Site created in cluster member A is sync in cluster member B, but deployer doesn't run in the cluster member B. Cluster member A has all the deployer logs from the site
```
crafter-deployer.out
deployer-general.log
editorial_test-authoring-deployments.csv
editorial_test-authoring.log
editorial_test-preview-deployments.csv
editorial_test-preview.log
spring.log
```
cluster member B has none, only:
```
crafter-deployer.out
deployer-general.log
spring.log
```

manually running 
```
curl --request POST \
  --url http://localhost:9191/api/1/target/deploy/preview/editorial_test \
  --header 'content-type: application/json' \
  --data '{
}'
```
fix the preview issue in cluster member B

## To Reproduce
1. Have a cluster with 2 members
2. Create a site from website_editorial BP in cluster member A
3. Wait until cluster sync and go to site preview in cluster member B

## Expected behavior
No errors and preview work fine in all cluster members.

## Logs
[catalina.out member B](https://gist.github.com/yacdaniel/026d73a61f35508b21bee99de4f09e36)
[crafter-deployer.out member a](https://gist.github.com/yacdaniel/0581be4452caa1f1a49285e9d51c76e6)
[crafter-deployer.out member b](https://gist.github.com/yacdaniel/a7b8b8a6eeb43637bf11747a3d7ebe8c)

### Version
Studio Version Number: 3.1.0-SNAPSHOT-d58ec0
Build Number: d58ec09614f6a0f549da0a2dfb09c3fcfb7d7578
Build Date/Time: 02-19-2019 08:19:00 -0600

### OS
Linux

### Browser
What browser did you use to produce the bug.

**Comment by dejan-brkic** [comment]
This is deployer issue. Related to ES. Deployer creates targets, but does not create ES index propery. In ES log there are not relevant errors except for this one
```
[2019-02-19T20:14:26,302][DEBUG][o.e.a.s.TransportSearchAction] [cBJWUBW] [craftercms2861][3], node[cBJWUBW3Q5q8ndC_7aMAcw], [P], s[STARTED], a[id=9YK8EEA5RKC1ryyERb2P_w]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[craftercms2861], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, source={"from":0,"size":10,"query":{"bool":{"must":[{"query_string":{"query":"content-type:\"/page/article\" AND featured_b:true","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"filter":[{"query_string":{"query":"-disabled:\"true\"","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},{"query_string":{"query":"-expired_dt:[* TO now]","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"sort":[{"date_dt":{"order":"desc"}}]}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [cBJWUBW][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [date_dt] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:319) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:153) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:823) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:656) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:631) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:388) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:360) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:356) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.0.jar:6.6.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Deployer log does not have any errors for site creation on node B

**Comment by jdrossl** [comment]
@dejan-brkic while doing some quick tests with @yacdaniel we found that the index is created in ES as expected, it is the first deploy event that is not triggered.

That is why a manual deploy fixes the issue because the index exists but remains empty.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1481

**Comment by yacdaniel** [comment]
Verified fixed.
