### ISSUE TITLE
[studio] Search API - Configuration per site for facet ranges

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#2872]
Per discussion, 
- Add configuration file per site so ranges can be defined per field.
- Keep global defaults in studio's yaml

**Comment by jvega190** [comment]
Ranges queries are not working anymore. Tested with this request body:
`filters: {
	width: {min: "32", max: "52"}
}
keywords: ""
limit: 20
offset: 0
sortBy: "internalName"
sortOrder: "asc"`

and got this error:
 `15:33:26.390 [http-nio-8080-exec-2] ERROR org.craftercms.studio.controller.rest.v2.ExceptionHandlers - API endpoint http://localhost:8080/studio/api/2/search/search.json?siteId=editorial2&nocache=Fri%20Mar%2001%202019%2015:33:26%20GMT-0600%20(Central%20Standard%20Time) failed with response: ApiResponse{code=1000, message='Internal system failure: Error executing search in ElasticSearch', remedialAction='Contact support', documentationUrl=''}
org.craftercms.studio.api.v1.exception.ServiceLayerException: Error executing search in ElasticSearch
    at org.craftercms.studio.impl.v2.service.search.internal.SearchServiceInternalImpl.search(SearchServiceInternalImpl.java:401) ~[classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.impl.v2.service.search.SearchServiceImpl.search(SearchServiceImpl.java:69) ~[classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.controller.rest.v2.SearchController.search(SearchController.java:59) ~[classes/:3.1.0-SNAPSHOT]
    at sun.reflect.GeneratedMethodAccessor341.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]`

Please let me know if you need more details about the error.

**Comment by jvega190** [comment]
Verified
