### ISSUE TITLE
[studio] DB Upgrade from v3.1.0.18 to v3.1.0.19 if site table contains deleted sites

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3067]
## Describe the bug
DB upgrade script from version 3.1.0.18 to 3.1.0.19 fails if site table has deleted sites.

## Logs
```
[INFO] 2019-04-10T15:31:03,625 [localhost-startStop-1] [operations.DbScriptUpgradeOperation] | Executing db script upgrade-3.1.0.18-to-3.1.0.19.sql 
Error executing: CALL migrate_audit()
.  Cause: java.sql.SQLSyntaxErrorException: (conn:10) Result consisted of more than one row
Query is : CALL migrate_audit()

[ERROR] 2019-04-10T15:31:03,671 [localhost-startStop-1] [operations.DbScriptUpgradeOperation] | Error executing db script 
org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: CALL migrate_audit()
.  Cause: java.sql.SQLSyntaxErrorException: (conn:10) Result consisted of more than one row
Query is : CALL migrate_audit()

    at org.apache.ibatis.jdbc.ScriptRunner.executeLineByLine(ScriptRunner.java:147) ~[mybatis-3.4.5.jar:3.4.5]
    at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:107) ~[mybatis-3.4.5.jar:3.4.5]
    at org.craftercms.studio.impl.v2.upgrade.operations.DbScriptUpgradeOperation.execute(DbScriptUpgradeOperation.java:122) [classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.impl.v2.upgrade.pipeline.DefaultUpgradePipelineImpl.execute(DefaultUpgradePipelineImpl.java:69) [classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.api.v2.upgrade.UpgradePipeline.execute(UpgradePipeline.java:41) [classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.upgradeDatabaseAndConfiguration(DefaultUpgradeManagerImpl.java:86) [classes/:3.1.0-SNAPSHOT]
    at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.init(DefaultUpgradeManagerImpl.java:189) [classes/:3.1.0-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$8.run(AbstractAutowireCapableBeanFactory.java:1750) [spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_191]
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1563
