### ISSUE TITLE
[engine] GraphQL fails when creating a new content-type

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3104]
## Describe the bug
When a new content-type is being created in Studio, engine will fail to load the GraphQL schema because the xml descriptor is not created until the user saves the changes.

## Logs
```
Caused by: java.lang.ClassCastException: org.craftercms.core.service.Item cannot be cast to org.craftercms.core.service.Tree
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.lambda$findContentTypes$1(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_152]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.findContentTypes(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.lambda$findContentTypes$1(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_152]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.findContentTypes(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.lambda$findContentTypes$1(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_152]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.findContentTypes(GraphQLFactoryImpl.java:117) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.buildSchema(GraphQLFactoryImpl.java:175) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.getInstance(GraphQLFactoryImpl.java:191) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.service.context.SiteContextManager.rebuildGraphQL(SiteContextManager.java:212) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.engine.controller.rest.SiteContextRestController.rebuildSchema(SiteContextRestController.java:102) ~[classes/:3.1.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	... 253 more
```

### Version
3.1.0

**Comment by avasquez614** [comment]
Verified
