### ISSUE TITLE
[engine] Error when creating a site from store BP IllegalArgumentException: [match] requires query value

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3165]
## Describe the bug
Error when creating a site from store BP `IllegalArgumentException: [match] requires query value`

## To Reproduce
1. Create a site from Store BP
2. Check catalina logs
3. Editing any page/component will thrown the same message in logs.

## Expected behavior
No errors when site is created.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
[WARN] 2019-05-23T08:28:21,847 [pool-4-thread-9] [store2] [execution.SimpleDataFetcherExceptionHandler] | Exception while fetching data (/products) : java.lang.IllegalArgumentException: [match] requires query value 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: [match] requires query value
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [?:1.8.0_212]
        at org.craftercms.engine.util.concurrent.SiteAwareRunnable.run(SiteAwareRunnable.java:41) [classes/:3.1.1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: [match] requires query value
        at org.elasticsearch.index.query.MatchQueryBuilder.<init>(MatchQueryBuilder.java:101) ~[elasticsearch-6.6.0.jar:6.6.0]
        at org.elasticsearch.index.query.QueryBuilders.matchQuery(QueryBuilders.java:59) ~[elasticsearch-6.6.0.jar:6.6.0]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.getFilterQuery(ContentTypeBasedDataFetcher.java:293) ~[classes/:3.1.1-SNAPSHOT]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.addFieldFilter(ContentTypeBasedDataFetcher.java:284) ~[classes/:3.1.1-SNAPSHOT]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.lambda$processSelection$5(ContentTypeBasedDataFetcher.java:237) ~[classes/:3.1.1-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.processSelection(ContentTypeBasedDataFetcher.java:237) ~[classes/:3.1.1-SNAPSHOT]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.lambda$processSelection$3(ContentTypeBasedDataFetcher.java:222) ~[classes/:3.1.1-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.processSelection(ContentTypeBasedDataFetcher.java:222) ~[classes/:3.1.1-SNAPSHOT]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.lambda$processSelection$3(ContentTypeBasedDataFetcher.java:222) ~[classes/:3.1.1-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.processSelection(ContentTypeBasedDataFetcher.java:222) ~[classes/:3.1.1-SNAPSHOT]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.lambda$get$2(ContentTypeBasedDataFetcher.java:174) ~[classes/:3.1.1-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at org.craftercms.engine.graphql.impl.fetchers.ContentTypeBasedDataFetcher.get(ContentTypeBasedDataFetcher.java:174) ~[classes/:3.1.1-SNAPSHOT]
        at graphql.schema.AsyncDataFetcher.lambda$get$0(AsyncDataFetcher.java:69) ~[graphql-java-12.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
        ... 4 more
```
### Version
3.1.1-SNAPSHOT

### OS
Linux

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Not studio issue. Stacktrace is coming from the engine graphql support.

**Comment by yacdaniel** [comment]
Verified fixed
