### ISSUE TITLE
[craftercms] delivery upgrade from 3.0.20 to 3.0.21 fails

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3193]
## Describe the bug
The upgrade of delivery from 3.0.20 to 3.0.21-SNAPSHOT is failing.

## To Reproduce
1. Download 3.0.20 delivery bundle, extract and start.
2. Upgrade Delivery following the guide https://docs.craftercms.org/en/3.0/system-administrators/upgrade/index.html#running-the-upgrade-script-from-your-current-install using the `start-upgrade` script(do not use the -f flag, is not necessary and should be removed from docs) for example:
`home/yhurtado/pre_release/delivery/crafter/temp/upgrade $ ./start-upgrade.sh -p /home/yhurtado/craftercms30/bundles/crafter-cms-delivery.tar.gz` and then go to the `temp/upgrade` dir and do the `upgrade.sh`
3. See error

## Expected behavior
No errors and delivery upgraded.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
Upgrading Crafter
========================================================================
Copying /home/yhurtado/pre_release/delivery/crafter/bin/apache-tomcat/shared to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/apache-tomcat/shared...
Copying /home/yhurtado/pre_release/delivery/crafter/bin/apache-tomcat/conf to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/apache-tomcat/conf...
Copying /home/yhurtado/pre_release/delivery/crafter/bin/crafter-deployer/config to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/crafter-deployer/config...
Copying /home/yhurtado/pre_release/delivery/crafter/bin/solr/server/solr/configsets/crafter_configs to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/solr/server/solr/configsets/crafter_configs...
Copying /home/yhurtado/pre_release/delivery/crafter/bin/crafter-setenv.sh to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/crafter-setenv.sh...
Copying /home/yhurtado/pre_release/delivery/crafter/bin/crafter-setenv.bat to /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin/crafter-setenv.bat...
Replacing /home/yhurtado/pre_release/delivery/crafter/bin with /home/yhurtado/pre_release/delivery/crafter/temp/upgrade/crafter/bin...
Upgrading /home/yhurtado/pre_release/delivery/crafter/bin/crafter-setenv.sh to 3.0.19 version...
Upgrading /home/yhurtado/pre_release/delivery/crafter/bin/crafter-setenv.bat to 3.0.19 version...
Upgrading /home/yhurtado/pre_release/delivery/crafter/bin/apache-tomcat/shared/classes/crafter/engine/extension/server-config.properties to 3.0.19 version...
Caught: java.nio.file.NoSuchFileException: /home/yhurtado/pre_release/delivery/crafter/bin/apache-tomcat/shared/classes/crafter/studio/extension/studio-config-override.yaml
java.nio.file.NoSuchFileException: /home/yhurtado/pre_release/delivery/crafter/bin/apache-tomcat/shared/classes/crafter/studio/extension/studio-config-override.yaml
        at java_nio_file_Files$readAllBytes.call(Unknown Source)
        at utils.NioUtils.fileToString(NioUtils.groovy:36)
        at utils.NioUtils$fileToString.callStatic(Unknown Source)
        at upgrade.hooks.UpgradeSharedConfTo3019.upgradeStudioConfigOverride(UpgradeSharedConfTo3019.groovy:49)
        at upgrade.hooks.UpgradeSharedConfTo3019$upgradeStudioConfigOverride$0.callCurrent(Unknown Source)
        at upgrade.hooks.UpgradeSharedConfTo3019.postUpgrade(UpgradeSharedConfTo3019.groovy:33)
        at upgrade.hooks.UpgradeHook$postUpgrade$0.call(Unknown Source)
        at upgrade.hooks.UpgradeHook$postUpgrade$0.call(Unknown Source)
        at upgrade.hooks.UpgradeHooks$_postUpgrade_closure2.doCall(UpgradeHooks.groovy:53)
        at upgrade.hooks.UpgradeHooks.postUpgrade(UpgradeHooks.groovy:52)
        at upgrade.hooks.UpgradeHooks$postUpgrade$0.call(Unknown Source)
        at upgrade-target.doUpgrade(upgrade-target.groovy:198)
        at upgrade-target$doUpgrade$3.callCurrent(Unknown Source)
        at upgrade-target.upgrade(upgrade-target.groovy:214)
        at upgrade-target$upgrade$0.callCurrent(Unknown Source)
        at upgrade-target.run(upgrade-target.groovy:247)

If the upgrade was completed successfully, please delete the upgrade temp/upgrade directory (rm -rf /home/yhurtado/pre_release/delivery/crafter/temp/upgrade)
```

### Version
3.0.20 upgraded to 3.0.21-SNAPSHOT-bea066

### OS
Linux

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
Verified fixed.
