### ISSUE TITLE
[studio] Clustering: create a site using siteid from a removed site causes sync errors

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3297]
## Describe the bug
Clustering: create a site using siteid from a removed site causes sync errors

## To Reproduce
1. Have a 2 authoring cluster.
2. Create a site  `testsite` from editorial BP in authoring node 1.
3. In authoring node 1 remove the site `testsite`, then create the site again using the same site id `testsite`
4. Check catalina from authoring node 1, wait for the logs of cluster.StudioNodeSyncPublishedTask`
5. Go to authoring node 2, edit some content. You will notice more errors in catalina log from authoring node 1.

## Expected behavior
No errors when a site is created using a siteid of a previously removed site, sync of sandbox publish should work successfully. 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Node 1 when site created
```
[INFO] 2019-07-17T20:25:42,156 [pool-3-thread-10] [] [context.SiteContext] | Starting GraphQL schema build for site 'tested01'                                                                                                                        
[INFO] 2019-07-17T20:25:42,203 [pool-3-thread-10] [] [context.SiteContext] | GraphQL schema build completed for site 'tested01'                              
[ERROR] 2019-07-17T20:25:42,280 [Studio_Clustering_Thread_Pool2] [cluster.StudioNodeSyncPublishedTask] | Error while fetching published repo for site tested01 from remote 10.130.137.161
[ERROR] 2019-07-17T20:25:42,280 [Studio_Clustering_Thread_Pool2] [cluster.StudioNodeSyncPublishedTask] | Invalid remote: 10.130.137.161                               
[ERROR] 2019-07-17T20:25:42,473 [Studio_Clustering_Thread_Pool2] [cluster.StudioNodeSyncPublishedTask] | Error while updating published repo for site tested01 from remote 10.130.137.161 environment live                                
[ERROR] 2019-07-17T20:25:42,473 [Studio_Clustering_Thread_Pool2] [cluster.StudioNodeSyncPublishedTask] | Invalid remote: 10.130.137.161                      
[WARN] 2019-07-17T20:25:53,863 [Studio_Publisher_Thread_Pool2] [lib.Repository] | close() called when useCnt is already zero for Repository[/home/crafter/craftercms/crafter-authoring/data/repos/sites/tested01/sandbox/.git]
```
Wthen there is a edit from authoring node 2, logs in node 1 are:
```
[ERROR] 2019-07-17T20:29:20,304 [Studio_Clustering_Thread_Pool9] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01              
[ERROR] 2019-07-17T20:29:22,303 [Studio_Clustering_Thread_Pool10] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01 
[ERROR] 2019-07-17T20:29:24,300 [Studio_Clustering_Thread_Pool11] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01                                                          
[ERROR] 2019-07-17T20:29:26,302 [Studio_Clustering_Thread_Pool7] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01          
[ERROR] 2019-07-17T20:29:28,297 [Studio_Clustering_Thread_Pool6] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01  
[ERROR] 2019-07-17T20:29:30,301 [Studio_Clustering_Thread_Pool1] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01                                                                                      
[ERROR] 2019-07-17T20:29:32,300 [Studio_Clustering_Thread_Pool4] [cluster.StudioNodeSyncSandboxTask] | Error while syncing cluster node content for site tested01                                                                                      
[ERROR] 2019-07-17T20:29:33,862 [Studio_Publisher_Thread_Pool4] [git.GitContentRepository] | Error getting operations for site tested01 from commit ID: 164de571adf9b000c783ba0ea91d8d06185d0293 to commit ID: ae3abc0e62df801897d1c3521e534398e57e7635
org.eclipse.jgit.errors.MissingObjectException: Missing commit 164de571adf9b000c783ba0ea91d8d06185d0293                                                            
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:170) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]
        at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:933) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]                                    
        at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:158) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]                       
        at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:302) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]                      
        at org.eclipse.jgit.revwalk.RevWalk.markUninteresting(RevWalk.java:372) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]
        at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:353) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]
        at org.eclipse.jgit.api.LogCommand.not(LogCommand.java:233) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]
        at org.eclipse.jgit.api.LogCommand.addRange(LogCommand.java:266) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar:4.11.0.201803080745-r]
        at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.getOperations(GitContentRepository.java:1358) [classes/:3.1.1-SNAPSHOT]
        at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1221) [classes/:3.1.1-SNAPSHOT]
        at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1211) [classes/:3.1.1-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor402.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at com.sun.proxy.$Proxy132.syncDatabaseWithRepo(Unknown Source) [?:?]
        at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.syncRepository(PublisherTask.java:188) [classes/:3.1.1-SNAPSHOT]
        at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.run(PublisherTask.java:115) [classes/:3.1.1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
### Version
Studio Version Number: 3.1.1-SNAPSHOT-f2e773
Build Number: f2e7738436efffcb2362118510d1c54ba10e7394
Build Date/Time: 07-17-2019 13:01:33 -0600

### OS
Linux

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1726

**Comment by yacdaniel** [comment]
Verified fixed.
