### ISSUE TITLE
[craftercms] MariaDB4j is not being copied on deploy when using the start-upgrade script

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3408]
## Describe the bug
MariaDB4j is not being copied on deploy when using the start-upgrade script

## To Reproduce
1. From the craftercms develop branch, create a bundle (I did not delete the authoring folder)
2. From an old bundle install (say 3.0.18), go to the `bin/upgrade` folder
3. Run the `start-upgrade.sh` script, then follow the instruction to next run the `upgrade.sh` script
```
➜  upgrade ./start-upgrade.sh -p /Users/vita/temp/test5/craftercms/bundles/crafter-cms-authoring-3.1.1-SNAPSHOT.tar.gz
.
.
.
➜  upgrade cd ../../temp
➜  temp cd upgrade
➜  upgrade ./upgrade.sh

```
4. After running the `upgrade.sh` script, you will be asked to run the `post-upgrade.sh` script.  Run the script and notice the error
```
➜  upgrade /Users/vita.alhambra/Downloads/crafTER-3-0-18-2/bin/upgrade/post-upgrade.sh
========================================================================
Post-upgrade 3.0.x -> 3.1.1
========================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Upgrading embedded DB
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------
Starting upgrade of embedded database /Users/vita/Downloads/crafter-3-0-18-2/data/db
------------------------------------------------------------------------
------------------------------------------------------------------------
Upgrading embedded DB
------------------------------------------------------------------------
./crafter.sh: line 1113: /Users/vita/Downloads/crafter-3-0-18-2/bin/dbms/bin/mysql_upgrade: No such file or directory
Unable to continue, an error occurred or the script was forcefully stopped
Caught: upgrade.exceptions.UpgradeException: Unable to upgrade the embedded DB
upgrade.exceptions.UpgradeException: Unable to upgrade the embedded DB
	at upgrade.hooks.UpgradeEmbeddedDbHook$_execute_closure1.doCall(UpgradeEmbeddedDbHook.groovy:54)
	at upgrade.hooks.UpgradeEmbeddedDbHook.execute(UpgradeEmbeddedDbHook.groovy:34)
	at upgrade.hooks.PostUpgradeHook$execute.call(Unknown Source)
	at upgrade.hooks.PostUpgradeHooks$_execute_closure1.doCall(PostUpgradeHooks.groovy:75)
	at upgrade.hooks.PostUpgradeHooks.execute(PostUpgradeHooks.groovy:74)
	at upgrade.hooks.PostUpgradeHooks$execute.call(Unknown Source)
	at upgrade.post-upgrade.postUpgrade(post-upgrade.groovy:72)
	at upgrade.post-upgrade$postUpgrade$0.callCurrent(Unknown Source)
	at upgrade.post-upgrade.run(post-upgrade.groovy:95)
Caused by: java.lang.RuntimeException: Process '[./crafter.sh, upgradedb]' exited with non-successful value 1
	at utils.ScriptUtils.executeCommand(ScriptUtils.groovy:80)
	at utils.ScriptUtils.executeCommand(ScriptUtils.groovy:56)
	at utils.ScriptUtils$executeCommand$0.callStatic(Unknown Source)
	at upgrade.hooks.UpgradeEmbeddedDbHook$_execute_closure1.doCall(UpgradeEmbeddedDbHook.groovy:52)
	... 8 more
```

## Expected behavior
There should be no errors when running the `post-upgrade.sh` script

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
OS X

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Verified issue is not in latest develop anymore.

Studio Version Number: 3.1.4-SNAPSHOT-d0710c
Build Number: d0710ca042dbe872a5caa0b8f219d09bffe4e308
Build Date/Time: 10-22-2019 09:20:48 -0400
