### ISSUE TITLE
[craftermcs] upgrade of delivery from 3.0.18 3.1.1-SNAPSHOT fails

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3410]
## Describe the bug
Upgrade of delivery from 3.0.18 to 3.1.1-SNAPSHOT does not complete successfully. 

## To Reproduce
1. Using crafter 3.0.18 create a site in authoring and `init-site.sh` to delivery
2. Upgrade delivery using `start-upgrade` script
3. See error when `post-upgrade.sh` is run.

## Expected behavior
Upgrade of delivery completed successfully.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
Upgrade completed
========================================================================
!!! Please read the release notes and make any necessary manual changes, then run the post upgrade script: /home/tmp/delivery/crafter/bin/upgrade/post-upgrade.sh !!!

If the upgrade was completed successfully, please delete the upgrade temp directory (rm -rf /home/tmp/delivery/crafter/temp/upgrade)
➜  upgrade /home/tmp/delivery/crafter/bin/upgrade/post-upgrade.sh
========================================================================
Post-upgrade 3.0.x -> 3.1.1
========================================================================
Caught: java.lang.NullPointerException
java.lang.NullPointerException
        at java_nio_file_Paths$get.call(Unknown Source)
        at utils.EnvironmentUtils.getMariaDbDataFolder(EnvironmentUtils.groovy:88)
        at utils.EnvironmentUtils$getMariaDbDataFolder$3.callStatic(Unknown Source)
        at upgrade.hooks.UpgradeEmbeddedDbHook.execute(UpgradeEmbeddedDbHook.groovy:32)
        at upgrade.hooks.PostUpgradeHook$execute.call(Unknown Source)
        at upgrade.hooks.PostUpgradeHooks$_execute_closure1.doCall(PostUpgradeHooks.groovy:75)
        at upgrade.hooks.PostUpgradeHooks.execute(PostUpgradeHooks.groovy:74)
        at upgrade.hooks.PostUpgradeHooks$execute.call(Unknown Source)
        at upgrade.post-upgrade.postUpgrade(post-upgrade.groovy:72)
        at upgrade.post-upgrade$postUpgrade$0.callCurrent(Unknown Source)
        at upgrade.post-upgrade.run(post-upgrade.groovy:95)
```

### Version
3.1.1-SNAPSHOT

### OS
Linux

### Browser
N/A

## Additional context
N/A

**Comment by yacdaniel** [comment]
Verified fixed.
