### ISSUE TITLE
[studio] migrate the WebDAV API to API 2

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3420]
We need to migrate the webdav API for assets upload and browse (including images, videos..)

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 should we just expose the services in API2 or also update it to use the remote-assets API?

**Comment by avasquez614** [comment]
@jdrossl after the API design and implementation is done, assign to @alhambrav to document that in order to avoid proxying the WebDav `/remote-assets` in Delivery, the Delivery Deployer target should be configured to have a find and replace processor that changes the `/remote-assets` URL to an actual Apache static asset delivery URL.

**Comment by jvega190** [comment]
@jdrossl both list and upload APIs work. But when trying to preview I get this error

```
[ERROR] 2019-09-18T14:59:42,390 [http-nio-8080-exec-3] [editorial] [impl.DefaultExceptionHandler] | GET http://127.0.0.1:8080/remote-assets/webdav/webdav-default//tengoImpresora.jpg failed 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[servlet-api.jar:?]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.craftercms.commons.web.AddResponseHeaderFilter.doFilterInternal(AddResponseHeaderFilter.java:65) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.craftercms.engine.scripting.impl.ScriptFilter.doFilter(ScriptFilter.java:106) ~[classes/:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.craftercms.security.servlet.filters.RequestSecurityFilter$1.processRequest(RequestSecurityFilter.java:193) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.UrlAccessRestrictionCheckingProcessor.processRequest(UrlAccessRestrictionCheckingProcessor.java:148) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.SecurityExceptionProcessor.processRequest(SecurityExceptionProcessor.java:82) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.SavedRequestAwareProcessor.processRequest(SavedRequestAwareProcessor.java:70) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.AuthenticationHeadersLoginProcessor.processRequest(AuthenticationHeadersLoginProcessor.java:145) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.engine.security.ConfigAwareAuthenticationHeadersLoginProcessor.processRequest(ConfigAwareAuthenticationHeadersLoginProcessor.java:103) ~[classes/:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RememberMeAutoLoginProcessor.processRequest(RememberMeAutoLoginProcessor.java:55) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.LogoutProcessor.processRequest(LogoutProcessor.java:104) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.LoginProcessor.processRequest(LoginProcessor.java:168) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.ReturnCurrentAuthenticationProcessor.processRequest(ReturnCurrentAuthenticationProcessor.java:76) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.CurrentAuthenticationResolvingProcessor.processRequest(CurrentAuthenticationResolvingProcessor.java:86) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.engine.security.PreviewCurrentAuthenticationResolvingProcessor.processRequest(PreviewCurrentAuthenticationResolvingProcessor.java:83) ~[classes/:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.AddSecurityCookiesProcessor.processRequest(AddSecurityCookiesProcessor.java:74) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.processors.impl.RequestSecurityProcessorChainImpl.processRequest(RequestSecurityProcessorChainImpl.java:59) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.servlet.filters.RequestSecurityFilter.doFilterInternal(RequestSecurityFilter.java:139) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.security.servlet.filters.RequestSecurityFilter.doFilter(RequestSecurityFilter.java:110) ~[crafter-security-provider-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.craftercms.engine.url.rewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:79) ~[classes/:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
    at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:56) [classes/:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
    at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:57) [classes/:3.1.4-SNAPSHOT]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
    at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:79) [crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
    at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.11.2.jar:2.11.2]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.24]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.24]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [catalina.jar:8.5.24]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.24]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.24]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.24]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.24]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.24]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-coyote.jar:8.5.24]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.24]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-coyote.jar:8.5.24]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-coyote.jar:8.5.24]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.24]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.24]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.RuntimeException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
    at com.github.sardine.util.SardineUtil.unmarshal(SardineUtil.java:190) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:70) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:52) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:35) ~[sardine-5.9.jar:5.9]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[httpclient-4.5.2.jar:4.5.2]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.2.jar:4.5.2]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1050) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1019) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:460) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:409) ~[sardine-5.9.jar:5.9]
    at org.craftercms.commons.spring.resources.WebDavResource.getResource(WebDavResource.java:144) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.commons.spring.resources.WebDavResource.lastModified(WebDavResource.java:110) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:449) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    ... 92 more
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
    at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230) ~[?:1.8.0_201]
    at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191) ~[?:1.8.0_201]
    at com.github.sardine.util.SardineUtil.unmarshal(SardineUtil.java:150) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:70) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:52) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:35) ~[sardine-5.9.jar:5.9]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[httpclient-4.5.2.jar:4.5.2]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.2.jar:4.5.2]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1050) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1019) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:460) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:409) ~[sardine-5.9.jar:5.9]
    at org.craftercms.commons.spring.resources.WebDavResource.getResource(WebDavResource.java:144) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.commons.spring.resources.WebDavResource.lastModified(WebDavResource.java:110) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:449) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    ... 92 more
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291) ~[catalina.jar:8.5.24]
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[catalina.jar:8.5.24]
    at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82) ~[?:1.8.0_201]
    at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228) ~[?:1.8.0_201]
    at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191) ~[?:1.8.0_201]
    at com.github.sardine.util.SardineUtil.unmarshal(SardineUtil.java:150) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.getMultistatus(MultiStatusResponseHandler.java:70) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:52) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:35) ~[sardine-5.9.jar:5.9]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[httpclient-4.5.2.jar:4.5.2]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.2.jar:4.5.2]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1050) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1019) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:460) ~[sardine-5.9.jar:5.9]
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:409) ~[sardine-5.9.jar:5.9]
    at org.craftercms.commons.spring.resources.WebDavResource.getResource(WebDavResource.java:144) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.craftercms.commons.spring.resources.WebDavResource.lastModified(WebDavResource.java:110) ~[crafter-commons-utilities-3.1.4-SNAPSHOT.jar:3.1.4-SNAPSHOT]
    at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:449) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
    ... 92 more

```

**Comment by jdrossl** [comment]
I was not able to replicate this error, @avasquez614 any idea what could cause it?

**Comment by jdrossl** [comment]
@yacdaniel please help us test on linux with both oracle's & open jdk

**Comment by yacdaniel** [comment]
Tested with Oracle JDK and OpenJDK, WebDAV works as expected.
