### ISSUE TITLE
[search] Empty files cause an error during indexing

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3520]
## Describe the bug
When a empty file is created in the repo the deployer tries to index it causing an error

## To Reproduce
Create an empty file, it can be a groovy script

## Expected behavior
Empty files should be ignored by all search indexing processors

## Logs
```
org.craftercms.search.exception.SearchException: [craftersoftwarecom-authoring] Error indexing binary document /scripts/pages/resources.groovy
at org.craftercms.search.elasticsearch.batch.ElasticsearchIndexingUtils.doUpdateBinary(ElasticsearchIndexingUtils.java:85)
at org.craftercms.search.elasticsearch.batch.ElasticsearchBinaryFileWithMetadataBatchIndexer.doUpdateContent(ElasticsearchBinaryFileWithMetadataBatchIndexer.java:105)
at org.craftercms.search.elasticsearch.batch.ElasticsearchBinaryFileWithMetadataBatchIndexer.doUpdateContent(ElasticsearchBinaryFileWithMetadataBatchIndexer.java:122)
at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.updateBinary(AbstractBinaryFileWithMetadataBatchIndexer.java:418)
at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.doUpdates(AbstractBinaryFileWithMetadataBatchIndexer.java:226)
at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.updateIndex(AbstractBinaryFileWithMetadataBatchIndexer.java:162)
at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.doMainProcess(AbstractSearchIndexingProcessor.java:276)
at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.doExecute(AbstractMainDeploymentProcessor.java:39)
at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:142)
at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:82)
at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:68)
at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:397)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Version
3.1.4-SNAPSHOT

**Comment by jdrossl** [comment]
@yacdaniel please help us to verify this

**Comment by yacdaniel** [comment]
Verified fixed.
