### ISSUE TITLE
[studio] Log an error if credentials are empty for a selected authentication mechanism in clustering

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3542]
**Is your feature request related to a problem? Please describe.**
In Studio, if the credentials are empty for a selected type authentication in a cluster an NPE is thrown.

**Describe the solution you'd like**
Studio should detect a missing key/token/password value and throw an error that indicates the issue.

Current error (hard to triage/interpret)
```
Exception in thread "Studio_Clustering_Thread_Pool12" java.lang.NullPointerException
    at org.craftercms.commons.crypto.impl.AesTextEncryptor.decrypt(AesTextEncryptor.java:58)
    at org.craftercms.studio.impl.v2.service.cluster.StudioNodeSyncBaseTask.configurePrivateKeyAuthentication(StudioNodeSyncBaseTask.java:425)
```

When the NPE above is thrown, you will also find that the "password" value in Cluster table columns will be null as well.

**Comment by russdanner** [comment]
Confirmed
