### ISSUE TITLE
[docs] Error performing find and replace on file /site/components/.keep

### ISSUE THREAD

**Issue by bitsofinfo** [craftercms/craftercms#3729]
## Describe the bug
Running the k8s example and doing the "serverless" setup with it. After creating the new target in the authoring pod's deployer container I start to see this in the deployer logs

```
2019-12-13 16:07:03.865 ERROR 26 --- [deployment-8] l.processors.AbstractDeploymentProcessor : Processor 'findAndReplaceProcessor' for target 'bitsofinfo-aws' failed
org.craftercms.deployer.api.exceptions.DeployerException: Error performing find and replace on file /site/components/.keep; nested exception is java.util.regex.PatternSyntaxException: Unclosed group near index 32
/static-assets(/([^&quot;&lt;]+)
	at org.craftercms.deployer.impl.processors.FindAndReplaceProcessor.doMainProcess(FindAndReplaceProcessor.java:113)
	at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.doExecute(AbstractMainDeploymentProcessor.java:39)
	at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:142)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:82)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:68)
	at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 32
/static-assets(/([^&quot;&lt;]+)
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.accept(Pattern.java:1815)
	at java.util.regex.Pattern.group0(Pattern.java:2910)
	at java.util.regex.Pattern.sequence(Pattern.java:2053)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at org.craftercms.deployer.impl.processors.FindAndReplaceProcessor.doMainProcess(FindAndReplaceProcessor.java:104)
	... 10 more
```

## To Reproduce

Do the k8s setup, create a site, then follow https://docs.craftercms.org/en/3.1/system-administrators/activities/delivery/setup-serverless-site.html?highlight=serverless

Error is happening after step 3

**Comment by sumerjabri** [comment]
@avasquez614 per our convo, this might be related to updating the docs task with the latest serverless config.

**Comment by sumerjabri** [comment]
@alhambrav please mark this article as deprecated: https://docs.craftercms.org/en/3.1/system-administrators/activities/delivery/setup-serverless-site.html and remove it from the navigation. Please add a link at the top to the new documentation: https://docs.craftercms.org/en/3.1/system-administrators/activities/delivery/setup-serverless-delivery.html and make sure the new article is in the navigation.

Please plan on removing the old article in the near future.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/907

**Comment by sumerjabri** [comment]
Verified.
