### ISSUE TITLE
[studio] Error Site context is not valid anymore when creating first site in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3748]
## Describe the bug
On a fresh install or when you delete the `data` folder,  there is an error that the site context is not valid anymore when creating the very first site in Studio

```
[ERROR] 2020-01-06T11:11:16,696 [http-nio-8080-exec-6] [] [context.SiteContextManager] | Site context SiteContext{siteName='newsite', context=FileSystemContext{id='977d6174f06786497c2d88f76bf315b0', rootFolderPath='file:/Users/vita/temp/test3/craftercms/crafter-authoring/data/repos/sites/newsite/sandbox/'}, fallback=false, staticAssetsPath='/static-assets', templatesPath='/', restScriptsPath='/scripts/rest', controllerScriptsPath='/scripts/controllers'} is not valid anymore
```

## To Reproduce
1. Clone craftercms or, delete the `crafter-authoring/data` folder
2. Start Studio
3. Create a site using the website editorial bp
4. Watch the logs as the site is being created and notice after your site is created, thesite preview is not available and instead you get a `Could not resolve site for the current request.`

![Screen Shot 2020-01-06 at 11 51 09 AM](https://user-images.githubusercontent.com/25483966/71833460-f30bc680-307a-11ea-8c83-0f7dbdde53d7.png)

## Expected behavior
There should be no errors when creating the first site in Studio

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
[ERROR] 2020-01-06T11:11:16,696 [http-nio-8080-exec-6] [] [context.SiteContextManager] | Site context SiteContext{siteName='newsite', context=FileSystemContext{id='977d6174f06786497c2d88f76bf315b0', rootFolderPath='file:/Users/vita/temp/test3/craftercms/crafter-authoring/data/repos/sites/newsite/sandbox/'}, fallback=false, staticAssetsPath='/static-assets', templatesPath='/', restScriptsPath='/scripts/rest', controllerScriptsPath='/scripts/controllers'} is not valid anymore
[INFO] 2020-01-06T11:11:16,696 [http-nio-8080-exec-6] [] [context.SiteContextManager] | ==================================================
[INFO] 2020-01-06T11:11:16,696 [http-nio-8080-exec-6] [] [context.SiteContextManager] | <Destroying site context: newsite>
[INFO] 2020-01-06T11:11:16,697 [http-nio-8080-exec-6] [] [context.SiteContextManager] | ==================================================
[INFO] 2020-01-06T11:11:16,697 [http-nio-8080-exec-6] [] [support.GenericApplicationContext] | Closing org.springframework.context.support.GenericApplicationContext@441fa52e: startup date [Mon Jan 06 11:11:15 EST 2020]; parent: Root WebApplicationContext
[INFO] 2020-01-06T11:11:16,698 [http-nio-8080-exec-6] [] [context.SiteContextManager] | Site context destroyed: SiteContext{siteName='newsite', context=FileSystemContext{id='977d6174f06786497c2d88f76bf315b0', rootFolderPath='file:/Users/vita/temp/test3/craftercms/crafter-authoring/data/repos/sites/newsite/sandbox/'}, fallback=false, staticAssetsPath='/static-assets', templatesPath='/', restScriptsPath='/scripts/rest', controllerScriptsPath='/scripts/controllers'}
[INFO] 2020-01-06T11:11:16,698 [http-nio-8080-exec-6] [] [context.SiteContextManager] | ==================================================
[INFO] 2020-01-06T11:11:16,699 [http-nio-8080-exec-6] [] [context.SiteContextManager] | </Destroying site context: newsite>
[INFO] 2020-01-06T11:11:16,699 [http-nio-8080-exec-6] [] [context.SiteContextManager] | ==================================================
[ERROR] 2020-01-06T11:11:16,699 [http-nio-8080-exec-6] [] [filter.SiteContextResolvingFilter] | Error while resolving site context for current request
java.lang.IllegalStateException: Unable to resolve context for site name 'newsite'
	at org.craftercms.engine.service.context.SiteContextResolverImpl.getContext(SiteContextResolverImpl.java:81) ~[classes/:3.1.5-SNAPSHOT]
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.getContext(SiteContextResolvingFilter.java:95) [classes/:3.1.5-SNAPSHOT]
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:79) [classes/:3.1.5-SNAPSHOT]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:79) [crafter-commons-utilities-3.1.5-SNAPSHOT.jar:3.1.5-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.11.2.jar:2.11.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.24]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-coyote.jar:8.5.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-coyote.jar:8.5.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-coyote.jar:8.5.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

### Version
Studio Version Number: 3.1.5-SNAPSHOT-189958
Build Number: 189958a33a56a46094df29c2c9675f709331ceba
Build Date/Time: 01-06-2020 11:02:57 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
The error only appears the first time you create a site.  Also, after getting the error `Could not resolve site for the current request.` in the UI, if you click on `Main Menu` -> `Sites` then click on your site, the site is now available for preview.

**Comment by dejan-brkic** [comment]
Can not reproduce it:
```
Studio Version Number: 3.1.5-SNAPSHOT-be2203

Build Number: be2203016285e1f305af2cfd4cc320fea974e934

Build Date/Time: 01-20-2020 22:05:28 +0100```

**Comment by alhambrav** [comment]
I am still getting the error `Could not resolve site for the current request`

```
[ERROR] 2020-01-21T03:24:43,517 [http-nio-8080-exec-10] [] [filter.SiteContextResolvingFilter] | Error while resolving site context for current request
java.lang.IllegalStateException: Unable to resolve context for site name 'foobar'
```

Studio Version:
```
Studio Version Number: 3.1.5-SNAPSHOT-be2203
Build Number: be2203016285e1f305af2cfd4cc320fea974e934
Build Date/Time: 01-21-2020 03:02:07 -0500
```

Here are updated steps on how to reproduce:
1. Clone crafter `git clone https://github.com/craftercms/craftercms.git -b develop` 
2. Build and deploy `./gradlew init build deploy`
3. Start crafter. `./gradlew start`
4. Create a site using the website editorial bp.  Notice the message displayed when the site preview is shown.
<img width="1261" alt="Screen Shot 2020-01-21 at 3 34 00 AM" src="https://user-images.githubusercontent.com/25483966/72787942-e355bb80-3bfe-11ea-87ae-7e6cfa413a44.png">

5. Look at the catalina log and notice the error message displayed.
Below is the logs for when the site is created and the error:
https://gist.github.com/alhambrav/3965283299a31d8dd4aef4962f58f50a

Here's a short clip:
https://www.loom.com/share/d4a3a67fa31e451cba923a8dd2e88f54

Another way to reproduce the error is:
1. Stop crafter `./gradlew stop`
2. Delete the data folder `rm -rf crafter-authoring/data`
3. Restart Studio `./gradlew start`
4. Create a site using website editorial.

As mentioned in the ticket, the error only appears after a fresh install or after deleting the data folder.

**Comment by dejan-brkic** [comment]
Still can not reproduce the issue. By examining stacktrace from attached log, it seems engine issue. It is possible some kind of race condition or lazy loading because it appears only when creating first site. In video i have noticed that after returning to site list and again to preview, there is no issue. That makes me more positive that it is race condition/slow environment.

**Comment by alhambrav** [comment]
Verified fixed.
