### ISSUE TITLE
[commercetools-blueprint] Unable to resolve class org.craftercms.engine.security.PreAuthenticatedProfile and client shutdown improvements

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3781]
## Describe the bug
Site created from commercetools blueprint fails to build GraphQL schema

Also when the site is deleted Studio keeps trying to connect to commercetools, client should be forced to shutdown.

## To Reproduce
1. Create a site from the commertools blueprint marketplace.
4. See an error in `tomcat/catalina.out`

## Expected behavior
No errors, site renders as expected.

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/73383847-b9039e00-428f-11ea-80c6-858fa702afdf.png)

## Logs
https://gist.github.com/yacdaniel/2d89f46ea2f6b4d349b69a231550b452
 
After I deleted the site because of failing to build the GraphQL schema there is a log entry showing over and over
```
[WARN] 2020-01-29T11:52:02,094 [AsyncHttpClient-2-1] [] [nio.NioEventLoop] | Unexpected exception in the selector loop.
java.lang.NoClassDefFoundError: io/netty/channel/AdaptiveRecvByteBufAllocator$HandleImpl
        at io.netty.channel.AdaptiveRecvByteBufAllocator.newHandle(AdaptiveRecvByteBufAllocator.java:180) ~[netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:107) ~[netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [netty-transport-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-common-4.0.54.Final.jar:4.0.54.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.0.54.Final.jar:4.0.54.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

### Version
`3.1.5-SNAPSHOT`

### OS
Mac OS

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
Verified fixed, when the site is removed there is an error which may don't look good for the user, ticket created to handle that case: https://github.com/craftercms/craftercms/issues/3805
