### ISSUE TITLE
[commercetools-blueprint] Gracefully destroy site context when site removed

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3805]
## Describe the bug
When a site from commercetools marketplace is removed the site context is destroyed throws some errors in the log, site context and site from Studio is successfully removed but the logs entries don't look good and may scare/confuse a user a bit 

## To Reproduce
1. Create a site from commercetools marketplace
2. Remove the site
3. See tomcat catalina.out log.

## Expected behavior
Log when the site context is destroyed should handle the exception? Improve the way the site context is destroyed? What else can we do? 

## Screenshots
N/A

## Logs
```
[INFO] 2020-02-05T07:55:17,731 [Studio_Publisher_Thread_Pool10] [site.SiteServiceImpl] | Last commit ID for site: ecommerce is 74f982b29eb217006f36e0dfd99c0235a8e84964 

[INFO] 2020-02-05T07:55:34,318 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | ================================================== 

[INFO] 2020-02-05T07:55:34,319 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | <Destroying site context: ecommerce> 

[INFO] 2020-02-05T07:55:34,319 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | ================================================== 

[INFO] 2020-02-05T07:55:34,319 [http-nio-8080-exec-9] [ecommerce] [support.GenericApplicationContext] [/scripts/filters/currency.groovy] | Closing org.springframework.context.support.GenericApplicationContext@1afd2261: startup date [Wed Feb 05 07:54:37 CST 2020]; parent: Root WebApplicationContext 

[INFO] 2020-02-05T07:55:34,326 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | Site context destroyed: SiteContext{siteName='ecommerce', context=FileSystemContext{id='cdb74d94ef00b87fa6c48d8058bfbe93', rootFolderPath='file:/home/yacdaniel/work/craftercmsent/crafter-authoring/data/repos/sites/ecommerce/sandbox/'}, fallback=false, staticAssetsPath='/static-assets', templatesPath='/', restScriptsPath='/scripts/rest', controllerScriptsPath='/scripts/controllers'} 

[INFO] 2020-02-05T07:55:34,327 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | ================================================== 

[INFO] 2020-02-05T07:55:34,327 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | </Destroying site context: ecommerce> 

[INFO] 2020-02-05T07:55:34,327 [http-nio-8080-exec-9] [ecommerce] [context.SiteContextManager] [/scripts/filters/currency.groovy] | ================================================== 

Exception in thread "AsyncHttpClient-2-1" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

Exception in thread "AsyncHttpClient-2-2"   at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.DefaultPromise$1

    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)

    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:702)

    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:812)

    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:800)

    ... 5 more

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

Exception in thread "AsyncHttpClient-2-29" Exception in thread "AsyncHttpClient-2-32" Exception in thread "AsyncHttpClient-2-8" Exception in thread "AsyncHttpClient-2-27" Exception in thread "AsyncHttpClient-2-9" Exception in thread "AsyncHttpClient-2-5" Exception in thread "AsyncHttpClient-2-20" Exception in thread "AsyncHttpClient-2-11" Exception in thread "AsyncHttpClient-2-4" Exception in thread "AsyncHttpClient-2-10" Exception in thread "AsyncHttpClient-2-28" Exception in thread "AsyncHttpClient-2-26" Exception in thread "AsyncHttpClient-2-7" Exception in thread "AsyncHttpClient-2-3" Exception in thread "AsyncHttpClient-2-16" Exception in thread "AsyncHttpClient-2-31" Exception in thread "AsyncHttpClient-2-30" Exception in thread "AsyncHttpClient-2-24" Exception in thread "AsyncHttpClient-2-25" Exception in thread "AsyncHttpClient-2-12" Exception in thread "AsyncHttpClient-2-23" Exception in thread "AsyncHttpClient-2-19" Exception in thread "AsyncHttpClient-2-17" Exception in thread "AsyncHttpClient-2-15" Exception in thread "AsyncHttpClient-2-13" Exception in thread "AsyncHttpClient-2-21" Exception in thread "AsyncHttpClient-2-22" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

Exception in thread "AsyncHttpClient-2-14" Exception in thread "AsyncHttpClient-2-6" Exception in thread "AsyncHttpClient-2-18"     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)

java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)

    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:170)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)
```

### Version
`3.1.5-SNAPSHOT`

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by yacdaniel** [comment]
Verified fixed in blueprint version `1.1.8`
