### ISSUE TITLE
[engine] GraphQL fails using groovy objects

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3860]
When using a custom GraphQL schema, if a data fetcher returns a goovy object it will fail after a site context rebuild is done. Example:

`/scripts/classes/org/craftercms/sites/editorial/Model.groovy`
```
package org.craftercms.sites.editorial

class Model {
	
	def value
	
}

```

`scripts/graphql/init.groovy`
```
import static graphql.Scalars.GraphQLString
import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition
import static graphql.schema.GraphQLObjectType.newObject

import org.craftercms.sites.editorial.Model

schema.field(newFieldDefinition()
  .name('test')
  .description('test field')
  .type(newObject() // inline type definition
    .name('Test')
    .description('test service')
    .field(newFieldDefinition()
      .name('value')
      .description('gets a value')
      .type(newObject()
        .name('Model')
        .field(newFieldDefinition()
          .name('value')
          .type(GraphQLString)
        )
      )
    )
  )
)

schema.fetcher('Test', 'value', { env ->
  def model = new Model()
  model.value = "42"
  return model
})

```

After performing a site context rebuild the following error is thrown:

```
[WARN] 2020-03-03T09:45:43,583 [http-nio-8080-exec-10] [ed] [execution.SimpleDataFetcherExceptionHandler] | Exception while fetching data (/test/value/value) : object is not an instance of declaring class 
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at graphql.schema.PropertyDataFetcher.getPropertyViaGetterUsingPrefix(PropertyDataFetcher.java:185) ~[graphql-java-12.0.jar:?]
	at graphql.schema.PropertyDataFetcher.getPropertyViaGetterMethod(PropertyDataFetcher.java:174) ~[graphql-java-12.0.jar:?]
	at graphql.schema.PropertyDataFetcher.getPropertyViaGetter(PropertyDataFetcher.java:151) ~[graphql-java-12.0.jar:?]
	at graphql.schema.PropertyDataFetcher.get(PropertyDataFetcher.java:146) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:197) ~[graphql-java-12.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:638) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:425) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:375) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:199) ~[graphql-java-12.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_152]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_152]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_152]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) ~[graphql-java-12.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:638) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:425) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:375) ~[graphql-java-12.0.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:199) ~[graphql-java-12.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) [?:1.8.0_152]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) [?:1.8.0_152]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) [?:1.8.0_152]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) [graphql-java-12.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) [graphql-java-12.0.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:160) [graphql-java-12.0.jar:?]
	at graphql.execution.Execution.execute(Execution.java:101) [graphql-java-12.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:591) [graphql-java-12.0.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521) [graphql-java-12.0.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:495) [graphql-java-12.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:426) [graphql-java-12.0.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:396) [graphql-java-12.0.jar:?]
	at org.craftercms.engine.controller.rest.SiteGraphQLController.handleRequest(SiteGraphQLController.java:105) [classes/:3.1.6-SNAPSHOT]
	at org.craftercms.engine.controller.rest.SiteGraphQLController.query(SiteGraphQLController.java:80) [classes/:3.1.6-SNAPSHOT]
```

**Comment by jdrossl** [comment]
@russdanner please help validate

**Comment by russdanner** [comment]
Confirmed
