### ISSUE TITLE
[search] Review default mapping settings for Elasticsearch indexes

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3929]
We are currently using the default settings for mapping in Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/mapping.html#mapping-limit-settings

We need to consider increasing some of the limits to prevent issues in larger sites

**Comment by sumerjabri** [comment]
Must also consider: Limit of mapping depth [20]

**Comment by avasquez614** [comment]
An issue related to this came up when upgrading deployer target from 3.1.6 to 3.1.9:

```
"cause":{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [mysite-authoring_v2] has been exceeded"},"status":400}]}];
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2030)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1775)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694)
	at org.elasticsearch.client.RestHighLevelClient.reindex(RestHighLevelClient.java:514)
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.doReindex(ElasticsearchAdminServiceImpl.java:234)
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.doRecreateIndex(ElasticsearchAdminServiceImpl.java:210)
	... 33 more
	Suppressed: ParsingException[Failed to parse object: expecting field with name [error] but found [took]]
		at org.elasticsearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:50)
		at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:605)
		at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
		at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2050)
		at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2026)
		... 39 more
```

Seems like when the a new index is created during the upgrade and re-index with the content from the old index, it fails because the limit settings from the old index are not copied. We need to make sure that either we copy the index settings or we set sensible limits so that most re-indexes don't fail.

**Comment by jdrossl** [comment]
@avasquez614 please verify

**Comment by avasquez614** [comment]
Verified
