### ISSUE TITLE
[studio] Invalid asset processing pipeline configuration causes Studio templates and groovy writes to fail silently

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3942]
## Describe the bug
Invalid asset processing pipeline configuration causes Studio templates and groovy writes to fail silently

## To Reproduce
1. Create a site based on editorial
2. Copy paste the asset processing pipeline config from docs (or from below)
3. Open, edit and save a template or controller. UI will report success, backend fails with exception

## Expected behavior
1. Asset processing failures should not impact write operations outside of static assets.
2. Write operation on asset impacted by processing pipeline should fail with meaningful message to user

## Screenshots
N/A

## Logs
```
[ERROR] 2020-04-03T13:07:05,633 [http-nio-8080-exec-10] [processing.AssetProcessingServiceImpl] | Error processing asset 
java.util.NoSuchElementException: Key 'keepOriginal' does not map to an existing object!
    at org.apache.commons.configuration2.AbstractConfiguration.throwMissingPropertyException(AbstractConfiguration.java:1901) ~[commons-configuration2-2.1.jar:2.1]
    at org.apache.commons.configuration2.AbstractConfiguration.checkNonNullValue(AbstractConfiguration.java:1888) ~[commons-configuration2-2.1.jar:2.1]
    at org.apache.commons.configuration2.AbstractConfiguration.getBoolean(AbstractConfiguration.java:1165) ~[commons-configuration2-2.1.jar:2.1]
```

### Version
Studio Version Number: 3.1.6-SNAPSHOT-768fca
Build Number: 768fca62056b29633b1569e06cb2ff966e5826d2

### OS
N/A

### Browser
N/A

## Additional context
Bad configuration example (missing a required element)
```
<assetProcessing>
    
    <pipelines>

        <!-- Huge transformer pipeline -->
        <pipeline>
            <inputPathPattern>^/static-assets/images/cms-available/(.+)\.jpeg$</inputPathPattern>
            <processors>
                <processor>
                    <type>ImageMagickTransformer</type>
                    <params>
                        <options>-resize 2000x1000</options>
                    </params>
                    <outputPathFormat>/static-assets/images/cms-available/(.+)/compressed/huge/$1-huge.jpeg</outputPathFormat>
                </processor>
            </processors>
        </pipeline>
        
        <!-- Large transformer pipeline -->
        <pipeline>
            <inputPathPattern>^/static-assets/images/cms-available/(.+)\.jpeg$</inputPathPattern>
            <processors>
                <processor>
                    <type>ImageMagickTransformer</type>
                    <params>
                        <options>-resize 1024x1024</options>
                    </params>
                    <outputPathFormat>/static-assets/images/cms-available/(.+)/compressed/large/$1-large.jpeg</outputPathFormat>
                </processor>
            </processors>
        </pipeline>

        <!-- Medium transformer pipeline -->
        <pipeline>
            <inputPathPattern>^/static-assets/images/cms-available/(.+)\.jpeg$</inputPathPattern>
            <processors>
                <processor>
                    <type>ImageMagickTransformer</type>
                    <params>
                        <options>-resize 300x300</options>
                    </params>
                    <outputPathFormat>/static-assets/images/cms-available/compressed/(.+)/medium/$1-medium.jpeg</outputPathFormat>
                </processor>
            </processors>
        </pipeline>

        <!-- Thumbnail transformer pipeline -->
        <pipeline>
            <inputPathPattern>^/static-assets/images/cms-available/(.+)\.jpeg$</inputPathPattern>
            <processors>
                <processor>
                    <type>ImageMagickTransformer</type>
                    <params>
                        <options>-resize 150x150</options>
                    </params>
                    <outputPathFormat>/static-assets/images/cms-available/compressed/(.+)/thumbnail/$1-thumbnail.jpeg</outputPathFormat>
                </processor>
            </processors>
        </pipeline>
    </pipelines>
</assetProcessing>
```

**Comment by dejan-brkic** [comment]
Fixed here:
https://github.com/craftercms/studio/pull/1942

**Comment by russdanner** [comment]
Comfirmed
