### ISSUE TITLE
[engine] Crafter Engine controllers should return 40x on requests which cannot be resolved

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4005]
## Describe the bug
When a request is sent to the page or static-assets controllers that Crafter engine cannot handle a 500 is returned and an exception is produced

Example: /a.xml
```
Caused by: java.lang.IllegalStateException: Unable to locate object to be marshalled in model: {}
	at org.springframework.web.servlet.view.xml.MarshallingView.renderMergedOutputModel(MarshallingView.java:105)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
```
Example 2: /static-assets
```
Caused by: java.lang.IllegalStateException: Required request attribute 'org.springframework.web.servlet.HandlerMapping.pathWithinHandlerMapping' is not set
	at org.craftercms.engine.controller.StaticAssetsRequestHandler.getPath(StaticAssetsRequestHandler.java:136)
	at org.craftercms.engine.controller.StaticAssetsRequestHandler.getResource(StaticAssetsRequestHandler.java:79)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:433)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
```

## To Reproduce
1) create a new site
2) access that site or set your crafterSite cookie
3) try to access a folder like: /static-assets
4) try to access a non-existent file like: /a-file.xml

## Expected behavior
Expected behavior would be the appropriate 400 series responses for these respective requests instead of a generic server error.

## Screenshots
N/A

## Logs
N/A

### Version
```
Studio Version Number: 3.1.6-SNAPSHOT-f684c6
Build Number: f684c6f70c638cf2ceb74d772ee8121eebbde408
Build Date/Time: 04-20-2020 15:09:28 -0400
```
### OS
Any

### Browser
Any

## Additional context
Any

**Comment by sumerjabri** [comment]
@russdanner is this really required in 3.1.x?

**Comment by russdanner** [comment]
Confirmed
