### ISSUE TITLE
[engine][groovysandbox] Allow closures to be used as Java lambdas

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4070]
## Describe the bug
Closures as lambdas don't work right now because of the sandbox.

## To Reproduce
1. Follow the guide for graphql custom schemas https://docs.craftercms.org/en/3.1/developers/cook-books/graphql/custom-graphql-schema.html

## Expected behavior
Groovy closures should be recognized as java lambdas

## Logs
```
[ERROR] 2020-05-18T16:42:08,347 [pool-38-thread-1] [wordify] [context.SiteContext] | Error building the GraphQL schema for site 'wordify' 
org.craftercms.engine.exception.ScriptException: No signature of method: org.craftercms.engine.graphql.impl.SchemaCustomizer.resolver() is applicable for argument types: (java.lang.String, graphql.init$_run_closure1) values: [WithIdenticalProps, graphql.init$_run_closure1@12338901]
Possible solutions: resolver(java.lang.String, graphql.schema.TypeResolver)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:74) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.runInitScript(GraphQLFactoryImpl.java:255) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.buildSchema(GraphQLFactoryImpl.java:233) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.graphql.impl.GraphQLFactoryImpl.getInstance(GraphQLFactoryImpl.java:272) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.service.context.SiteContext.buildGraphQLSchema(SiteContext.java:541) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.service.context.SiteContext.lambda$init$0(SiteContext.java:405) ~[classes/:3.2.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: groovy.lang.MissingMethodException: No signature of method: org.craftercms.engine.graphql.impl.SchemaCustomizer.resolver() is applicable for argument types: (java.lang.String, graphql.init$_run_closure1) values: [WithIdenticalProps, graphql.init$_run_closure1@12338901]
Possible solutions: resolver(java.lang.String, graphql.schema.TypeResolver)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:161) ~[script-security-1.72.2.jar:?]
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:169) ~[groovy-sandbox-1.27.2.jar:?]
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:173) ~[groovy-sandbox-1.27.2.jar:?]
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall.callStatic(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) ~[groovy-all-2.4.15.jar:2.4.15]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197) ~[groovy-all-2.4.15.jar:2.4.15]
	at graphql.init.run(init.groovy:35) ~[?:?]
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:72) ~[classes/:3.2.0-SNAPSHOT]
	... 8 more
```

### Version
3.2.0

**Comment by jdrossl** [comment]
This was fixed in https://github.com/craftercms/script-security-plugin/pull/4

**Comment by sumerjabri** [comment]
Failed when following the doc: https://docs.craftercms.org/en/3.1/developers/cook-books/graphql/custom-graphql-schema.html

The method triggering the problem:
```
  // performs a search call, returns the entries as maps
  def search(String title) {
    return [
      http.get() {
        // include the needed parameters
        request.uri.query  = [ apiKey: apiKey, t: title ]
      }
    ].flatten() // return a list even if the API only returns a single entry
  }
```

The logs:

https://gist.github.com/sumerjabri/5b1357c5b42d1ec05a954bba290768a6

**Comment by sumerjabri** [comment]
Verified using the GraphQL customization example.
