### ISSUE TITLE
[search] Error indexing with Solr

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4094]
## Describe the bug
The below issue is present on the deployer when trying to index with Solr enabled in Crafter 3.1.6

```
2020-05-28 13:00:10.862 ERROR 37016 --- [deployment-5] rcms.deployer.impl.DeploymentServiceImpl : Unexpected error occurred while executing deployment pipeline for target 'SITEID-preview'
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
at org.craftercms.deployer.impl.processors.SearchIndexingProcessor.searchField(SearchIndexingProcessor.java:120)
at org.craftercms.deployer.impl.processors.SearchIndexingProcessor.getItemsThatInheritDescriptor(SearchIndexingProcessor.java:77)
at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.addAffectedItemsToUpdatedFiles(AbstractSearchIndexingProcessor.java:329)
at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.addItemsThatInheritFromDescriptorToUpdatedFiles(AbstractSearchIndexingProcessor.java:314)
at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.getFilteredChangeSet(AbstractSearchIndexingProcessor.java:210)
at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:135)
at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:81)
at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:67)
at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:411)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

## To Reproduce
1. Enable Solr in Crafter 3.1.6
2. Edit and save content
3. See error

### Version
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 05-07-2020 17:31:21 -0400

### OS
Any

### Browser
N/A

**Comment by russdanner** [comment]
Confirmed
