### ISSUE TITLE
[engine] Groovy sandbox error when a method & a property have the same name

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4115]
If a groovy class has a property & a method with the same name the sandbox throws an error like this one:

```
Caused by: java.lang.UnsupportedOperationException: Insecure call to 'method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (org.craftercms.blueprints.headless.AuthorSearchHelper query)' you can tweak the security sandbox to allow it. Read more about this in the documentation.
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.reject(StaticWhitelist.java:290)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectMethod(StaticWhitelist.java:264)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:167)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:150)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:174)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:178)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:363)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty.callStatic(Unknown Source)
	at org.craftercms.blueprints.headless.SearchHelper.filter(SearchHelper.groovy:42)
	at org.craftercms.blueprints.headless.SearchHelper$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:176)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:174)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:178)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)
	at org.craftercms.blueprints.headless.AuthorSearchHelper.<init>(AuthorSearchHelper.groovy:27)
	at org.craftercms.blueprints.headless.AuthorSearchHelper.<init>(AuthorSearchHelper.groovy:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:221)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onNewInstance(GroovyInterceptor.java:42)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:180)
	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:218)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:223)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedConstructor$1.callStatic(Unknown Source)
	at list_get.run(list.get.groovy:23)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:599)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:72)
	... 95 more

```

**Comment by jdrossl** [comment]
@yacdaniel please help validate this, you do it by using a headless bp from 3.0.26

**Comment by yacdaniel** [comment]
Verified fixed.
