### ISSUE TITLE
[studio] The upgrade manager is broken

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4213]
## Describe the bug
A NPE is thrown for any repository (local or remote)

## To Reproduce
Create a site from an older repository or upgrade from a previous version

## Logs
```
Caused by: java.lang.NullPointerException
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.exists(SiteServiceImpl.java:1577) ~[classes/:3.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.getSite(SiteServiceImpl.java:1632) ~[classes/:3.1.9-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at com.sun.proxy.$Proxy252.getSite(Unknown Source) ~[?:?]
	at org.craftercms.studio.impl.v2.upgrade.pipeline.SiteRepositoryUpgradePipelineImpl.execute(SiteRepositoryUpgradePipelineImpl.java:118) ~[classes/:3.1.9-SNAPSHOT]
```

### Version
3.1.9-SNAPSHOT

### OS
Linux

**Comment by dejan-brkic** [comment]
Can not reproduce it.
By inspecting stacktrace it is a local build issue (either broken spring context or bad merge).

Otherwise we need more details for use case (version and blueprint)

**Comment by jdrossl** [comment]
I just did a full upgrade, my version is `3.1.9-SNAPSHOT-aff853` and I was able to reproduce it with these steps:
1. Start crafter
2. Create a site using the editorial blueprint
3. Delete the `config/studio/studio_version.xml` file from the site and commit
4. Restart crafter

When the upgrade manager tries to run the NPE is thrown

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2101
https://github.com/craftercms/studio/pull/2102

**Comment by jdrossl** [comment]
Verified
