### ISSUE TITLE
[engine] Authentication conflicts

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4222]
## Describe the bug
In preview there is a conflict with targeting that prevents headers authentication to work

## To Reproduce
1. Setup Crafter Profile & headers authentication
2. Add a url restriction to trigger the authentication
3. Try to preview the site

## Expected behavior
All authentication methods should work as expected in preview

## Logs
```
java.lang.IllegalArgumentException: Object of class [org.springframework.security.web.authentication.WebAuthenticationDetails] must be an instance of interface org.springframework.security.core.authority.GrantedAuthoritiesContainer
 at org.springframework.util.Assert.instanceCheckFailed(Assert.java:389) ~[spring-core-4.3.18.RELEASE.jar:4.3.18.RELEASE]
 at org.springframework.util.Assert.isInstanceOf(Assert.java:327) ~[spring-core-4.3.18.RELEASE.jar:4.3.18.RELEASE]
 at org.springframework.util.Assert.isInstanceOf(Assert.java:339) ~[spring-core-4.3.18.RELEASE.jar:4.3.18.RELEASE]
 at org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesUserDetailsService.loadUserDetails(PreAuthenticatedGrantedAuthoritiesUserDetailsService.java:58) ~[spring-security-web-4.2.13.RELEASE.jar:4.2.13.RELEASE]
 at org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesUserDetailsService.loadUserDetails(PreAuthenticatedGrantedAuthoritiesUserDetailsService.java:48) ~[spring-security-web-4.2.13.RELEASE.jar:4.2.13.RELEASE]
 at org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider.authenticate(PreAuthenticatedAuthenticationProvider.java:103) ~[spring-security-web-4.2.13.RELEASE.jar:4.2.13.RELEASE]
 at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-4.2.13.RELEASE.jar:4.2.13.RELEASE]
 at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doAuthenticate(AbstractPreAuthenticatedProcessingFilter.java:184) ~[spring-security-web-4.2.13.RELEASE.jar:4.2.13.RELEASE]
 at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:118) ~[spring-security-web-4.2.13.RELEASE.jar:4.2.13.RELEASE]
```
### Version
3.1.8

**Comment by jdrossl** [comment]
@yacdaniel please help validating this, let me know if you need help with the setup

**Comment by yacdaniel** [comment]
Verified fixed.
