### ISSUE TITLE
[studio] Publish Delete by Commit ID fails when the commit contains a delete at the root of the repository

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4254]
## Describe the bug
Publishing a Delete by Commit ID fails when the commit contains a delete at the root of the repository.

## To Reproduce
1. Create a new site "publishing-test"
2. Create a new file at the root of this site directory (publishing-test/sandbox/new-test-file.txt), create this file via the command line and not through Crafter Studio UI
3. Git commit this newly added file
4. Publish this commit ID through the publisher by going to Site Config --> Publishing --> Publish by Commit ID(s). This will be successful (publishing-test/published/new-test-file.txt)
5. Delete this file via the command line by doing "git rm new-test-file.txt" and commit the change.
6. Publish this commit through the publisher using the same approach by going to Site Config --> Publishing --> Publish by Commit ID(s). This will fail and publishing will be  #disabled with this item left in a READY_FOR_LIVE state in the publishing queue.

## Expected behavior
Delete's should be published when made via Git

## Screenshots
N/A

## Logs
From the tomcat/catalina.out logs: 

```
[ERROR] 2020-07-30T08:47:59,922 [Studio_Publisher_Thread_Pool3] [git.GitContentRepository] | Error when publishing site test-for-publishing to environment live 
java.lang.NullPointerException: null 
at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.deleteParentFolder(GitContentRepository.java:413) ~[classes/:3.1.8] 
at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:1210) [classes/:3.1.8] 
at org.craftercms.studio.impl.v2.repository.blob.BlobAwareContentRepository.publish(BlobAwareContentRepository.java:402) [classes/:3.1.8] 
at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.deploy(PublisherTask.java:381) [classes/:3.1.8] 
at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.doPublishing(PublisherTask.java:251) [classes/:3.1.8] 
at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.run(PublisherTask.java:151) [classes/:3.1.8] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121] 
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

### Version
```
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 05-07-2020 17:31:21 -0400
```

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by russdanner** [comment]
Assigning to myself for review

**Comment by russdanner** [comment]
This bug duplicates 
https://github.com/craftercms/craftercms/issues/3784

We determined in January that we would not fix this issue for the following reasons:
1. Studio Auto publishes a delete
2. Auto-publishing a delete encountered while processing the git history is dangerous.
3. A manual publish of a delete by commit ID works and is deterministic.

For the same reason I am closing this issue as wont fix.

**Comment by russdanner** [comment]
Correction. This bug does NOT duplicate #3784
It's a special case of the Publish by commit work-around. 
As such I am re-opening this issue.

**Comment by sumerjabri** [comment]
The delete should happen externally (not under Studio in Sandbox) and then pulled in. This generates a merge commit that can be published and that should work.

Closing as an invalid use-case.
