### ISSUE TITLE
[deployer] The upgrade of a target shouldn't fail if an ES index doesn't previously exist

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4267]
## Describe the bug
When creating a target in 3.1.6 that has no ES index associated, when trying to upgrade to 3.1.8, the upgrade of the target fails.

## To Reproduce
1. Start a 3.1.6 instance.
2. Create an empty site (call it `empty`)
3. Copy the following as the `empty-backup-target.yaml` target (it's just a simple dummy target).

```
target:
  env: dummy
  siteName: empty
  localRepoPath: /opt/crafter/data/repos/sites/empty/sandbox
  crafterSearchEnabled: false
  deployment:
    scheduling:
      enabled: true
      cron: 0 0 * * * *
    pipeline:
    - processorName: fileOutputProcessor
      processorLabel: fileOutputProcessor
version: '1.1'
```

4. Upgrade the instance to 3.1.9 or copy the data folder to a 3.1.9 instance.
5. Start the 3.1.9 instance

You should see the following error:

```
2020-08-31 18:18:49.804 ERROR 5881 --- [main] oyer.impl.upgrade.DeployerUpgradeManager : Error during upgrade for target TargetImpl{env='dummy', siteName='empty', configurationFile=/home/alfonso/code/craftercms-installs/crafter-cms-authoring-3.1.9E/crafter/data/deployer/targets/empty-dummy.yaml}
org.craftercms.commons.upgrade.exception.UpgradeException: Error during upgrade for target TargetImpl{env='dummy', siteName='empty', configurationFile=/home/alfonso/code/craftercms-installs/crafter-cms-authoring-3.1.9E/crafter/data/deployer/targets/empty-dummy.yaml}
	at org.craftercms.commons.upgrade.impl.AbstractUpgradeManager.upgrade(AbstractUpgradeManager.java:65)
	at org.craftercms.deployer.impl.TargetServiceImpl.loadTarget(TargetServiceImpl.java:365)
	at org.craftercms.deployer.impl.TargetServiceImpl.resolveTargetFromConfigFile(TargetServiceImpl.java:336)
	at org.craftercms.deployer.impl.TargetServiceImpl.resolveTargets(TargetServiceImpl.java:213)
	at org.craftercms.deployer.impl.TargetServiceImpl.onApplicationEvent(TargetServiceImpl.java:162)
	at org.craftercms.deployer.impl.TargetServiceImpl.onApplicationEvent(TargetServiceImpl.java:77)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.craftercms.deployer.DeployerApplication.main(DeployerApplication.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: org.craftercms.commons.upgrade.exception.UpgradeException: Error executing upgrade operation class org.craftercms.deployer.impl.upgrade.operations.ElasticsearchIndexUpgradeOperation
	at org.craftercms.commons.upgrade.impl.operations.AbstractUpgradeOperation.execute(AbstractUpgradeOperation.java:98)
	at org.craftercms.commons.upgrade.impl.pipeline.DefaultUpgradePipelineImpl.execute(DefaultUpgradePipelineImpl.java:81)
	at org.craftercms.commons.upgrade.impl.AbstractUpgradeManager.executePipeline(AbstractUpgradeManager.java:102)
	at org.craftercms.deployer.impl.upgrade.DeployerUpgradeManager.doUpgrade(DeployerUpgradeManager.java:52)
	at org.craftercms.deployer.impl.upgrade.DeployerUpgradeManager.doUpgrade(DeployerUpgradeManager.java:34)
	at org.craftercms.commons.upgrade.impl.AbstractUpgradeManager.upgrade(AbstractUpgradeManager.java:63)
	... 24 more
Caused by: org.craftercms.search.elasticsearch.exception.ElasticsearchException: [empty] Error upgrading index empty
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.doRecreateIndex(ElasticsearchAdminServiceImpl.java:218)
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.recreateIndex(ElasticsearchAdminServiceImpl.java:183)
	at org.craftercms.deployer.impl.upgrade.operations.ElasticsearchIndexUpgradeOperation.doExecute(ElasticsearchIndexUpgradeOperation.java:50)
	at org.craftercms.deployer.impl.upgrade.operations.ElasticsearchIndexUpgradeOperation.doExecute(ElasticsearchIndexUpgradeOperation.java:32)
	at org.craftercms.commons.upgrade.impl.operations.AbstractUpgradeOperation.execute(AbstractUpgradeOperation.java:96)
	... 29 more
Caused by: java.lang.IllegalStateException: None or more than one index is associated with alias: empty
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.doGetIndexName(ElasticsearchAdminServiceImpl.java:226)
	at org.craftercms.search.elasticsearch.impl.ElasticsearchAdminServiceImpl.doRecreateIndex(ElasticsearchAdminServiceImpl.java:193)
	... 33 more
```

## Expected behavior
The target shouldn't need an ES index to be upgraded (since it doesn't have any ES processor).

Also, for any upgrade that requires an ES index to exist, if the index doesn't exist, the upgrade should be skipped since it's not needed.

**Comment by avasquez614** [comment]
@jdrossl the issue with the exception is done, but I'm not sure why we're still recreating the index on a target that doesn't have an index. Can we just detect that the target has an Elasticsearch processor and if not don't do the upgrade?

```
2020-09-14 16:52:38.848  INFO 18685 --- [main] oyer.impl.upgrade.DeployerUpgradeManager : Starting upgrade for target 'TargetImpl{env='backup', siteName='editorial', configurationFile=/home/alfonso/code/craftercms-e-3.1.x/crafter-authoring/data/deployer/targets/editorial-backup-target.yaml}'
2020-09-14 16:52:38.968  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ============================================================
2020-09-14 16:52:38.968  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : Starting execution of upgrade pipeline: target
2020-09-14 16:52:38.969  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation ElasticsearchIndexUpgradeOperation -------
2020-09-14 16:52:38.969  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : Waiting for Elasticsearch cluster to be ready
2020-09-14 16:52:39.321  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : Recreating index for alias editorial
2020-09-14 16:52:39.390  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : No index found for alias editorial, skipping recreate operations
2020-09-14 16:52:39.391  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation ElasticsearchIndexUpgradeOperation completed -------
2020-09-14 16:52:39.391  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation ReplaceProcessorUpgradeOperation -------
2020-09-14 16:52:39.417  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation ReplaceProcessorUpgradeOperation completed -------
2020-09-14 16:52:39.420  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation EncryptionUpgradeOperation -------
2020-09-14 16:52:39.426  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation EncryptionUpgradeOperation completed -------
2020-09-14 16:52:39.427  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation AddLifecycleHookUpgradeOperation -------
2020-09-14 16:52:39.428  INFO 18685 --- [main] rations.AddLifecycleHookUpgradeOperation : Processor 'gitPullProcessor' not found in pipeline for target 'editorial-backup', operation will be skipped
2020-09-14 16:52:39.430  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation AddLifecycleHookUpgradeOperation completed -------
2020-09-14 16:52:39.430  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation ProcessorUpgradeOperation -------
2020-09-14 16:52:39.438  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation ProcessorUpgradeOperation completed -------
2020-09-14 16:52:39.439  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation ElasticsearchIndexUpgradeOperation -------
2020-09-14 16:52:39.439  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : Waiting for Elasticsearch cluster to be ready
2020-09-14 16:52:39.443  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : Recreating index for alias editorial
2020-09-14 16:52:39.449  INFO 18685 --- [main] earch.impl.ElasticsearchAdminServiceImpl : No index found for alias editorial, skipping recreate operations
2020-09-14 16:52:39.449  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation ElasticsearchIndexUpgradeOperation completed -------
2020-09-14 16:52:39.450  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Starting execution of operation UpdateVersionUpgradeOperation -------
2020-09-14 16:52:39.456  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ------- Execution of operation UpdateVersionUpgradeOperation completed -------
2020-09-14 16:52:39.457  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : Execution of pipeline target completed
2020-09-14 16:52:39.457  INFO 18685 --- [main] impl.pipeline.DefaultUpgradePipelineImpl : ============================================================
2020-09-14 16:52:39.457  INFO 18685 --- [main] org.craftercms.deployer.impl.TargetImpl  : Closing target 'editorial-backup'...
2020-09-14 16:52:39.461  INFO 18685 --- [main] org.craftercms.deployer.impl.TargetImpl  : Stopping current and pending deployments for target 'editorial-backup'
2020-09-14 16:52:39.461  INFO 18685 --- [main] org.craftercms.deployer.impl.TargetImpl  : Releasing resources for target 'editorial-backup'
```

**Comment by avasquez614** [comment]
@jdrossl found another issue, for authoring targets the ES upgrade is skipped, probably because the ES processor has a different name (`authoringElasticsearchIndexingProcessor`):

```
2020-10-01 17:41:30.774  INFO 27781 --- [main] tions.ElasticsearchIndexUpgradeOperation : Target vccraftercloudio-authoring does not use Elasticsearch so will be skipped
```

**Comment by avasquez614** [comment]
Verified
