### ISSUE TITLE
[studio] Studio fails to parse the Engine's URL rewrite config sample

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4380]
## Describe the bug
Studio fails to parse the Engine's URL rewrite config sample

## To Reproduce
1. Create a site from any BP
2. Go to Site Config -> Configuration
3. Select Engine URL Rewrite Configuration (XML Style)
4. Use the Configuration sample
5. Check Catalina log, publishing will be disabled in the site.

## Expected behavior
Studio shouldn't fail to parse the configuration sample.

## Screenshots
N/A

## Logs
```
[INFO] 2020-11-03T12:16:40,685 [Studio_Publisher_Thread_Pool9] [site.SiteServiceImpl] | Syncing database with repository for site: ed2 fromCommitId = 31cfced2fdf7ede774bcfbc0f70eebd3a5367161 
[ERROR] 2020-11-03T12:16:40,724 [Studio_Publisher_Thread_Pool9] [job.PublisherTask] | Failed to sync database from repository for site ed2 
org.craftercms.core.exception.XmlFileParseException: Error while parsing xml document at /home/yacdaniel/work/craftercms3.2.x/crafter-authoring/data/repos/sites/ed2/sandbox/config/engine/urlrewrite.xml
	at org.craftercms.core.store.impl.AbstractFileBasedContentStoreAdapter.doFindItem(AbstractFileBasedContentStoreAdapter.java:166) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.store.impl.AbstractCachedContentStoreAdapter$3.execute(AbstractCachedContentStoreAdapter.java:113) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.store.impl.AbstractCachedContentStoreAdapter$3.execute(AbstractCachedContentStoreAdapter.java:109) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.loadAndPutInCache(DefaultCacheTemplate.java:109) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.getObject(DefaultCacheTemplate.java:83) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.store.impl.AbstractCachedContentStoreAdapter.findItem(AbstractCachedContentStoreAdapter.java:109) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.engine.cache.CacheWarmingAwareContentStoreAdapterDecorator.findItem(CacheWarmingAwareContentStoreAdapterDecorator.java:125) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.engine.targeting.impl.TargetedContentStoreAdapterDecorator.findItem(TargetedContentStoreAdapterDecorator.java:173) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.core.service.impl.ContentStoreServiceImpl.doFindItem(ContentStoreServiceImpl.java:282) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.service.impl.AbstractCachedContentStoreService$2.execute(AbstractCachedContentStoreService.java:147) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.service.impl.AbstractCachedContentStoreService$2.execute(AbstractCachedContentStoreService.java:143) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.loadAndPutInCache(DefaultCacheTemplate.java:109) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.getObject(DefaultCacheTemplate.java:83) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.service.impl.AbstractCachedContentStoreService.findItem(AbstractCachedContentStoreService.java:143) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.core.service.impl.AbstractCachedContentStoreService.getItem(AbstractCachedContentStoreService.java:163) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.repository.GitContentRepository.getItem(GitContentRepository.java:1421) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.repository.GitContentRepository$$FastClassBySpringCGLIB$$fe2ec81.invoke(<generated>) ~[classes/:3.2.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.craftercms.studio.impl.v2.repository.GitContentRepository$$EnhancerBySpringCGLIB$$55427c69.getItem(<generated>) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.repository.blob.BlobAwareContentRepository.getItem(BlobAwareContentRepository.java:606) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.service.content.internal.ContentServiceInternalImpl.getItem(ContentServiceInternalImpl.java:139) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.service.item.internal.ItemServiceInternalImpl.persistItemAfterWrite(ItemServiceInternalImpl.java:411) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1261) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1139) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$FastClassBySpringCGLIB$$562e9c15.invoke(<generated>) ~[classes/:3.2.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$EnhancerBySpringCGLIB$$c00e41e0.syncDatabaseWithRepo(<generated>) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.syncRepository(PublisherTask.java:214) ~[classes/:3.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.run(PublisherTask.java:128) [classes/:3.2.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.dom4j.DocumentException: Error on line 19 of document  : DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at org.dom4j.io.SAXReader.read(SAXReader.java:511) ~[dom4j-2.1.3.jar:?]
	at org.dom4j.io.SAXReader.read(SAXReader.java:408) ~[dom4j-2.1.3.jar:?]
	at org.craftercms.core.store.impl.AbstractFileBasedContentStoreAdapter.doFindItem(AbstractFileBasedContentStoreAdapter.java:159) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	... 48 more
Caused by: org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[daisydiff.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[daisydiff.jar:?]
	at org.dom4j.io.SAXReader.read(SAXReader.java:494) ~[dom4j-2.1.3.jar:?]
	at org.dom4j.io.SAXReader.read(SAXReader.java:408) ~[dom4j-2.1.3.jar:?]
	at org.craftercms.core.store.impl.AbstractFileBasedContentStoreAdapter.doFindItem(AbstractFileBasedContentStoreAdapter.java:159) ~[crafter-core-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT]
	... 48 more
[INFO] 2020-11-03T12:16:40,726 [Studio_Publisher_Thread_Pool9] [job.PublisherTask] | Publishing is disabled for site ed2 
```

### Version
`3.2.0-SNAPSHOT`

### OS
Ubuntu

### Browser
N/A

## Additional context
N/A

**Comment by yacdaniel** [comment]
Verified fixed in `Crafter CMS 3.2.0-SNAPSHOT`
