### ISSUE TITLE
[deployer] Binary files from blob store can't be indexed

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4381]
## Describe the bug
For targets in delivery the blob store is looking for a mapping of `default` instead of `live`

## To Reproduce
1. Create a site & setup the blob store
2. Upload a document to static-assets & publish to live
3. Check the log of the deployer in delivery

## Expected behavior
The deployer should use the mapping for `live`

## Logs
```
2020-11-03 14:54:33.533 ERROR 49638 --- [deployment-4] s.search.batch.impl.AbstractBatchIndexer : Error while trying to perform update of file empty:/static-assets/s3/DAM.pdf
java.lang.NullPointerException
	at org.craftercms.commons.file.blob.impl.s3.AwsS3BlobStore.doGetContent(AwsS3BlobStore.java:66)
	at org.craftercms.commons.file.blob.impl.AbstractBlobStore.getResource(AbstractBlobStore.java:119)
	at org.craftercms.core.service.impl.ContentStoreServiceImpl.findContent(ContentStoreServiceImpl.java:244)
	at org.craftercms.core.service.impl.ContentStoreServiceImpl.getContent(ContentStoreServiceImpl.java:268)
	at org.craftercms.core.service.impl.ContentStoreServiceImpl.getContent(ContentStoreServiceImpl.java:259)
	at org.craftercms.search.batch.impl.AbstractBinaryFileBatchIndexer.doSingleFileUpdate(AbstractBinaryFileBatchIndexer.java:71)
	at org.craftercms.search.batch.impl.AbstractBatchIndexer.updateIndex(AbstractBatchIndexer.java:62)
	at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.doMainProcess(AbstractSearchIndexingProcessor.java:293)
	at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.doExecute(AbstractMainDeploymentProcessor.java:51)
	at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:148)
	at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.execute(AbstractSearchIndexingProcessor.java:205)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:81)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:67)
	at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:411)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Version
3.1.x & 3.2

**Comment by jdrossl** [comment]
@yacdaniel please help validate this

**Comment by sumerjabri** [comment]
Validated in 3.1.x

**Comment by yacdaniel** [comment]
Verified fixed in 3.2.x

**Comment by avasquez614** [comment]
Still happening, when the Deployer's target env is `serverless-delivery`. We should assume that if the env is not in the config list it's automatically `live`.

**Comment by avasquez614** [comment]
Verified
