### ISSUE TITLE
[search] Elasticsearch client becomes defunct due to unhandled exception

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4446]
## Describe the bug
Elasticsearch client has an underlying issue/unhandled exception that ultimately disables its ability to complete requests .
https://github.com/elastic/elasticsearch/issues/45115

The symptom in Crafter is a 500 response and the the following exception:
```
Caused by: org.craftercms.search.elasticsearch.exception.ElasticsearchException: [sellercenter-au] Error executing search request
at org.craftercms.search.elasticsearch.impl.AbstractElasticsearchWrapper.search(AbstractElasticsearchWrapper.java:111) ~[crafter-search-elasticsearch-3.1.10E.jar:?]
at org.craftercms.search.elasticsearch.ElasticsearchWrapper.search(ElasticsearchWrapper.java:39) ~[crafter-search-elasticsearch-3.1.10E.jar:?]
at org.craftercms.search.elasticsearch.ElasticsearchWrapper$search.call(Unknown Source) ~[?:?]

Caused by: java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:812) ~[elasticsearch-rest-client-7.2.1.jar:7.2.1]
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225) ~[elasticsearch-rest-client-7.2.1.jar:7.2.1]
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.2.1.jar:7.2.1]

Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.4.jar:4.4.4]
at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar:4.1.4]
at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar:4.1.4]
```

## To Reproduce
1. This appears to be a function of time in certain environments

## Expected behavior
Crafter should re-initialize ES Client if this condition is detected

## Screenshots
N/A

## Logs
See exception in description

### Version
Crafter 3.1.10E, 3.1.11E

### OS
Ubuntu

### Browser
N/A

**Comment by avasquez614** [comment]
@jdrossl take a look at this, it could be a fix for most cases: https://github.com/elastic/elasticsearch/issues/49124#issuecomment-646453705

**Comment by russdanner** [comment]
Confirmed
