### ISSUE TITLE
Delivery site failing

### ISSUE THREAD

**Issue by dokuboyejo** [craftercms/craftercms#4484]
## Describe the bug
After initializing the delivery site from authoring, the delivery site didn't load

## To Reproduce
1. Create a new authoring site e.g. test-site
2. Publish the site in authoring env
3. Ensure delivery system can access the authoring system
4. Initialize the site on delivery system `./init-site.sh -b live [SITE_ID] ssh://crafter@[DNS_NAME_OF_AUTHORING_SERVER]:/opt/crafter/data/repos/sites/[SITE_ID]/published`

## Expected behavior
The delivery site shoud load without eror

## Screenshots
![image](https://user-images.githubusercontent.com/969476/105676015-93d15c00-5ef2-11eb-82f0-d0dd4f724e3d.png)

## Logs
```

site:/scripts/pages/home.groovy: 17: unable to resolve class org.craftercms.sites.editorial.SearchHelper
 @ line 17, column 1.
   import org.craftercms.sites.editorial.SearchHelper
   ^

2 errors

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309) ~[groovy-all-2.4.19.jar:2.4.19]
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:981) ~[groovy-all-2.4.19.jar:2.4.19]
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626) ~[groovy-all-2.4.19.jar:2.4.19]
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:575) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:250) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:237) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:236) ~[groovy-all-2.4.19.jar:2.4.19]
        at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:562) ~[groovy-all-2.4.19.jar:2.4.19]
        at org.craftercms.engine.scripting.impl.GroovyScriptFactory.lambda$getScript$0(GroovyScriptFactory.java:75) ~[classes/:3.1.12]
        at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.loadAndPutInCache(DefaultCacheTemplate.java:109) ~[crafter-core-3.1.12.jar:3.1.12]
        at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.getObject(DefaultCacheTemplate.java:83) ~[crafter-core-3.1.12.jar:3.1.12]
        at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.getObject(DefaultCacheTemplate.java:73) ~[crafter-core-3.1.12.jar:3.1.12]
        at org.craftercms.engine.scripting.impl.GroovyScriptFactory.getScript(GroovyScriptFactory.java:73) ~[classes/:3.1.12]
        at org.craftercms.engine.view.CrafterPageViewResolver.loadScripts(CrafterPageViewResolver.java:308) ~[classes/:3.1.12]
        at org.craftercms.engine.view.CrafterPageViewResolver.lambda$getCachedLocalizedView$0(CrafterPageViewResolver.java:282) ~[classes/:3.1.12]
        at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.loadAndPutInCache(DefaultCacheTemplate.java:109) ~[crafter-core-3.1.12.jar:3.1.12]
        at org.craftercms.core.util.cache.impl.DefaultCacheTemplate.getObject(DefaultCacheTemplate.java:83) ~[crafter-core-3.1.12.jar:3.1.12]
        at org.craftercms.engine.view.CrafterPageViewResolver.getCachedLocalizedView(CrafterPageViewResolver.java:251) ~[classes/:3.1.12]
        at org.craftercms.engine.view.CrafterPageViewResolver.resolveViewName(CrafterPageViewResolver.java:198) ~[classes/:3.1.12]
        at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.getCandidateViews(ContentNegotiatingViewResolver.java:299) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.resolveViewName(ContentNegotiatingViewResolver.java:220) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1325) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1263) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.29.RELEASE.jar:4.3.29.RELEASE]
        ... 133 more
```

### Version
Authoring v 3.1.12

### OS
Ubuntu 18.04.5 LTS

### Browser
FireFox 84.0.2 (64-bit)

**Comment by russdanner** [comment]
Hi Do, this issue repository is intended for software bugs, feature requests and tasks.  
As this issue pertains to installation concerns we'll close this ticket here and assist in opening a new version of it in the appropriate channels.

**Comment by davidassigbi** [comment]
Hi y'all. I do know you said this issue wasn't posted at the right place but when you closed it, you didn't tell us where you moved it. Can we get a hint about that or even better where we should post such issues ?
I am asking because I am also facing the same issue for more than two day now...

**Comment by sumerjabri** [comment]
@davidassigbi please join us here: https://join.slack.com/t/craftercms/shared_invite/enQtNDg0NzI3NzA0NjMwLWZmMGQzMDViMzA5NDE1YjMzM2M1N2JlOWJlZDA1MjA2MGJlZjgzNDVlMmI5ODQxNmNjMWQ3NzA5ZWNkN2UxOWE

You can ask questions of the community there.
