### ISSUE TITLE
[studio] Synchronized block in getOperations causes possible thread based locks on lockItem repository action

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4585]
## Describe the bug
We find scenarios (see attached thread dump) where sync repo operation (running in a job) blocks LockItem operations (running in a user thread)

Relevent code:

Lock Item is from v1 GitContentRepository
https://github.com/craftercms/studio/blob/8171823c8c9d8d7bb5ff390e0b2de64c8eebcb80/src/main/java/org/craftercms/studio/impl/v1/repository/git/GitContentRepository.java

getOperationsFromDelta(GitContentRepository and processDiffEntry are from v2 GitContentRepository
https://github.com/craftercms/studio/blob/support/3.1.x/src/main/java/org/craftercms/studio/impl/v2/repository/GitContentRepository.java  

There seems to be a lock between this type of thread:

```
"Studio_Publisher_Thread_Pool2" #94 prio=5 os_prio=31 tid=0x00007fcb2b5d0800 nid=0x14203 runnable [0x000070000c362000]
   java.lang.Thread.State: RUNNABLE
 at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:154)
 at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
 at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
 at java.lang.StringBuilder.append(StringBuilder.java:136)
 at java.io.UnixFileSystem.resolve(UnixFileSystem.java:108)
 at java.io.File.<init>(File.java:367)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.fileFor(ObjectDirectory.java:1037)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openLooseObject(ObjectDirectory.java:476)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openLooseFromSelfOrAlternate(ObjectDirectory.java:432)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:408)
 at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:132)
 at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:191)
 at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:226)
 at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:204)
 at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:1)
 at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1270)
 at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:826)
 at org.eclipse.jgit.revwalk.TreeRevFilter.include(TreeRevFilter.java:124)
 at org.eclipse.jgit.revwalk.filter.AndRevFilter$Binary.include(AndRevFilter.java:104)
 at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:108)
 at org.eclipse.jgit.revwalk.BlockRevQueue.<init>(BlockRevQueue.java:40)
 at org.eclipse.jgit.revwalk.FIFORevQueue.<init>(FIFORevQueue.java:37)
 at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:133)
 at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:443)
 at org.eclipse.jgit.revwalk.RevWalk.nextForIterator(RevWalk.java:1378)
 at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1402)
 at org.craftercms.studio.impl.v2.repository.GitContentRepository.processDiffEntry(GitContentRepository.java:518)
 at org.craftercms.studio.impl.v2.repository.GitContentRepository.getOperationsFromDelta(GitContentRepository.java:442)
 - locked <0x00000006c4986f30> (a org.eclipse.jgit.internal.storage.file.FileRepository)
 at org.craftercms.studio.impl.v2.repository.GitContentRepository$$FastClassBySpringCGLIB$$fe2ec81.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
 at org.craftercms.studio.impl.v2.repository.GitContentRepository$$EnhancerBySpringCGLIB$$d5b5cad2.getOperationsFromDelta(<generated>)
 at org.craftercms.studio.impl.v2.repository.blob.BlobAwareContentRepository.getOperationsFromDelta(BlobAwareContentRepository.java:587)
 at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1133)
 at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.syncDatabaseWithRepo(SiteServiceImpl.java:1123)
 at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$FastClassBySpringCGLIB$$562e9c15.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
 at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
 at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$EnhancerBySpringCGLIB$$3110d8fe.syncDatabaseWithRepo(<generated>)
 at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.syncRepository(PublisherTask.java:217)
 at org.craftercms.studio.impl.v1.service.deployment.job.PublisherTask.run(PublisherTask.java:131)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

And any user thread that tries to lock/edit an item (xml, groovy, etc)

```
"http-nio-8080-exec-1" #123 daemon prio=5 os_prio=31 tid=0x00007fcb2c235800 nid=0x13003 waiting for monitor entry [0x000070000d595000]
   java.lang.Thread.State: BLOCKED (on object monitor)
 at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.lockItem(GitContentRepository.java:817)
 - waiting to lock <0x00000006c4986f30> (a org.eclipse.jgit.internal.storage.file.FileRepository)
 at org.craftercms.studio.impl.v1.repository.git.GitContentRepository$$FastClassBySpringCGLIB$$fd69e59c.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
 at org.craftercms.studio.impl.v1.repository.git.GitContentRepository$$EnhancerBySpringCGLIB$$9b55bf03.lockItem(<generated>)
 at org.craftercms.studio.impl.v2.repository.blob.BlobAwareContentRepository.lockItem(BlobAwareContentRepository.java:337)
 at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.lockContent(ContentServiceImpl.java:2314)
 at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$FastClassBySpringCGLIB$$a67efd9f.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
 at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
 at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$EnhancerBySpringCGLIB$$a89c1578.lockContent(<generated>)
 at org.craftercms.studio.api.v1.service.content.ContentService$lockContent$1.call(Unknown Source)
 at scripts.api.impl.content.SpringContentServices.lockContent(SpringContentServices.groovy:228)
 at scripts.api.impl.content.SpringContentServices$lockContent$1.call(Unknown Source)
 at scripts.api.ContentServices.getContent(ContentServices.groovy:79)
 at scripts.api.ContentServices$getContent$3.call(Unknown Source)
 at get-content_get.run(get-content.get.groovy:50)
```
## To Reproduce
N/A

## Expected behavior
getOperations does not require a synchronization because no writes are performed in this task. 
Remove the synchronization. 

## Screenshots
N/A
## Logs
See attached thread thread dump
[dump5.txt](https://github.com/craftercms/craftercms/files/6144753/dump5.txt)

### Version
Studio Version Number: 3.1.14-SNAPSHOT-26fc18
Build Number: 26fc18c1ec63332b0c035111a3c899b94cac5c20
Build Date/Time: 03-15-2021 16:26:19 -0400

### OS
All

### Browser
Any

**Comment by mcgitty** [comment]
Notice the victim thread is calling get-content. Isn't that also a read-only operation, thus shouldn't acquire a lock either?

**Comment by dejan-brkic** [comment]
3.1.x
PR:
https://github.com/craftercms/studio/pull/2465

**Comment by russdanner** [comment]
CONFIRMED
