### ISSUE TITLE
[docs] Add TLS < 1.2 unsupported by Java message in the release notes

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4687]
Please add a message like the following in the 3.1.14 and 4.0.0 release notes:

Java has decided to disable support for TLS versions minor to 1.2 in the latest Java version 1.8.0_292. If you encounter the following error in your application:

```
 Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)                                                                        
     at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171) ~[?:1.8.0_292]                                                                                                                
     at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98) ~[?:1.8.0_292]                                                                                                     
     at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220) ~[?:1.8.0_292]                                                                                                             
     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428) ~[?:1.8.0_292]                                                                                                              
     at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                   
     at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                         
     at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                      
     at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:333) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                  
     at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                     
     at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                                
     at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                                              
     at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                             
     at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[mysql-connector-java-8.0.23.jar:8.0.23]                                                                                   
     ... 173 more
```

It means your application is doing a connection with a version prior to TLSv1.2. Please check the documentation of the library performing the connection to see if there's a way to enforce TLSv1.2 or higher (for example, when using a MySQL JDBC driver you can enforce it by adding the `enabledTLSProtocols=TLSv1.2` parameter to your connection string). If you must use TLSv1 or TLSv1.1, look for the `java.security file` in `JDK_INSTALL_HOME/jre//lib/security`, and change the property:

```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```

to:

```
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
    EC keySize < 224, 3DES_EDE_CBC, anon, NULL
```

**Comment by sumerjabri** [comment]
@alhambrav perhaps we add the note in 3.1.14 release notes, but more importantly, we add it to a troubleshooting guide/system admin. This will happen regardless of the crafter version, it's a JVM thing.

**Comment by alhambrav** [comment]
3.1:  https://github.com/craftercms/docs/pull/1194/commits/ab6b22ab16b2cf40c69a5c3d1da6fb20b4fe97b8
master: https://github.com/craftercms/docs/pull/1243

**Comment by avasquez614** [comment]
Verified in 3.1.14
