### ISSUE TITLE
[studio] Could not find matching constructor for: org.craftercms.studio.api.v1.job.CronJobContext

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#485]
Using the latest Studio master, every 5 mins the following error appears:

```
[INFO] 2017-02-27 10:15:00,005 [craftercms_scheduler_Worker-2] [core.JobRunShell] | Job DEFAULT.craftercms:/scripts/jobs/every-5-minutes/content-monitoring.groovy threw a JobExecutionException:  
org.quartz.JobExecutionException: Error executing script job at /scripts/jobs/every-5-minutes/content-monitoring.groovy [See nested exception: org.craftercms.engine.exception.ScriptException: Could not find matching constructor for: org.craftercms.studio.api.v1.job.CronJobContext(java.lang.String)]
	at org.craftercms.engine.scripting.impl.ScriptJob.execute(ScriptJob.java:47)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.craftercms.engine.exception.ScriptException: Could not find matching constructor for: org.craftercms.studio.api.v1.job.CronJobContext(java.lang.String)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:61)
	at org.craftercms.engine.scripting.impl.ScriptJob.execute(ScriptJob.java:45)
	... 2 more
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.craftercms.studio.api.v1.job.CronJobContext(java.lang.String)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1723)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1526)
	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
	at content-monitoring.run(content-monitoring.groovy:33)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:589)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
	... 3 more
```

**Comment by dejan-brkic** [comment]
PR #552
