### ISSUE TITLE
[studio] Clock task error messages should include site ID

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4977]
# Feature Request

#### Is your feature request related to a problem? Please describe.
When a clock task in  Studio throws an error it's not possible to know what site is having an issue because the site ID is not included in all error messages.

Example:
```
Exception in thread "studio.clockTaskExecutor-49" java.lang.UnsupportedOperationException: Cannot check out from unborn branch
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:202)
	at org.craftercms.studio.impl.v2.job.StudioClusterPublishedRepoSyncTask.updatePublishedBranch(StudioClusterPublishedRepoSyncTask.java:420)
	at org.craftercms.studio.impl.v2.job.StudioClusterPublishedRepoSyncTask.updateContent(StudioClusterPublishedRepoSyncTask.java:376)
	at org.craftercms.studio.impl.v2.job.StudioClusterPublishedRepoSyncTask.executeInternal(StudioClusterPublishedRepoSyncTask.java:180)
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:80)
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor$1.run(StudioClockExecutor.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

#### Describe the solution you'd like
Include the site ID in all clock task error messages

#### Describe alternatives you've considered
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2729
https://github.com/craftercms/studio/pull/2730

**Comment by russdanner** [comment]
Confirmed
