### ISSUE TITLE
[studio]  studio sometimes deletes files but fails to commit to git sandbox repository 

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4999]
#### Crafter CMS Version
3.1.17

#### Describe the bug
Sometimes, after deleting a page with several subpages in the same path, Studio fails to delete everything properly. The files are removed from the filesystem, but deletes are not committed to the repo and files still appear in Studio sidebar.
When authors try to delete content again, it does not always get deleted (we don't know exactly which scenario is causing content to get blocked though).
So far the fix has been manually committing the deleted files. However, this is becoming more frequent and is causing confusion to authors.

#### To Reproduce
1. Start Studio 3.1.x
2. Create a new site name 'testing'
3. Copy attached website folder into the site sandbox then commit via command-line tool
[website.zip](https://github.com/craftercms/craftercms/files/7141523/website.zip)

4. Reload Studio UI, notice that files are added
5. Publish each file via UI, confirmed that all files under `f2` folder have been published
6. Delete `f2` folder
7. Notice that not all pages are deleted in UI but when clicking on the page, an error says content is not available

#### Logs

```
[ERROR] 2021-09-10T12:38:47,388 [studio.clockTaskExecutor-17] [git.GitContentRepository] | Error while deleting content for site: testing path: /site/website/f2/index.xml 
java.nio.file.NoSuchFileException: /home/pnguyen/craftercms/support_3.1.x/craftercms/crafter-authoring/data/repos/sites/testing/sandbox/site/website/f2/page2-1
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_292]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_292]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_292]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:1.8.0_292]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:1.8.0_292]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:1.8.0_292]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[?:1.8.0_292]
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72) ~[?:1.8.0_292]
	at java.nio.file.Files.walk(Files.java:3574) ~[?:1.8.0_292]
	at java.nio.file.Files.walk(Files.java:3625) ~[?:1.8.0_292]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.deleteParentFolder(GitContentRepository.java:457) ~[classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.deleteParentFolder(GitContentRepository.java:467) ~[classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.deleteContent(GitContentRepository.java:428) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository$$FastClassBySpringCGLIB$$fd69e59c.invoke(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository$$EnhancerBySpringCGLIB$$9949ff82.deleteContent(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.repository.blob.BlobAwareContentRepository.deleteContent(BlobAwareContentRepository.java:253) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.deleteContent(ContentServiceImpl.java:657) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.deleteContent(ContentServiceImpl.java:643) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$FastClassBySpringCGLIB$$a67efd9f.invoke(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$EnhancerBySpringCGLIB$$3ac3d507.deleteContent(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processItem(PublishingManagerImpl.java:183) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$FastClassBySpringCGLIB$$964b4d9f.invoke(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672) [spring-aop-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$EnhancerBySpringCGLIB$$19628c76.processItem(<generated>) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.processPublishingRequest(StudioPublisherTask.java:323) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:259) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:166) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:80) [classes/:3.1.18-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor$1.run(StudioClockExecutor.java:147) [classes/:3.1.18-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

* `git status` on sandbox:

```
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    site/website/f2/index.xml
	deleted:    site/website/f2/page2/index.xml
	deleted:    site/website/f2/page2/page2-1/index.xml
	deleted:    site/website/f2/page2/page2-1/page2-1-2/.keep
	deleted:    site/website/f2/page2/page2-1/page2-1-2/index.xml
```

#### Screenshots

https://user-images.githubusercontent.com/2996543/132807101-e6cb501b-ef9c-438e-9834-a15e1cc851fb.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2748
https://github.com/craftercms/studio/pull/2749

**Comment by phuongnq** [comment]
verified fixex
