### ISSUE TITLE
[studio][studio-ui] There's an error displaying the "Recently Published" dashlet in the Dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5003]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-3d2b27
Build Number:
3d2b27306409c1289eae4d88c236c0ecf8ec612f
Build Date:
9/16/2021, 9:20 AM

#### Describe the bug
There's an error displaying the "Recently Published" dashlet in the Dashboard with error in the logs `java.time.DateTimeException: Invalid ID for ZoneOffset, invalid format`

#### To Reproduce
1. Create a site using any bp
2. Publish the site
3. Open the dashboard
4. Scroll to the `Recently Published` dashlet and notice the error.  See below for the error message in the logs and a screenshot of the dashboard with the error.

Here's the `site-config.xml` file.  The default config is being used and no changes has been made to the `site-config.xml` file

```
<site-config>
    <version>10</version>
    <wem-project>hi</wem-project>
    <display-name>hi</display-name>

    <!-- Site URLs. Default to http://localhost:8080 if blank -->
    <site-urls>
        <authoring-url></authoring-url>
        <staging-url></staging-url>
        <live-url></live-url>
    </site-urls>

    <locale>
        <!--
        BCP 47 language tag (e.g. en-US) or unicode extension (e.g. "en-US-u-ca-buddhist").
        Leave empty for using the user's browser locale (i.e. dates/times will be displayed in each users's system locale).
        Specifying a locale code will apply those localization settings to *all* users regardless of their system settings
        or location. For example, if "en-US", is specified, all users will see dates as month/day/year instead of day/month/year
        regardless of their system (i.e. OS) locale preference.
        -->
        <localeCode/>
        <!--
        Use `dateTimeFormatOptions` to customize how dates & times get displayed on Studio UI.
        For full list of options and docs, visit: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
        -->
        <dateTimeFormatOptions>
            <!--
            Specifying a time zone (i.e. `timeZone` element) will express dates/times across the UI in the time zone you specify
            here. Leaving it unspecified, will display dates/times to each user in their own system time zone.
            -->
            <!--<timeZone>EST5EDT</timeZone>-->
            <day>numeric</day>
            <month>numeric</month>
            <year>numeric</year>
            <hour>numeric</hour>
            <minute>numeric</minute>
            <!--
            Set `hour12` to "false" to show times in 24 hour format.
            -->
            <hour12>true</hour12>
        </dateTimeFormatOptions>
    </locale>

```

#### Logs
Here's the error message in the logs:
```
[ERROR] 2021-09-16T09:53:16,225 [http-nio-8080-exec-7] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/publish/history.json?ascending=false&days=30&filterType=page&num=20&siteId=another-one&sort=eventDate failed with response: ApiResponse{code=1000, message='Internal system failure', remedialAction='Contact support', documentationUrl=''}
java.time.DateTimeException: Invalid ID for ZoneOffset, invalid format:
	at java.time.ZoneOffset.of(ZoneOffset.java:241) ~[?:?]
	at java.time.ZoneId.of(ZoneId.java:402) ~[?:?]
	at java.time.ZoneId.of(ZoneId.java:356) ~[?:?]
	at org.craftercms.studio.impl.v2.service.publish.PublishServiceImpl.getDeploymentHistory(PublishServiceImpl.java:196) ~[classes/:4.0.0-SNAPSHOT]
```

#### Screenshots
<img width="1452" alt="Screen Shot 2021-09-16 at 9 57 40 AM" src="https://user-images.githubusercontent.com/25483966/133633380-b05422b7-59ae-4c49-b534-165bd736e32d.png">

**Comment by rart** [comment]
@sumerjabri 
- [ ] There's a backend issue here. The UI is not sending any timezone offset here. Something is breaking on the back.
- [ ] The docs should be deterministic/specific on what is supported on `filterType` (see screenshot below, what is the meaning of `...`?)
<img width="448" alt="image" src="https://user-images.githubusercontent.com/3928341/133659384-01165e9c-0f0e-428f-9332-d9c72c0112a8.png">

@jvega190 
- [ ] the UI is sending some additional arguments that API 2 doesn't implement (i.e. `ascending`, `sort`). 
- [ ] `filterType` sent doesn't seem to match what the docs specify. UI is sending for example `filterType=page` instead of `filterType=pages`
<img width="448" alt="image" src="https://user-images.githubusercontent.com/3928341/133659384-01165e9c-0f0e-428f-9332-d9c72c0112a8.png">


I did test with the right set of arguments and the same exception persists.

**Comment by sumerjabri** [comment]
@dejan-brkic let's fix the docs and address the problem with the timezone

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2754

**Comment by sumerjabri** [comment]
@alhambrav please note the new configuration and document it to complete this task. (it's in the YAML file.)
