### ISSUE TITLE
[ecom-bp] commcercetools blueprint has FTL errors on the homescreen

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5185]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/28

#### Describe the bug
ECom BP has FTL errors on the home page.

#### To Reproduce
1. Create a site from `commercetools` blueprint
2. See the errors

#### Logs
```
$FreeMarker template error:
Java method "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl.getCurrencies()" threw an exception when invoked on org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl object "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl@39bb4052"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign currenciesString = '"' + appl...  [in template "templates/web/index.ftl" at line 25, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:292)
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:255)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:78)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
```

```
$FreeMarker template error:
Java method "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl.getLocales()" threw an exception when invoked on org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl object "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl@39bb4052"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign localesString = '"' + applica...  [in template "templates/web/index.ftl" at line 26, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:292)
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:255)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:78)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
```

```
$FreeMarker template error:
Java method "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl.getName()" threw an exception when invoked on org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl object "org.craftercms.sites.ecommerce.service.commercetools.StoreServiceImpl@39bb4052"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign storeSettingsJSON = "\n{\n  n...  [in template "templates/web/index.ftl" at line 27, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:292)
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:255)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:78)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
	at freemarker.core.Expression.eval(Expression.java:101)
```

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/147597673-300fde7f-9078-42f1-91ed-47a89703d52b.png)

**Comment by sumerjabri** [comment]
Verified.
