### ISSUE TITLE
[wordify-bp] Wordify BP has errors in the logs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5187]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/28

#### Describe the bug
Wordify BP produces errors in the logs.

#### To Reproduce
1. Create a  site from Wordify BP
2. See the error in the logs

#### Logs

```
[ERROR] 2021-12-28T15:32:36,756 [http-nio-8080-exec-3] [upgrade.StudioUpgradeManagerImpl] | Error upgrading configuration file /config/engine/proxy-config.xml 
org.craftercms.commons.upgrade.exception.UpgradeNotSupportedException: Current version '2' for '/config/engine/proxy-config.xml @ wordify3' cannot be upgraded automatically, requires '>=3'
	at org.craftercms.commons.upgrade.impl.pipeline.DefaultUpgradePipelineFactoryImpl.getPipeline(DefaultUpgradePipelineFactoryImpl.java:147) ~[crafter-commons-upgrade-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.pipeline.ConfigurationUpgradePipelineFactoryImpl.getPipeline(ConfigurationUpgradePipelineFactoryImpl.java:50) ~[classes/:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.upgradeSiteConfiguration(StudioUpgradeManagerImpl.java:203) [classes/:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.doUpgrade(StudioUpgradeManagerImpl.java:144) [classes/:4.0.0-SNAPSHOT]
	at org.craftercms.commons.upgrade.impl.AbstractUpgradeManager.upgrade(AbstractUpgradeManager.java:63) [crafter-commons-upgrade-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSiteCloneRemote(SiteServiceImpl.java:768) [classes/:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSiteWithRemoteOption(SiteServiceImpl.java:644) [classes/:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$FastClassBySpringCGLIB$$562e9c15.invoke(<generated>) [classes/:4.0.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) [spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) [spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58) [spring-aop-5.3.13.jar:5.3.13]

```

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
Verified fixed.
