### ISSUE TITLE
[deployer] Error while indexing preview target with blob store on custom processor

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5201]
#### Crafter CMS Version
3.1.x

#### Date of Build
Jan 4, 2022

#### Describe the bug
While indexing preview target with blob store, the mapping wrongly picks LIVE environment instead of preview.

#### To Reproduce
1. Create a site with Editorial BP. Ex: test
2. Update blob store configuration as following:

```
<?xml version="1.0" encoding="UTF-8"?>
<blobStores>
  <blobStore>
    <id>s3-store</id>
    <type>s3BlobStore</type>
    <pattern>/static-assets/s3/.*</pattern>
    <mappings>
      <mapping>
        <publishingTarget>preview</publishingTarget>
        <storeTarget>philnguyen-authoring-bucket</storeTarget>
        <prefix>sandbox</prefix>
      </mapping>
      <mapping>
        <publishingTarget>staging</publishingTarget>
        <storeTarget>philnguyen-authoring-bucket</storeTarget>
        <prefix>staging</prefix>
      </mapping>
      <mapping>
        <publishingTarget>live</publishingTarget>
        <storeTarget>philnguyen-authoring-bucket</storeTarget>
        <prefix>published</prefix>
      </mapping>
    </mappings>
    <configuration>
      <credentials>
        <accessKey>{your_access_key}</accessKey>
        <secretKey>{your_secret_key}</secretKey>
      </credentials>
      <region>us-east-1</region>
      <pathStyleAccess>true</pathStyleAccess>
    </configuration>
  </blobStore>
</blobStores>
```

3. Upload a Word file to `/static-assets/s3/`
4. Update 'Article' Page content-type to include File Browse

![2022-01-04_10-33](https://user-images.githubusercontent.com/2996543/148006161-574db8a8-2375-4483-9db2-4a3042f30306.png)

5. Edit an article to include the file from step 3 
![2022-01-04_10-35](https://user-images.githubusercontent.com/2996543/148006223-e4881110-2d93-4080-a111-58f01147105a.png)

6. Update `test-preview.yaml` to use `authoringElasticsearchIndexingProcessor`

```
...
- processorName: authoringElasticsearchIndexingProcessor
...
```

7. Run reindex on preview target:

```
curl "http://localhost:9191/api/1/target/deploy/preview/test" -X POST -H "Content-Type: application/json" -d '{ "reprocess_all_files": true }'
```

8. Check `test-preview.log`, there is an error:

```
java.io.FileNotFoundException: S3Resource{profile=S3Profile{profileId='s3-store', region='us-east-1', endpoint='null', bucketName='null', pathStyleAccessEnabled=true}, key='published/static-assets/s3/copy-word-demo.docx'} not found
	at org.craftercms.commons.spring.resources.S3Resource.getInputStream(S3Resource.java:132)
	at org.craftercms.core.service.impl.ResourceBasedContent.getInputStream(ResourceBasedContent.java:61)
	at org.craftercms.search.service.utils.ContentResource.getInputStream(ContentResource.java:66)
	at org.craftercms.search.elasticsearch.impl.tika.TikaDocumentParser.parseToXml(TikaDocumentParser.java:103)
	at org.craftercms.search.elasticsearch.impl.ElasticsearchServiceImpl.indexBinary(ElasticsearchServiceImpl.java:235)
	at org.craftercms.search.elasticsearch.batch.ElasticsearchIndexingUtils.doUpdateBinary(ElasticsearchIndexingUtils.java:77)
	at org.craftercms.search.elasticsearch.batch.ElasticsearchBinaryFileWithMetadataBatchIndexer.doUpdateContent(ElasticsearchBinaryFileWithMetadataBatchIndexer.java:111)
	at org.craftercms.search.elasticsearch.batch.ElasticsearchBinaryFileWithMetadataBatchIndexer.doUpdateContent(ElasticsearchBinaryFileWithMetadataBatchIndexer.java:52)
	at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.updateBinaryWithMetadata(AbstractBinaryFileWithMetadataBatchIndexer.java:378)
	at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.doUpdates(AbstractBinaryFileWithMetadataBatchIndexer.java:203)
	at org.craftercms.search.batch.impl.AbstractBinaryFileWithMetadataBatchIndexer.updateIndex(AbstractBinaryFileWithMetadataBatchIndexer.java:161)
	at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.doMainProcess(AbstractSearchIndexingProcessor.java:294)
	at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.doExecute(AbstractMainDeploymentProcessor.java:57)
	at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:148)
	at org.craftercms.deployer.impl.processors.AbstractSearchIndexingProcessor.execute(AbstractSearchIndexingProcessor.java:205)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:81)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:67)
	at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:423)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Notice that in `key` parameter, `published` prefix which is from mapping for `live` is used. For preview target, mapping for `preview` should be used instead.

**Comment by phuongnq** [comment]
verified
