### ISSUE TITLE
[craftercms] Upgrade 3.0.x to 3.1.x: post-upgrade is not able to run the delete of Solr targets

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5252]
#### Crafter CMS Version
3.0.28 to 3.1.18
#### Date of Build
` 01-18-2022`
#### Describe the bug
When running the `post-upgrade.sh` script, the step related to recreate the Solr index is failing because the script is not sending the management token for the `crafter-search` API. 

#### To Reproduce
1. Do an upgrade from 3.0.28 to 3.1.18
3. See the error running the `post-upgrade.sh`

#### Logs
```
Please make sure Crafter has started successfully before continuing
> Continue? [(Y)es/(N)o]: Yes
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Creating Authoring Deployer Targets
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Authoring target for site 'empty' created successfully
Authoring target for site 'editorial' created successfully
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Re-creating Solr cores for sites
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING: This will delete the current Solr site cores, recreate them, and trigger a content 
re-index to re-populate them. This is necessary because of a major Solr upgrade. Don't proceed 
if you can't have any search downtime.
> Proceed? [(Y)es/(N)o]: Yes
Caught: upgrade.exceptions.UpgradeException: Error while deleting Solr core 'empty': Required string parameter 'token' is not present
upgrade.exceptions.UpgradeException: Error while deleting Solr core 'empty': Required string parameter 'token' is not present
        at upgrade.hooks.v30.RecreateSolrCoresHook$_deleteCore_closure3$_closure8.doCall(RecreateSolrCoresHook.groovy:82)
        at groovyx.net.http.fn.ClosureBiFunction.apply(ClosureBiFunction.java:45)
        at groovyx.net.http.HttpBuilder$ResponseHandlerFunction.apply(HttpBuilder.java:2305)
        at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$2(JavaHttpBuilder.java:168)
        at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:331)
        at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:122)
        at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:374)
        at groovyx.net.http.JavaHttpBuilder.doPost(JavaHttpBuilder.java:389)
        at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:47)
        at groovyx.net.http.HttpBuilder.post(HttpBuilder.java:732)
        at groovyx.net.http.HttpBuilder.post(HttpBuilder.java:1391)
        at groovyx.net.http.HttpBuilder$post$0.call(Unknown Source)
        at upgrade.hooks.v30.RecreateSolrCoresHook.deleteCore(RecreateSolrCoresHook.groovy:75)
        at upgrade.hooks.v30.RecreateSolrCoresHook.recreateCore(RecreateSolrCoresHook.groovy:64)
        at upgrade.hooks.v30.RecreateSolrCoresHook$_execute_closure1$_closure6.doCall(RecreateSolrCoresHook.groovy:51)
        at upgrade.hooks.v30.RecreateSolrCoresHook$_execute_closure1.doCall(RecreateSolrCoresHook.groovy:49)
        at upgrade.hooks.v30.RecreateSolrCoresHook.execute(RecreateSolrCoresHook.groovy:48)
        at upgrade.hooks.PostUpgradeHook$execute.call(Unknown Source)
        at upgrade.hooks.PostUpgradeHook$execute.call(Unknown Source)
        at upgrade.hooks.PostUpgradeHooks$_execute_closure1.doCall(PostUpgradeHooks.groovy:73)
        at upgrade.hooks.PostUpgradeHooks.execute(PostUpgradeHooks.groovy:72)
        at upgrade.hooks.PostUpgradeHooks$execute.call(Unknown Source)
        at upgrade.post-upgrade.postUpgrade(post-upgrade.groovy:71)
        at upgrade.post-upgrade$postUpgrade$0.callCurrent(Unknown Source)
        at upgrade.post-upgrade.run(post-upgrade.groovy:94)
```
#### Screenshots
N/A

**Comment by jdrossl** [comment]
@sumerjabri @yacdaniel this does not apply to 4.0

**Comment by yacdaniel** [comment]
Verified fixed.
