### ISSUE TITLE
[deployer] Deployer fails with NoClassDefFoundError for JschConfigSessionFactory when performing Git actions via SSH

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5336]
#### Crafter CMS Version
3.1.21

#### Date of Build
n/a

#### Describe the bug
Deployer is missing the following dependencies 

1. https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.ssh.jsch/5.13.0.202109080827-r/org.eclipse.jgit.ssh.jsch-5.13.0.202109080827-r.jar
2. https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.55/jsch-0.1.55.jar
3. https://repo1.maven.org/maven2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar 

#### To Reproduce
1. Create an SSH based target
2. Wait for pull/clone operation
3.  See the error

#### Logs
```
2022-02-16 00:01:22.473  INFO 17 --- [deployment-1] org.craftercms.deployer.impl.TargetImpl  : Creating deployment pipeline for target 'ASITE-default'
Exception in thread "deployment-1" java.lang.NoClassDefFoundError: org/eclipse/jgit/transport/JschConfigSessionFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.craftercms.deployer.impl.processors.git.AbstractRemoteGitRepoAwareProcessor.createAuthenticationConfigurator(AbstractRemoteGitRepoAwareProcessor.java:123)
	at org.craftercms.deployer.impl.processors.git.AbstractRemoteGitRepoAwareProcessor.doInit(AbstractRemoteGitRepoAwareProcessor.java:91)
	at org.craftercms.deployer.impl.processors.git.GitPullProcessor.doInit(GitPullProcessor.java:73)
	at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.init(AbstractDeploymentProcessor.java:123)
	at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.init(AbstractMainDeploymentProcessor.java:44)
	at org.craftercms.deployer.impl.DeploymentPipelineFactoryImpl.getPipeline(DeploymentPipelineFactoryImpl.java:62)
	at org.craftercms.deployer.impl.TargetImpl.init(TargetImpl.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.transport.JschConfigSessionFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 22 more

```

#### Screenshots
N/A

**Comment by jdrossl** [comment]
4.0 doesn't have the same issue

**Comment by russdanner** [comment]
Confirmed.
