### ISSUE TITLE
[studio-ui] Not able to view the first item history for configuration files. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5429]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-7a168d`

#### Date of Build
`3/31/2022`

#### Describe the bug
When an user from `system_admin` groups goes to `Project Tools` -> `Configuration`, edit a config file and picks the first item to see it fails.

#### To Reproduce
1. Go to `Project Tools` -> `Configuration`
2. Edit any config file
3. Click `History`, select the first version and click the `View` option
4. History of specific file is not displayed. 
5. If user picks an older versions, the result is not displaying probably because the API is taking a lot to response (https://github.com/craftercms/craftercms/issues/5426) 

#### Logs
```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'availableActions')
    at N (PreviewDialogContainer.tsx:105:31)
    at ui (react-dom.production.min.js:157:137)
    at $u (react-dom.production.min.js:267:460)
    at Tc (react-dom.production.min.js:250:347)
    at wc (react-dom.production.min.js:250:278)
    at Sc (react-dom.production.min.js:250:138)
    at yc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
```
#### Screenshots

https://user-images.githubusercontent.com/6722074/161331181-36d89e29-93cc-438e-a560-0fefc781b7ec.mp4

**Comment by yacdaniel** [comment]
Verified fixed.
