### ISSUE TITLE
[studio-ui] XB Panel - Search not working

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5483]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-60dbd0`
#### Date of Build
`4/12/2022`
#### Describe the bug
Search widget in Experience Builder not working. 
#### To Reproduce
1. Open the Search widget in the Experience Builder Panel
2. See the error

#### Logs
```
TypeError: Cannot read properties of null (reading 'firstName')
    at g (string.ts:85:19)
    at v (DraggablePanelListItem.tsx:75:48)
    at ui (react-dom.production.min.js:157:137)
    at $u (react-dom.production.min.js:267:460)
    at Tc (react-dom.production.min.js:250:347)
    at wc (react-dom.production.min.js:250:278)
    at Sc (react-dom.production.min.js:250:138)
    at yc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```    
#### Screenshots
![image](https://user-images.githubusercontent.com/6722074/163001478-a3c86e1b-7a43-4a1d-9530-c7d75b26e3e3.png)

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/163835394-76c0ecbd-ef0f-4b2f-9eec-f913ea7e78d9.png)
