### ISSUE TITLE
[studio-ui] Edit in UI Editor, then minimize and change site throws error

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5551]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-da6e57`

#### Date of Build
`4/25/2022`

#### Describe the bug
If you use the UI Editor to change the content of a document (.ftl, .groovy, .txt ...), then minimize and change to another site, and error will show up: `Cannot read properties of null (reading 'craftercms.freemarkerCodeSnippets')`

Also, the content will stay locked upon refreshing. It is important to notice that the effects when refreshing may vary. 

#### To Reproduce
1. Go to any site of your choosing.
2. Click on `Edit` on an .ftl file, .groovy file or any other content that opens a UI editor.
3. Add a line, cut content or edit anything on it.
4. `Minimize` the UI Editor.
5. Change site.
6. See the error

#### Logs
The browser dev tool console, shows the next error:
```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'craftercms.freemarkerCodeSnippets')
    at U (CodeEditorDialogContainer.tsx:73:3)
    at ui (react-dom.production.min.js:157:137)
    at Ui (react-dom.production.min.js:180:154)
    at $u (react-dom.production.min.js:269:343)
    at Tc (react-dom.production.min.js:250:347)
    at wc (react-dom.production.min.js:250:278)
    at Sc (react-dom.production.min.js:250:138)
    at yc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/165158660-2fdcb499-18ea-440b-9888-c370a4e7f7a1.mp4

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now. Thank you! Closing this ticket.

**Comment by Euquimides** [comment]
Hi @rart ! Related with this issue, when you upload various files, minimize the window and then change sites, the minimized Upload windows will stay through sites. Please, take a look at it. 

https://user-images.githubusercontent.com/90878288/166554000-76cc6632-d179-42bf-9203-a917148c1e8b.mp4

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue, it is fixed. Thank you! Closing this ticket.
