### ISSUE TITLE
[studio-ui] Error when leaving only one configuration file in `Project Tools` -> `Configuration` -> `Configurations`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5582]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-345d8a`

#### Date of Build
`5/4/2022`

#### Describe the bug
If you leave only one configuration file inside `Project Tools` -> `Configuration` -> `Configurations`, a bug will appear that might be related with xml serializer. It freezes the UI in that section. 

#### To Reproduce
1. Go to any site of your choosing. 
2. Go to `Project Tools` -> `Configuration` -> `Configurations`
3. On `Configurations` delete all files, leaving only one. 
4. Refresh your browser. 
5. See the error

#### Logs
When you check the browser's dev tools console, the following error will show up:
```
reportUnhandledError.ts:21 Uncaught TypeError: e.map is not a function
    at SiteConfigurationManagement.tsx:152:24
    at Object.next (Subscriber.ts:194:14)
    at t._next (Subscriber.ts:119:22)
    at t.next (Subscriber.ts:75:12)
    at map.ts:56:20
    at t.i._next (OperatorSubscriber.ts:43:13)
    at t.next (Subscriber.ts:75:12)
    at map.ts:56:20
    at t.i._next (OperatorSubscriber.ts:43:13)
    at t.next (Subscriber.ts:75:12)
``` 

#### Screenshots

https://user-images.githubusercontent.com/90878288/166745171-3df9ffbd-2b6d-4333-a584-81c8e33d36fc.mp4

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
