### ISSUE TITLE
[studio-ui] Top navigation bar is disabled with an empty field ending _o

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5608]
#### Crafter CMS Version
4.0.1-SNAPSHOT-02a7a6

#### Date of Build
May 26, 2022

#### Describe the bug
A field ending with `_o` with no value makes the top navigation bar disabled with an error in the console.

#### To Reproduce
1. Create a new site with Editorial BP
2. Open an article and make sure that the top navigation bar is enabled
3. Update `Ariticle` content type to have *Minimum Selection* 0
4. Update the article in step 2 and uncheck the Categories metadata
5. Save and notice that the navigation bar is now disabled with an error in the console log

#### Logs
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at I (content.ts:691:10)
    at content.ts:701:55
    at Array.map (<anonymous>)
    at content.ts:701:41
    at Array.forEach (<anonymous>)
    at I (content.ts:691:25)
    at content.ts:684:18
    at Array.forEach (<anonymous>)
    at L (content.ts:683:26)
```

This caused by an end closing tag in XML:

```
<categories_o/>
```

#### Screenshots
![2022-05-26_11-04](https://user-images.githubusercontent.com/2996543/170414019-25040ed6-aeb3-47e0-8e17-914c63171816.png)
![2022-05-26_11-06](https://user-images.githubusercontent.com/2996543/170414030-333fbd72-17ba-4191-952f-373433436b50.png)

**Comment by phuongnq** [comment]
Verified.
