### ISSUE TITLE
[studio] Disallow `SVG` files by default in the policy engine

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5609]
Please update the default policy engine to disallow `SVG` files

This is related to #5569 

This will probably require updates to:
- Sample
- Built-in BPs
- Marketplace BPs

**Comment by sumerjabri** [comment]
Updated all blueprints to have the same policy by default. Blueprints have been marked as compatible with 4.0.1+ moving forward to leverage the new feature.

**Comment by yacdaniel** [comment]
@rart  the `Preview Image` for a Content Types does a Policy Validation, but seems that the dialog that shows the error is freezing Studio UI.
Steps: Upload an SVG file in the `Preview Image` of a Content Type, accept the dialog. 
```
Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
    at oe (SingleFileUpload.tsx:276:28)
    at Object.Ne (react-dom.production.min.js:54:317)
    at je (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Ir (react-dom.production.min.js:105:68)
    at Br (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at sc (react-dom.production.min.js:273:42)
    at Pe (react-dom.production.min.js:52:375)
    at Ur (react-dom.production.min.js:109:469)
```
https://user-images.githubusercontent.com/6722074/172709769-fee62519-66ec-4580-a885-c6abc7e558ed.mp4
