### ISSUE TITLE
[studio-ui] Audit Log shows error in UI when clicking on empty space in `Timestamp` tab 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5619]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-221e57`

#### Date of Build
`6/3/2022`

#### Describe the bug
In `Audit` log when clicking on on an empty space inside the `Timestamp` tab, an error will show up in the UI. 

#### To Reproduce
1. Go to 'Audit' log either in `User Dashboard` or in `Project Tools` inside any project. 
2. Click on the empty space right beside the down arrow in 'Timestamp'
3. See the error

#### Logs
The browser console will show the following errors:
```
react-dom.production.min.js:186 TypeError: Cannot set properties of null (setting 'scrollLeft')
    at GridColumnHeaderItem.js:162:63
    at es (react-dom.production.min.js:242:332)
    at vs (react-dom.production.min.js:262:100)
    at gs (react-dom.production.min.js:258:318)
    at gs (react-dom.production.min.js:258:343)
    at gs (react-dom.production.min.js:258:343)
    at hs (react-dom.production.min.js:257:421)
    at react-dom.production.min.js:282:96
    at Dc (react-dom.production.min.js:280:398)
    at rc (react-dom.production.min.js:269:269)
uu @ react-dom.production.min.js:186
```
```
useGridLoggerFactory.js:26 MUI: GridErrorHandler - An unexpected error occurred. Error: Cannot set properties of null (setting 'scrollLeft').  TypeError: Cannot set properties of null (setting 'scrollLeft')
    at GridColumnHeaderItem.js:162:63
    at es (react-dom.production.min.js:242:332)
    at vs (react-dom.production.min.js:262:100)
    at gs (react-dom.production.min.js:258:318)
    at gs (react-dom.production.min.js:258:343)
    at gs (react-dom.production.min.js:258:343)
    at hs (react-dom.production.min.js:257:421)
    at react-dom.production.min.js:282:96
    at Dc (react-dom.production.min.js:280:398)
    at rc (react-dom.production.min.js:269:269) undefined
nu.reduce.u.<computed> @ useGridLoggerFactory.js:26
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/171915196-749182c8-1b69-4e54-a253-34de46de2af2.mp4

![audit_timestamp_edited](https://user-images.githubusercontent.com/90878288/171915299-6b81ac91-1ed0-46a3-8621-6385851f02c5.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
