### ISSUE TITLE
[studio] Error with content expiring email notifications 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5620]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-221e57`

#### Date of Build
`6/6/2022`

#### Describe the bug
When setting content for expiration, no email notification will be sent, since there is an error when executing the content monitoring script. 

#### To Reproduce
1. Go to any project of your choice, can be one based on Editorial BP. 
2. Go to `Project Tools` -> `Content Types` and edit an `Article` (for example) content type to add a field `expired_dt`. 
3. Edit the `Article` to add the date of expiration. 
4. See the error

#### Logs
The tomcat log `catalina.out`, will show the following error when sending a notification:
```
[INFO] 2022-06-06T12:00:00,413 [pool-14-thread-9] [impl.GroovyScript] | content monitor: Content Expiring Tomorrow Sending notification (contentExpiringSoon) 
[INFO] 2022-06-06T12:00:00,436 [pool-14-thread-9] [core.JobRunShell] | Job DEFAULT.craftercms:/scripts/jobs/every-day/content-monitoring.groovy threw a JobExecutionException:  
org.quartz.JobExecutionException: Error executing script job at /scripts/jobs/every-day/content-monitoring.groovy
	at org.craftercms.engine.scripting.impl.ScriptJob.execute(ScriptJob.java:63) ~[classes/:4.0.1-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.craftercms.engine.exception.ScriptException: No signature of method: org.craftercms.studio.impl.v2.service.notification.NotificationServiceImpl$$EnhancerBySpringCGLIB$$58b79127.notify() is applicable for argument types: (String, ArrayList, String, Locale, org.apache.commons.lang3.tuple.ImmutablePair...) values: [a1, [admin@example.com], contentExpiringSoon, en, (monitorName,Content Expiring Tomorrow), ...]
Possible solutions: notify(), notifyAll(), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:74) ~[classes/:4.0.1-SNAPSHOT]
	at org.craftercms.engine.scripting.impl.ScriptJob.execute(ScriptJob.java:61) ~[classes/:4.0.1-SNAPSHOT]
	... 4 more
Caused by: groovy.lang.MissingMethodException: No signature of method: org.craftercms.studio.impl.v2.service.notification.NotificationServiceImpl$$EnhancerBySpringCGLIB$$58b79127.notify() is applicable for argument types: (String, ArrayList, String, Locale, org.apache.commons.lang3.tuple.ImmutablePair...) values: [a1, [admin@example.com], contentExpiringSoon, en, (monitorName,Content Expiring Tomorrow), ...]
Possible solutions: notify(), notifyAll(), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.ContentMonitoring$_doContentMonitoringForSite_closure2$_closure3.doCall(ContentMonitoring.groovy:121) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.ContentMonitoring$_doContentMonitoringForSite_closure2.doCall(ContentMonitoring.groovy:92) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.ContentMonitoring.doContentMonitoringForSite(ContentMonitoring.groovy:70) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.ContentMonitoring$_doMonitoringForAllSites_closure1.doCall(ContentMonitoring.groovy:38) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.10.jar:3.0.10]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2396) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.dgm$204.invoke(Unknown Source) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.ContentMonitoring.doMonitoringForAllSites(ContentMonitoring.groovy:35) ~[?:?]
	at scripts.api.impl.content.ContentMonitoring$doMonitoringForAllSites.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.10.jar:3.0.10]
	at content-monitoring.run(content-monitoring.groovy:19) ~[?:?]
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:72) ~[classes/:4.0.1-SNAPSHOT]
	at org.craftercms.engine.scripting.impl.ScriptJob.execute(ScriptJob.java:61) ~[classes/:4.0.1-SNAPSHOT]
	... 4 more
```
Also, when calling the monitor-content API `http://localhost:8080/studio/api/1/services/api/1/site/monitor-content.json`, you will get the following response:
```
{
    "message": "No signature of method: org.craftercms.studio.impl.v2.service.notification.NotificationServiceImpl$$EnhancerBySpringCGLIB$$58b79127.notify() is applicable for argument types: (String, ArrayList, String, Locale, org.apache.commons.lang3.tuple.ImmutablePair...) values: [a1, [admin@example.com], contentExpiringSoon, en, (monitorName,Content Expiring Tomorrow), ...]\nPossible solutions: notify(), notifyAll(), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;), notify(java.lang.String, java.util.List, java.lang.String, [Lorg.apache.commons.lang3.tuple.Pair;)"
}
```

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
CC @phuongnq @avasquez614
