### ISSUE TITLE
[studio-ui] Approve a pending publish request failed with a blank page

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5631]
#### Crafter CMS Version
4.0.1-SNAPSHOT-528e4b

#### Date of Build
6/10/2022, 12:36 PM

#### Describe the bug

When approving a pending publish request, the UI failed with a blank page

#### To Reproduce
1. Create a site from Editorial BP
2. Do an initial publish 
3. Edit a page
4. Create a publish request for the page in step 3
5. Open `Dashboard` and notice the page is in *Items Waiting For Approval* list
6. Select the item in step 5 and publish it
7. Notice that the page goes blank and the item is not published

#### Logs

There is an error in the backend:

```
[ERROR] 2022-06-10T13:13:52,692 [Thread-2] [job.EmailMessageSender] | Error sending email notification to: 
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused). Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:378) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:366) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.craftercms.studio.impl.v1.job.EmailMessageSender.sendEmail(EmailMessageSender.java:117) ~[classes/:4.0.1-SNAPSHOT]
	at org.craftercms.studio.impl.v1.job.EmailMessageSender.run(EmailMessageSender.java:72) ~[classes/:4.0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Service.connect(Service.java:366) ~[javax.mail-1.6.2.jar:1.6.2]
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437) ~[spring-context-support-5.3.18.jar:5.3.18]
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at java.net.Socket.connect(Socket.java:558) ~[?:?]
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:359) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Service.connect(Service.java:366) ~[javax.mail-1.6.2.jar:1.6.2]
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518) ~[spring-context-support-5.3.18.jar:5.3.18]
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437) ~[spring-context-support-5.3.18.jar:5.3.18]
	... 6 more
```

#### Screenshots

![2022-06-10_13-18](https://user-images.githubusercontent.com/2996543/173002937-160667e7-bded-45c3-9d1f-10eee63cdf2b.png)

![2022-06-10_13-15](https://user-images.githubusercontent.com/2996543/173002399-f18eed38-49ac-4282-b904-1dd5e98457f9.png)

**Comment by phuongnq** [comment]
Verified. Thank you!
