### ISSUE TITLE
[studio-ui] UI error when opening `Project Tools` -> `GraphQL` for the first time after creating a site

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5637]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-cde410`

#### Date of Build
`6/14/2022`

#### Describe the bug
After creating a site, if you go to `Project Tools` -> `GraphQL` a UI error will show up, that will affect all other options in the `Project Tools` window. 

#### To Reproduce
1. Create a new project or site.
2. Go to `Project Tools`
3. Go to `GraphQL`
4. See the error

#### Logs
The browser's console will show the following error:
```
react-dom.production.min.js:186 TypeError: Cannot read properties of null (reading 'split')
    at He (codemirror.es.js:711:21)
    at e.splitLines (codemirror.es.js:6720:16)
    at e.<anonymous> (codemirror.es.js:6260:22)
    at e.setValue (codemirror.es.js:4160:20)
    at Es.setValue (codemirror.es.js:10501:27)
    at index.es.js:10070:14
    at es (react-dom.production.min.js:242:332)
    at Cc (react-dom.production.min.js:285:111)
    at react-dom.production.min.js:281:391
    at M (scheduler.production.min.js:13:203)
``` 

#### Screenshots
![Screenshot from 2022-06-14 09-19-49](https://user-images.githubusercontent.com/90878288/173614727-cfcbe9ff-8094-4c44-a4be-285435f99267.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It has been fixed. Thank you! Closing this ticket.
