### ISSUE TITLE
[studio-ui] Certain file types not being handled by UI, empty screen when opening them from `Item History` -> `View`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5653]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Certain file types, like .woff, .woff2 files, .ttf, and .eot, are not being handled well by the UI when you explore dependencies following a tree approach (dependency of dependency). And empty screen will show up when opening this file types in `Item History` -> `View`.

### Steps to reproduce

Steps:

1. Create an Editorial site. 
2. Click on `Health` page. 
3. Right-click select `Dependencies`.
4. Select `Dependencies of selected item`
5. On `category-landing.ftl` select `Dependencies`
6. On `head.ftl` select `Dependencies`
7. On `font-awesome.min.css` select Dependencies`
8. On `fa-brands-400.woff2` select `History` then select `View`
9. See issue

### Relevant log output

```shell
TypeError: e.match is not a function
    at a.$detectNewLine (ace.js:1:114425)
    at a.insert (ace.js:1:116171)
    at a.setValue (ace.js:1:114063)
    at w.setValue (ace.js:1:209779)
    at AceEditor.tsx:344:11
    at es (react-dom.production.min.js:242:332)
    at Cc (react-dom.production.min.js:285:111)
    at react-dom.production.min.js:281:391
    at M (scheduler.production.min.js:13:203)
    at MessagePort.x (scheduler.production.min.js:14:128)
uu @ react-dom.production.min.js:186
t.callback @ react-dom.production.min.js:187
co @ react-dom.production.min.js:137
bs @ react-dom.production.min.js:260
gs @ react-dom.production.min.js:258
hs @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:282
Dc @ react-dom.production.min.js:280
uc @ react-dom.production.min.js:272
Wi @ react-dom.production.min.js:127
Cc @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
M @ scheduler.production.min.js:13
x @ scheduler.production.min.js:14
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/175366893-7d0f35a1-1b2a-4a12-94f6-ae6aa84d8d46.mp4

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
