### ISSUE TITLE
[studio] Add a get-loggers API v2 REST API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5717]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The logging levels screen on the main menu:
![image](https://user-images.githubusercontent.com/3931908/183504482-3fa830cc-8eeb-4078-a202-5a1e58938d45.png)

Is based on the API `/studio/api/1/services/api/1/server/get-loggers.json` which has been removed along with the old logging system by the PR https://github.com/craftercms/studio/pull/3064

An API returns the list of loggers to the UI is still needed to power that experience.

Please create a v2 API that returns the list of loggers along with the levels. See this code for how it was done: https://github.com/craftercms/studio/pull/3064/files#diff-0c9d02c94c2392f26c4bd5ee05e42330ef7b33628d574224eece40bc84aea598

### Steps to reproduce

Steps:

1. Go to the main menu
2. Click on Logging Levels
3. See the logs

### Relevant log output

```shell
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.59]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.io.FileNotFoundException: No content found at '/scripts/rest/api/1/server/get-loggers.get.groovy' in content store
	at org.craftercms.engine.util.url.ContentStoreUrlStreamHandler.openConnection(ContentStoreUrlStreamHandler.java:61) ~[classes/:4.0.2-SNAPSHOT]
	at java.net.URL.openConnection(URL.java:1099) ~[?:?]
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/3931908/183504482-3fa830cc-8eeb-4078-a202-5a1e58938d45.png)

**Comment by sumerjabri** [comment]
@rart please switch to using the new API

@Euquimides please automate testing the new API

CC @yacdaniel
