### ISSUE TITLE
[studio] Publishing of new items is breaking publisher

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5732]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

After initial publish, if you create a new item and then publish it, the publisher will fail and get disabled. The same happens when approving a new item requested for publishing. You can bypass the issue by cancelling the publishing package and then restarting the publisher, but the item will get the modified state. 

### Steps to reproduce

Steps:

1. Create a new site. 
2. Do an initial publish.
3. Create a new item. 
4. Publish that new item. 
5. See issue

### Relevant log output

```shell
[INFO] 2022-08-17T12:39:47,690 [studio.clockTaskExecutor-34] [job.StudioPublisherTask] | Publish started in site 'test' for target 'live' with '1' items ready to be published 
[INFO] 2022-08-17T12:39:47,696 [studio.clockTaskExecutor-34] [job.StudioPublisherTask] | Publish '1' items in site 'test' to target 'live' 
[ERROR] 2022-08-17T12:39:47,705 [studio.clockTaskExecutor-34] [job.StudioPublisherTask] | Failed to publish items from site 'test' to target 'live' 
org.craftercms.commons.security.exception.PermissionException: Permission evaluation failed
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:146) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:95) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v2.service.dependency.DependencyServiceImpl$$EnhancerBySpringCGLIB$$e9d2569a.getHardDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:227) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:221) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processMandatoryDependencies(PublishingManagerImpl.java:369) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$FastClassBySpringCGLIB$$964b4d9f.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$EnhancerBySpringCGLIB$$c134576e.processMandatoryDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.processPublishingRequest(StudioPublisherTask.java:296) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:236) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:152) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:69) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:121) ~[classes/:4.0.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.craftercms.commons.security.exception.SubjectNotFoundException: Current subject was not found
	at org.craftercms.commons.security.permissions.impl.PermissionEvaluatorImpl.isAllowed(PermissionEvaluatorImpl.java:57) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:144) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	... 35 more
[ERROR] 2022-08-17T12:39:47,736 [studio.clockTaskExecutor-34] [job.StudioPublisherTask] | Failed to publish '1' items in site 'test' 
org.craftercms.commons.security.exception.PermissionException: Permission evaluation failed
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:146) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:95) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v2.service.dependency.DependencyServiceImpl$$EnhancerBySpringCGLIB$$e9d2569a.getHardDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:227) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:221) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processMandatoryDependencies(PublishingManagerImpl.java:369) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$FastClassBySpringCGLIB$$964b4d9f.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$EnhancerBySpringCGLIB$$c134576e.processMandatoryDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.processPublishingRequest(StudioPublisherTask.java:296) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:236) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:152) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:69) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:121) ~[classes/:4.0.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.craftercms.commons.security.exception.SubjectNotFoundException: Current subject was not found
	at org.craftercms.commons.security.permissions.impl.PermissionEvaluatorImpl.isAllowed(PermissionEvaluatorImpl.java:57) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:144) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	... 35 more
[ERROR] 2022-08-17T12:39:47,739 [studio.clockTaskExecutor-34] [job.StudioPublisherTask] | Failed to publish items in site 'test' 
org.craftercms.commons.security.exception.PermissionException: Permission evaluation failed
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:146) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:95) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v2.service.dependency.DependencyServiceImpl$$EnhancerBySpringCGLIB$$e9d2569a.getHardDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:227) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.getPublishingDependencies(DependencyServiceImpl.java:221) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processMandatoryDependencies(PublishingManagerImpl.java:369) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$FastClassBySpringCGLIB$$964b4d9f.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl$$EnhancerBySpringCGLIB$$c134576e.processMandatoryDependencies(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.processPublishingRequest(StudioPublisherTask.java:296) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:236) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:152) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:69) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:121) ~[classes/:4.0.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.craftercms.commons.security.exception.SubjectNotFoundException: Current subject was not found
	at org.craftercms.commons.security.permissions.impl.PermissionEvaluatorImpl.isAllowed(PermissionEvaluatorImpl.java:57) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at org.craftercms.commons.security.permissions.annotations.HasPermissionAnnotationHandler.checkPermissions(HasPermissionAnnotationHandler.java:144) ~[crafter-commons-security-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	... 35 more
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/185221988-050eafc0-89f2-4981-82dd-cfdd57252759.mp4

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The publisher isn't failing anymore when creating new items, so it is validated. Thank you! Closing this ticket.
