### ISSUE TITLE
[studio] Copying a page results in an NPE

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5746]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Copying a page results in an NPE

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Copy a page and paste it under home
3. See the issue in the logs

### Relevant log output

```shell
[ERROR] 2022-08-24T09:06:36,167 [http-nio-8080-exec-7] [content.DmPageNavigationOrderServiceImpl] | Failed to get the new NavOrder for site 'editorial101' path '/site/website/entertainment-copy-1' 
java.lang.NullPointerException: null
	at org.craftercms.studio.impl.v1.service.content.DmPageNavigationOrderServiceImpl.getNewNavOrder(DmPageNavigationOrderServiceImpl.java:88) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.DmPageNavigationOrderServiceImpl.getNewNavOrder(DmPageNavigationOrderServiceImpl.java:65) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.DmPageNavigationOrderServiceImpl.addNavOrder(DmPageNavigationOrderServiceImpl.java:130) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.DmPageNavigationOrderServiceImpl$$FastClassBySpringCGLIB$$ce599d76.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.impl.v1.service.content.DmPageNavigationOrderServiceImpl$$EnhancerBySpringCGLIB$$701fcb75.addNavOrder(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.content.pipeline.FormNavOrderProcessor.process(FormNavOrderProcessor.java:55) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.content.pipeline.ContentProcessorPipelineImpl.processContent(ContentProcessorPipelineImpl.java:51) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.executor.ProcessContentExecutorImpl.processContent(ProcessContentExecutorImpl.java:62) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.processContent(ContentServiceImpl.java:2267) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.copyContent(ContentServiceImpl.java:880) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.copyContent(ContentServiceImpl.java:768) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$FastClassBySpringCGLIB$$a67efd9f.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.craftercms.studio.api.v2.annotation.policy.SitePolicyAspect.validateAction(SitePolicyAspect.java:137) ~[classes/:4.0.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.22.jar:5.3.22]
```

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
