### ISSUE TITLE
[studio] Page URL is not editable with content-as-folder configuration has 'false' value

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5784]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

If `content-as-folder` configuration has `false` value, we don't create a new folder for each content. In that case, editing a page URL throws an error as the parent folder exists.

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Edit `Article` content-type `config.xml` to have `content-as-folder` is `false`
3. Create a new article under `/site/website/articles` folder. Ex: `test.xml`
4. Edit the article in step (3) to update the URL.
5. Notice that URL is not editable and there is an error that the `/site/website/articles` folder exists
the 

### Relevant log output

```
Caused by: org.craftercms.studio.api.v1.exception.ServiceLayerException: Content /site/website/articles/test.xml can't be renamed because target path /site/website/articles already exists
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.writeContentAndRename(ContentServiceImpl.java:482) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$FastClassBySpringCGLIB$$a67efd9f.invoke(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.craftercms.studio.api.v2.annotation.policy.SitePolicyAspect.validateAction(SitePolicyAspect.java:137) ~[classes/:4.0.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.21.jar:5.3.21]
	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl$$EnhancerBySpringCGLIB$$dcdfca20.writeContentAndRename(<generated>) ~[classes/:4.0.2-SNAPSHOT]
	at org.craftercms.studio.api.v1.service.content.ContentService$writeContentAndRename$6.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.impl.content.SpringContentServices.writeContentAndRename(SpringContentServices.groovy:203) ~[?:?]
	at scripts.api.impl.content.SpringContentServices$writeContentAndRename$11.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at scripts.api.ContentServices.writeContentAndRename(ContentServices.groovy:254) ~[?:?]
	at scripts.api.ContentServices$writeContentAndRename$13.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar:3.0.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar:3.0.10]
	at write-content_post.run(write-content.post.groovy:145) ~[?:?]
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:72) ~[classes/:4.0.2-SNAPSHOT]
	... 123 more
```

### Screenshots and/or videos

![2022-09-13_08-55](https://user-images.githubusercontent.com/2996543/189791271-373e107e-81f5-443f-9f27-352e7ab9cdac.png)

![2022-09-13_09-06](https://user-images.githubusercontent.com/2996543/189791777-aaecc09d-9853-4d24-a30c-3490b3505541.png)
![v4](https://user-images.githubusercontent.com/2996543/189791787-bf369e0c-badb-47d9-a3ed-6e33b83038ad.png)

**Comment by phuongnq** [comment]
verified
