### ISSUE TITLE
[3.1] [studio] NullPointerException while running UM on start-up

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5893]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

`NullPointerException` occurred at the following line while running UM at start-up:

SiteServiceImpl.java
```
return siteFeedMapper.getSiteState(siteId, studioClusterUtils.getClusterNodeLocalAddress());
```

### Steps to reproduce

Steps:

1. Create a new site in 3.1.27
2. Upgrade Studio to 3.1.28
3. Start Studio
4. Notice that there is a `NullPointerExeption` as in the log

### Relevant log output

```shell
ERROR] 2022-12-27T15:02:57,848 [localhost-startStop-1] [job.StudioSyncRepositoryTask] | Failed to sync database from repository for site ed
java.lang.NullPointerException: null
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.getSiteState(SiteServiceImpl.java:1684) ~[classes/:3.1.28]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$FastClassBySpringCGLIB$$562e9c15.invoke(<generated>) ~[classes/:3.1.28]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl$$EnhancerBySpringCGLIB$$dadca209.getSiteState(<generated>) ~[classes/:3.1.28]
	at org.craftercms.studio.impl.v2.job.StudioSyncRepositoryTask.executeInternal(StudioSyncRepositoryTask.java:68) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:80) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.upgrade.pipeline.SiteRepositoryUpgradePipelineImpl.execute(SiteRepositoryUpgradePipelineImpl.java:122) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.upgradeSiteConfiguration(DefaultUpgradeManagerImpl.java:178) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.upgradeSite(DefaultUpgradeManagerImpl.java:135) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.upgradeExistingSites(DefaultUpgradeManagerImpl.java:205) [classes/:3.1.28]
	at org.craftercms.studio.impl.v2.upgrade.DefaultUpgradeManagerImpl.init(DefaultUpgradeManagerImpl.java:277) [classes/:3.1.28]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
```

**Comment by phuongnq** [comment]
verified
