### ISSUE TITLE
[videocenter] Blank page when click through selected XB element

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5906]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using `z` + mouse click on a selected XB element in preview mode of the home page, the video page is blank and there is an error in the console.

### Steps to reproduce

Steps:

1. Create a new site with Video Center BP
2. While the XB is enabled, click a video thumbnail so that the edit tooltip is available
3. `z` + mouse click to click through to navigate to video detail.
4. See the error: video detail page is blank and there is the following error in the console:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'modelId')
    at Jf (ZoneMenu.js:49:13)
    at ia (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at Ou (react-dom.production.min.js:250:347)
    at Du (react-dom.production.min.js:250:278)
    at Mu (react-dom.production.min.js:250:138)
    at gu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qi (react-dom.production.min.js:122:325)
ss @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
fo @ react-dom.production.min.js:131
hs @ react-dom.production.min.js:220
xu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
wu @ react-dom.production.min.js:252
gu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
vu @ react-dom.production.min.js:244
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
i @ Subscription.js:90
d @ redux.js:296
(anonymous) @ index.js:20
(anonymous) @ createEpicMiddleware.js:46
dispatch @ redux.js:659
(anonymous) @ Subscriber.ts:194
t._next @ Subscriber.ts:119
t.next @ Subscriber.ts:75
(anonymous) @ mergeInternals.ts:85
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ observeOn.ts:66
(anonymous) @ executeSchedule.ts:27
t._execute @ AsyncAction.ts:116
t.execute @ QueueAction.ts:26
t.flush @ AsyncScheduler.ts:39
t.schedule @ QueueAction.ts:19
e.schedule @ Scheduler.ts:60
r @ executeSchedule.ts:26
(anonymous) @ observeOn.ts:66
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ mergeInternals.ts:85
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ mergeInternals.ts:85
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
t._next @ Subscriber.ts:119
t.next @ Subscriber.ts:75
(anonymous) @ map.ts:56
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ map.ts:56
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ map.ts:56
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ ajax.ts:474
load (async)
(anonymous) @ ajax.ts:457
e._trySubscribe @ Observable.ts:244
(anonymous) @ Observable.ts:234
o @ errorContext.ts:29
e.subscribe @ Observable.ts:220
(anonymous) @ map.ts:52
(anonymous) @ lift.ts:24
(anonymous) @ Observable.ts:226
o @ errorContext.ts:29
e.subscribe @ Observable.ts:220
(anonymous) @ map.ts:52
(anonymous) @ lift.ts:24
(anonymous) @ Observable.ts:226
o @ errorContext.ts:29
e.subscribe @ Observable.ts:220
(anonymous) @ map.ts:52
(anonymous) @ lift.ts:24
(anonymous) @ Observable.ts:226
o @ errorContext.ts:29
e.subscribe @ Observable.ts:220
(anonymous) @ catchError.ts:114
(anonymous) @ lift.ts:24
(anonymous) @ Observable.ts:226
o @ errorContext.ts:29
e.subscribe @ Observable.ts:220
e @ mergeInternals.ts:71
g @ mergeInternals.ts:53
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ filter.ts:71
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ observeOn.ts:66
(anonymous) @ executeSchedule.ts:27
t._execute @ AsyncAction.ts:116
t.execute @ QueueAction.ts:26
t.flush @ AsyncScheduler.ts:39
t.schedule @ QueueAction.ts:19
e.schedule @ Scheduler.ts:60
r @ executeSchedule.ts:26
(anonymous) @ observeOn.ts:66
a._next @ OperatorSubscriber.ts:43
t.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:63
o @ errorContext.ts:29
t.next @ Subject.ts:58
(anonymous) @ createEpicMiddleware.js:50
search @ Video.js:392
value @ Video.js:107
t @ Video.js:31
vo @ react-dom.production.min.js:135
Ha @ react-dom.production.min.js:181
Ws @ react-dom.production.min.js:269
Ou @ react-dom.production.min.js:250
Du @ react-dom.production.min.js:250
Mu @ react-dom.production.min.js:250
gu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Gi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
ZoneMenu.js:49 Uncaught TypeError: Cannot read properties of undefined (reading 'modelId')
    at Jf (ZoneMenu.js:49:13)
    at ia (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at Ou (react-dom.production.min.js:250:347)
    at Du (react-dom.production.min.js:250:278)
    at Mu (react-dom.production.min.js:250:138)
    at gu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qi (react-dom.production.min.js:122:325)
```

### Screenshots and/or videos

![2023-01-16_16-34](https://user-images.githubusercontent.com/2996543/212646490-270c32a2-0e1a-4f50-a2b3-d336aa90abc6.png)
![2023-01-16_16-34_1](https://user-images.githubusercontent.com/2996543/212646507-bdb8f80d-f6fd-4b2d-92e2-509999b390e3.png)

**Comment by phuongnq** [comment]
@russdanner FYI

**Comment by jvega190** [comment]
@rart after merging, experience builder npm package needs to be published for the react blueprints to be updated

**Comment by jvega190** [comment]
@rart assigning it to you for XB publishing

**Comment by phuongnq** [comment]
verified!
