### ISSUE TITLE
[studio] Ensure clean shutdown of that database and scheduled tasks that rely on it

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5951]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It's possible to request get errors from ongoing tasks that leverage the database when performing an orderly shutdown. You can see in the error below a job is working while the shutdown to the container is issued. The database is stopped and then the job fails.

```
08-Feb-2023 13:09:36.110 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
08-Feb-2023 13:09:36.110 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
08-Feb-2023 13:09:36.116 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-0.0.0.0-8009"]
08-Feb-2023 13:09:36.121 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
[INFO] 2023-02-08T13:09:36,127 [localhost-startStop-2] [] [support.XmlWebApplicationContext] | Closing WebApplicationContext for namespace 'Spring MVC Dispatcher Servlet-servlet': startup date [Wed Feb 08 13:07:41 CST 2023]; parent: Root WebApplicationContext 
[INFO] 2023-02-08T13:09:36,137 [localhost-startStop-2] [] [support.XmlWebApplicationContext] | Closing Root WebApplicationContext: startup date [Wed Feb 08 13:07:33 CST 2023]; root of context hierarchy 
[INFO] 2023-02-08T13:09:36,137 [localhost-startStop-2] [] [support.DefaultLifecycleProcessor] | Stopping beans in phase 2147483647 
[INFO] 2023-02-08T13:09:36,158 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.cacheTickerScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:36,159 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:36,171 [localhost-startStop-2] [] [concurrent.ThreadPoolTaskScheduler] | Shutting down ExecutorService 'crafter.licenseScheduler' 
[INFO] 2023-02-08T13:09:36,171 [localhost-startStop-2] [] [quartz.SchedulerFactoryBean] | Shutting down Quartz Scheduler 
[INFO] 2023-02-08T13:09:36,172 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED shutting down. 
[INFO] 2023-02-08T13:09:36,172 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:36,172 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED shutdown complete. 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | <DESTROYING SITE CONTEXTS> 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | <Destroying site context: mis> 
[INFO] 2023-02-08T13:09:36,174 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,175 [localhost-startStop-2] [] [context.RestrictedApplicationContext] | Closing org.craftercms.engine.util.spring.context.RestrictedApplicationContext@4a69691: startup date [Wed Feb 08 13:07:40 CST 2023]; parent: Root WebApplicationContext 
[WARN] 2023-02-08T13:09:36,176 [localhost-startStop-2] [] [dataaccess.DatabasePool] | Closing database connection due to shutdown event. 
[INFO] 2023-02-08T13:09:36,296 [localhost-startStop-2] [] [context.SiteContextManager] | Site context destroyed: SiteContext{siteName='mis', context=FileSystemContext{id='cc2190c5902e0b4c691408c90ad60420', rootFolderPath='file:/app/ercot/crafter/data/repos/sites/mis/sandbox/'}, fallback=false, staticAssetsPath='/static-assets', templatesPath='/templates', restScriptsPath='/scripts/rest', controllerScriptsPath='/scripts/controllers'} 
[INFO] 2023-02-08T13:09:36,296 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,297 [localhost-startStop-2] [] [context.SiteContextManager] | </Destroying site context: mis> 
[INFO] 2023-02-08T13:09:36,297 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,297 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:36,297 [localhost-startStop-2] [] [context.SiteContextManager] | </DESTROYING SITE CONTEXTS> 
[INFO] 2023-02-08T13:09:36,297 [localhost-startStop-2] [] [context.SiteContextManager] | ================================================== 
[INFO] 2023-02-08T13:09:37,303 [localhost-startStop-2] [] [aws.S3ClientCachingFactory] | Shutting down S3ClientCachingFactory 
[INFO] 2023-02-08T13:09:37,306 [localhost-startStop-2] [] [quartz.SchedulerFactoryBean] | Shutting down Quartz Scheduler 
[INFO] 2023-02-08T13:09:37,306 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.cacheTickerScheduler_$_NON_CLUSTERED shutting down. 
[INFO] 2023-02-08T13:09:37,306 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.cacheTickerScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:37,307 [localhost-startStop-2] [] [core.QuartzScheduler] | Scheduler crafter.cacheTickerScheduler_$_NON_CLUSTERED shutdown complete. 
08-Feb-2023 13:09:37.331 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [oracle.jdbc.OracleDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
08-Feb-2023 13:09:37.332 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.microsoft.sqlserver.jdbc.SQLServerDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
08-Feb-2023 13:09:37.334 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [crafter.cacheTickerScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
08-Feb-2023 13:09:37.335 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 java.util.TimerThread.mainLoop(Timer.java:526)
 java.util.TimerThread.run(Timer.java:505)
08-Feb-2023 13:09:37.337 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@58c762bc]) and a value of type [org.springframework.security.core.context.SecurityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@ffffffff: Null authentication]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
08-Feb-2023 13:09:37.337 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@58c762bc]) and a value of type [org.springframework.security.core.context.SecurityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@ffffffff: Null authentication]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[INFO] 2023-02-08T13:09:37,362 [localhost-startStop-2] [support.XmlWebApplicationContext] | Closing WebApplicationContext for namespace 'Spring MVC Dispatcher Servlet-servlet': startup date [Wed Feb 08 13:07:24 CST 2023]; parent: Root WebApplicationContext 
[INFO] 2023-02-08T13:09:37,366 [localhost-startStop-2] [support.XmlWebApplicationContext] | Closing Root WebApplicationContext: startup date [Wed Feb 08 13:07:22 CST 2023]; root of context hierarchy 
[INFO] 2023-02-08T13:09:37,407 [localhost-startStop-2] [support.XmlWebApplicationContext] | Closing WebApplicationContext for namespace 'Spring MVC Dispatcher Servlet-servlet': startup date [Wed Feb 08 13:07:14 CST 2023]; parent: Root WebApplicationContext 
[INFO] 2023-02-08T13:09:37,413 [localhost-startStop-2] [support.XmlWebApplicationContext] | Closing Root WebApplicationContext: startup date [Wed Feb 08 13:06:26 CST 2023]; root of context hierarchy 
[INFO] 2023-02-08T13:09:37,414 [localhost-startStop-2] [support.DefaultLifecycleProcessor] | Stopping beans in phase 2147483647 
[INFO] 2023-02-08T13:09:37,438 [localhost-startStop-2] [core.QuartzScheduler] | Scheduler crafter.cacheTickerScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:37,439 [localhost-startStop-2] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-02-08T13:09:37,439 [localhost-startStop-2] [support.DefaultLifecycleProcessor] | Stopping beans in phase 0 
[INFO] 2023-02-08T13:09:37,440 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld: 2023-02-08 13:09:37 0 [Note] /app/ercot/crafter/bin/dbms/bin/mysqld (initiated by: unknown): Normal shutdown 
Then an error pops out: 
BUT: this is because the thread was busy doing something and the system chopped the database out from under it.
 
[INFO] 2023-02-08T13:09:37,440 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld: 2023-02-08 13:09:37 0 [Note] Event Scheduler: Purging the queue. 0 events 
[ERROR] 2023-02-08T13:09:37,885 [studio.clockTaskExecutor-30] [job.StudioSyncRepositoryTask] | Failed to sync database from repository for site mis 
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=127.0.0.1)(port=33306)(type=master) : Connection refused (Connection refused)
### The error may exist in org/craftercms/studio/api/v1/dal/SiteFeedMapper.xml
### The error may involve org.craftercms.studio.api.v1.dal.SiteFeedMapper.getSiteState
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=127.0.0.1)(port=33306)(type=master) : Connection refused (Connection refused)
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-1.3.1.jar:1.3.1]
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.1.jar:1.3.1]
at com.sun.proxy.$Proxy39.selectOne(Unknown Source) ~[?:?]
at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-1.3.1.jar:1.3.1]
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82) ~[mybatis-3.4.5.jar:3.4.5]
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.5.jar:3.4.5]
This activity will re-run when the server is resarted.
```

### Describe the solution you'd like

Facilitate a more orderly shutdown of the Studio context
- Block database shutdown until current jobs that require it are complete or support canceling a job in an orderly fashion.
- Block new jobs from starting

**Comment by russdanner** [comment]
RD: Reviewed 1/24/25
