### ISSUE TITLE
Upgrade to the latest Spring Framework

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5977]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.
Spring Boot 2.7 is approaching EOL.

### Describe the solution you'd like

Upgrade to the latest Spring Framework. Upgrade to Spring 6 and Spring Boot 3.

Upgrade Spring Framework and upgrade dependencies to keep with that. This includes
- [x] Spring Framework 6
- [x] Spring Boot 3
- [x] Java 21
- [x] Apache Tomcat 10
- [x] FreeMarker
- [x] HTTP Proxy
- [x] Tuckey
- [x] ESAPI
- [x] FileUpload
- [x] Groovy 4, see https://github.com/craftercms/craftercms/issues/5876
- [x] Anything else that breaks with the `javax` to `jakarta` change

**Comment by phuongnq** [comment]
Note: Spring Boot 3 has Groovy dependency 4.0.11. We may need to upgrade Groovy.
https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html

**Comment by sumerjabri** [comment]
@phuongnq yes, it's in the plan https://github.com/craftercms/craftercms/issues/5876

**Comment by jmendeza** [comment]
These are some libraries I have found so far that are non-compatible with Jakarta 9+ (required by spring 6)
ESAPI
Tuckey (url rewrite)
Freemarker
smiley-http-proxy-servlet
Apache commons - fileupload

**Comment by sumerjabri** [comment]
These are some libraries I have found so far that are non-compatible with Jakarta 9+
- ESAPI
- Tuckey (URL rewrite)
- Freemarker
- smiley-http-proxy-servlet
- Apache commons - fileupload

Due to the above, we must wait until our dependencies are updated to Jakarta 9.

I will close this ticket for now.

**Comment by sumerjabri** [comment]
FreeMarker is getting there, see https://github.com/apache/freemarker/pull/104

**Comment by sumerjabri** [comment]
@phuongnq this work will be contingent on https://github.com/apache/freemarker/pull/104, so we don't have to rush it. We can begin with a draft PR from a special branch. We can work that branch until it's ready and then turn the Draft PR to a full PR.

**Comment by sumerjabri** [comment]
FreeMarker has merged the Jakarta changes! https://github.com/apache/freemarker/pull/104

**Comment by sumerjabri** [comment]
FreeMarker SNAPSHOT has been pushed to Maven https://lists.apache.org/thread/vcw952xpxj3ns5srbz444r6h35dpodd2

```
<repository>
  <id>apache-snapshot-repository</id>
  <url>https://repository.apache.org/content/repositories/snapshots/</url>
  <releases><enabled>false</enabled></releases>
  <snapshots><enabled>true</enabled></snapshots>
</repository>
```

**Comment by sumerjabri** [comment]
@phuongnq I created a `feature/5977` branch for us to collaborate within for this feature. Please start working in that branch on this ticket and use the `snapshot` repository of FreeMarker to get us moving forward.

To get a base setup, you can clone like this:
`git clone -b feature/5977 https://github.com/craftercms/craftercms java21`

You can then work on all modules and send PRs to the `feature/5977` branch.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/pull/6377

**Comment by phuongnq** [comment]
@sumerjabri I sent the first PRs to update `commons`. This only makes sure `mvn clean install` runs correctly with the test cases updated for commons. Other changes will be added eventually to make this work in other modules.

* `@Required` annotation is removed so I switched for those setters to be constructor arguments.
* Update `javax.**` => `jakarta.**`

**Comment by phuongnq** [comment]
PR to update `core` note:

* Update `javax.**` => `jakarta.**` 
* `@Required` annotation is removed so I switched for those setters to be constructor arguments when possible. When constructor is not possible due to circular dependencies, using `@AutoWired` and `@Lazy` annotations on setter method
* Make sure `mvn clean install` pass all test cases

**Comment by phuongnq** [comment]
@sumerjabri For Engine module, I had a TODO here: https://github.com/craftercms/engine/pull/720/commits/200b7baba43f16161b005825fb1d64bda74cb1e3
We should use the latest `CookieLocaleResolver` but this class has been changed in v6 that we cannot override `getCookieName()` so I keep using the old one (by copying the whole class to our code) for now.

**Comment by sumerjabri** [comment]
@alhambrav Spring 6 requires mandatory (required) injected dependencies into beans to be done via the constructor. Those who override our beans must switch from <property> to <constructor-arg> style dependency injection. See the PR for many examples. This is a breaking change that we must document in 4.2.0

**Comment by sumerjabri** [comment]
@phuongnq please check off the tasks completed in this ticket.

See:
![image](https://github.com/craftercms/craftercms/assets/3931908/b826830c-2e6f-4c49-948b-761f9b1d493a)

**Comment by phuongnq** [comment]
@sumerjabri I have checked the list.
For ESAPI, please note that there is no change regarding the version. We only added the flag `<classifier>jakarta</classifier>` to support it. Refer to https://github.com/ESAPI/esapi-java-legacy/wiki/Using-ESAPI-with-Jakarta-EE-Servlet-API-Specification-5.0-and-later#with-maven for the detail

**Comment by sumerjabri** [comment]
@phuongnq it's failing to start, see:

```
[ERROR] 2024-04-30T14:26:23,065 [http-nio-8080-exec-7] [default] [preview.PreviewAccessTokenFilter] | User is not authorized to preview site. 'crafterPreview' cookie not found 
[ERROR] 2024-04-30T14:26:23,068 [http-nio-8080-exec-7] [default] [impl.HttpStatusCodeAwareExceptionHandler] | GET http://localhost:8080/studio failed 
org.craftercms.engine.exception.HttpStatusCodeException: User is not authorized to preview site. 'crafterPreview' cookie not found
	at org.craftercms.engine.util.spring.security.preview.PreviewAccessTokenFilter.doFilter(PreviewAccessTokenFilter.java:63) ~[classes/:4.2.0-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.3.jar:6.2.3]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.2.3.jar:6.2.3]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.2.3.jar:6.2.3]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:53) ~[classes/:4.2.0-SNAPSHOT]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:77) ~[classes/:4.2.0-SNAPSHOT]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:78) ~[crafter-commons-utilities-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:70) ~[log4j-jakarta-web-2.23.1.jar:2.23.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersBefore(HeaderWriterFilter.java:82) ~[spring-security-web-6.2.3.jar:6.2.3]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:72) ~[spring-security-web-6.2.3.jar:6.2.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.1.5.jar:6.1.5]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.1.5.jar:6.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:10.1.20]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[catalina.jar:10.1.20]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:10.1.20]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:10.1.20]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:10.1.20]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[catalina.jar:10.1.20]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-coyote.jar:10.1.20]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:10.1.20]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-coyote.jar:10.1.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) ~[tomcat-coyote.jar:10.1.20]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:10.1.20]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:10.1.20]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:10.1.20]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-util.jar:10.1.20]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]


```
