### ISSUE TITLE
[studio] Error uploading videos though MediaConvert control

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6057]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

There is an error while uploading video to S3 through MediaConvert control

### Steps to reproduce

Steps:

1. Create a new site
2. Add MediaConvert with a profile
3. Upload a video through the MediaConvert and see the error

### Relevant log output

```shell
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: xxxxxxx; S3 Extended Request ID: xxxxxxxx; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[aws-java-sdk-core-1.12.463.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5470) ~[aws-java-sdk-s3-1.12.463.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5417) ~[aws-java-sdk-s3-1.12.463.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3728) ~[aws-java-sdk-s3-1.12.463.jar:?]
	at org.craftercms.studio.impl.v1.service.aws.AwsUtils.uploadStream(AwsUtils.java:64) ~[classes/:4.1.0-SNAPSHOT]
	... 144 more
```

**Comment by sumerjabri** [comment]
This may also apply to other S3 access. Please see if this affects:
- [ ] Engine (Serverless Mode)
- [ ] Commons
- [ ] Studio (data sources, blob-store, etc.)

**Comment by phuongnq** [comment]
Confirmed that there is no other change needed.
I also double-checked the usage of function [uploadStream](https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java#L50) and only the MediaConvert use the folder directory as a part of the bucket name. All other services have already implemented the logic as in the PR of this ticket (only bucket name as the `inputBucket`, other resource's directory, and filename are the `inputKey`)
