### ISSUE TITLE
[docker] Switch the Docker images to use Alpine instead of Ubuntu

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6107]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Ubuntu-based images are quite large.

### Describe the solution you'd like

Switch to Alpine to reduce image size.

**Comment by sumerjabri** [comment]
@phuongnq I build the new images like this:
```
./gradlew buildAuthoringLocal -PauthoringBundle=/home/sumer/nobackup/crafter/4.1/ce/bundles/crafter-cms-authoring-4.1.0-rc2-linux-x86_64.tar.gz -Ptag=4.1.2-SNAPSHOT
```
Where the bundle referenced is built based on the latest in `develop`

I ran the image like this:
```
docker run -p 8080:8080 craftercms/authoring_local:4.1.2-SNAPSHOT
```

It failed in MariaDB, see the log:
```
[ERROR] 2023-08-09T21:45:32,961 [Exec Default Executor] [exec.LoggingExecuteResultHandler] | Program [/opt/crafter/bin/dbms/scripts/mysql_install_db, --datadir=/opt/crafter/data/db, --auth-root-authentication-method=normal, --datadir=/opt/crafter/data/db, --tmpdir=/opt/crafter/temp/tomcat/MariaDB4j/tmp/3306, --basedir=/opt/crafter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /opt/crafter/bin/dbms) failed unexpectedly 
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) [commons-exec-1.3.jar:1.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[ERROR] 2023-08-09T21:45:33,048 [main] [exec.ManagedProcess] | Program [/opt/crafter/bin/dbms/scripts/mysql_install_db, --datadir=/opt/crafter/data/db, --auth-root-authentication-method=normal, --datadir=/opt/crafter/data/db, --tmpdir=/opt/crafter/temp/tomcat/MariaDB4j/tmp/3306, --basedir=/opt/crafter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /opt/crafter/bin/dbms) failed 
[WARN] 2023-08-09T21:45:33,050 [main] [support.XmlWebApplicationContext] | Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'studioMariaDBService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed 
[INFO] 2023-08-09T21:45:33,050 [main] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED shutting down. 
[INFO] 2023-08-09T21:45:33,050 [main] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED paused. 
[INFO] 2023-08-09T21:45:33,050 [main] [core.QuartzScheduler] | Scheduler crafter.jobScheduler_$_NON_CLUSTERED shutdown complete. 
[INFO] 2023-08-09T21:45:33,061 [main] [cache.GuavaCacheFactoryBean] | Cleaning up cache for bean userDetailsCache 
[INFO] 2023-08-09T21:45:33,062 [main] [context.SiteContextManager] | ================================================== 
[INFO] 2023-08-09T21:45:33,062 [main] [context.SiteContextManager] | <DESTROYING SITE CONTEXTS> 
[INFO] 2023-08-09T21:45:33,062 [main] [context.SiteContextManager] | ================================================== 
[INFO] 2023-08-09T21:45:33,062 [main] [context.SiteContextManager] | ================================================== 
[INFO] 2023-08-09T21:45:33,062 [main] [context.SiteContextManager] | </DESTROYING SITE CONTEXTS> 
[INFO] 2023-08-09T21:45:33,063 [main] [context.SiteContextManager] | ================================================== 
[INFO] 2023-08-09T21:45:33,067 [main] [cache.GuavaCacheFactoryBean] | Cleaning up cache for bean crafter.guavaCacheAuthenticationCache 
[INFO] 2023-08-09T21:45:33,067 [main] [cache.GuavaCacheFactoryBean] | Cleaning up cache for bean configurationCache 
[INFO] 2023-08-09T21:45:33,070 [main] [aws.S3ClientCachingFactory] | Shutting down S3ClientCachingFactory 
[ERROR] 2023-08-09T21:45:33,073 [main] [context.ContextLoader] | Context initialization failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'studioMariaDBService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: MariaDB4jSpringService start() failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920) ~[spring-context-5.3.27.jar:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.27.jar:5.3.27]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4494) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4946) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1023) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1910) [catalina.jar:9.0.78]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.78]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) [?:?]
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:824) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:474) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328) [catalina.jar:9.0.78]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318) [catalina.jar:9.0.78]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.78]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.78]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:922) [catalina.jar:9.0.78]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.78]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.78]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.78]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.78]
Caused by: java.lang.IllegalStateException: MariaDB4jSpringService start() failed
	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:152) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.postConstruct(MariaDB4jService.java:66) ~[mariaDB4j-core-2.6.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.27.jar:5.3.27]
	... 57 more
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while installing the database
	at ch.vorburger.mariadb4j.DB.install(DB.java:179) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:98) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.start(MariaDB4jService.java:76) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:149) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.postConstruct(MariaDB4jService.java:66) ~[mariaDB4j-core-2.6.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.27.jar:5.3.27]
	... 57 more
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/opt/crafter/bin/dbms/scripts/mysql_install_db, --datadir=/opt/crafter/data/db, --auth-root-authentication-method=normal, --datadir=/opt/crafter/data/db, --tmpdir=/opt/crafter/temp/tomcat/MariaDB4j/tmp/3306, --basedir=/opt/crafter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /opt/crafter/bin/dbms) failed, exitValue=1, last 100 lines of console:
/opt/crafter/bin/dbms/scripts/mysql_install_db: line 306: /opt/crafter/bin/dbms/bin/my_print_defaults: not found
Installing MariaDB/MySQL system tables in '/opt/crafter/data/db' ...
/opt/crafter/bin/dbms/scripts/mysql_install_db: line 525: /opt/crafter/bin/dbms/bin/mysqld: not found

Installation of system tables failed!  Examine the logs in
/opt/crafter/data/db for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /opt/crafter/bin/dbms/scripts/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /opt/crafter/bin/dbms/bin/mysqld --skip-grant-tables --general-log &

and use the command line tool /opt/crafter/bin/dbms/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /opt/crafter/bin/dbms/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /opt/crafter/data/db that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at http://mariadb.org/jira

	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:310) ~[exec-3.1.3.jar:?]
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:216) ~[exec-3.1.3.jar:?]
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:155) ~[exec-3.1.3.jar:?]
	at ch.vorburger.mariadb4j.DB.install(DB.java:176) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:98) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.start(MariaDB4jService.java:76) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService.start(MariaDB4jSpringService.java:149) ~[mariaDB4j-core-2.6.0.jar:?]
	at ch.vorburger.mariadb4j.MariaDB4jService.postConstruct(MariaDB4jService.java:66) ~[mariaDB4j-core-2.6.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.27.jar:5.3.27]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.27.jar:5.3.27]
	... 57 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) ~[commons-exec-1.3.jar:1.3]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
09-Aug-2023 21:45:33.077 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
09-Aug-2023 21:45:33.079 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/studio] startup failed due to previous errors
```
