### ISSUE TITLE
[studio-ui] permittedRoles is not working for widget PublishingStatusButton

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6158]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

We would like to hide the publishing status button in the toolbar so it's only visible for admin users and not for the rest of the users. But updating the `permittedRoles` does not work for the widget `craftercms.components.PublishingStatusButton`

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Update the ui.xml as the following:
```
<widget id="craftercms.components.PublishingStatusButton">
                        <permittedRoles>
                          <role>admin</role>
                        </permittedRoles>
                        <configuration>
                            <variant>icon</variant>
                        </configuration>
                    </widget>
```
3. Notice that the studio is blank and there is an error in the console:

```
TypeError: e.permittedRoles.includes is not a function
    at renderWidgets.tsx:42:68
    at Array.some (<anonymous>)
    at renderWidgets.tsx:42:31
    at Array.filter (<anonymous>)
    at r (renderWidgets.tsx:39:10)
    at P (ToolBar.tsx:83:12)
    at qa (react-dom.production.min.js:167:137)
    at Wu (react-dom.production.min.js:197:258)
    at qc (react-dom.production.min.js:292:88)
    at As (react-dom.production.min.js:280:389)
```

### Screenshots and/or videos

![2023-07-18_13-15](https://github.com/craftercms/craftercms/assets/2996543/4a3fe4bd-1ecb-476c-9895-33ba431bc8cf)

**Comment by phuongnq** [comment]
Verified!
