### ISSUE TITLE
[studio-ui] UI Sass build output has errors

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6229]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Sometimes, there seems to be error output on the sass build. Seems related to the recent bootstrap and other related sass updates.

### Steps to reproduce

Steps:

1. `git clone https://github.com/craftercms/craftercms.git -b develop`, cd in and `mvn install && mvn -f pom-spring-boot.xml install`
2. `./gradlew build deploy -PquietBuild=false -PrefreshEnv=true -Pmodules=studio-ui`
3. Watch the output
4. See the issue

### Relevant log output

```shell
[INFO] --- frontend-maven-plugin:1.12.0:yarn (UI styles: Build sass styles) @ crafter-studio-ui ---
[INFO] yarn not inheriting proxy config from Maven
[INFO] Running 'yarn build-if-changed' in /Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/ui/scss
[INFO] 📦  Building 1 package...
[INFO] [@craftercms/studio-ui-styles] Error compiling global.scss Error: Can't find stylesheet to import.
[INFO] [@craftercms/studio-ui-styles]   ╷
[INFO] [@craftercms/studio-ui-styles] 1 │ @import '../../static-assets/libs/bootstrap/scss/mixins';
[INFO] [@craftercms/studio-ui-styles]   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [@craftercms/studio-ui-styles]   ╵
[INFO] [@craftercms/studio-ui-styles]   src/global.scss 1:9  root stylesheet
[INFO] [@craftercms/studio-ui-styles]     at Object.wrapException (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:1250:17)
[INFO] [@craftercms/studio-ui-styles]     at /Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:71174:25
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.$protected (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:3841:15)
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.call$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28694:12)
[INFO] [@craftercms/studio-ui-styles]     at _awaitOnObject_closure.call$1 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28682:32)
[INFO] [@craftercms/studio-ui-styles]     at Object._rootRunUnary (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4216:18)
[INFO] [@craftercms/studio-ui-styles]     at StaticClosure.<anonymous> (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:100086:16)
[INFO] [@craftercms/studio-ui-styles]     at _CustomZone.runUnary$2$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:30091:39)
[INFO] [@craftercms/studio-ui-styles]     at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:29163:51)
[INFO] [@craftercms/studio-ui-styles]     at Object._Future__propagateToListeners (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4012:93) {
[INFO] [@craftercms/studio-ui-styles]   formatted: "Error: Can't find stylesheet to import.\n" +
[INFO] [@craftercms/studio-ui-styles]     '  ╷\n' +
[INFO] [@craftercms/studio-ui-styles]     "1 │ @import '../../static-assets/libs/bootstrap/scss/mixins';\n" +
[INFO] [@craftercms/studio-ui-styles]     '  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
[INFO] [@craftercms/studio-ui-styles]     '  ╵\n' +
[INFO] [@craftercms/studio-ui-styles]     '  src/global.scss 1:9  root stylesheet',
[INFO] [@craftercms/studio-ui-styles]   line: 1,
[INFO] [@craftercms/studio-ui-styles]   column: 9,
[INFO] [@craftercms/studio-ui-styles]   file: '/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/ui/scss/src/global.scss',
[INFO] [@craftercms/studio-ui-styles]   status: 1
[INFO] [@craftercms/studio-ui-styles] }
[INFO] [@craftercms/studio-ui-styles] Error compiling bootstrap-5.3.scss Error: Can't find stylesheet to import.
[INFO] [@craftercms/studio-ui-styles]    ╷
[INFO] [@craftercms/studio-ui-styles] 17 │ @import '../../static-assets/libs/bootstrap/scss/functions';
[INFO] [@craftercms/studio-ui-styles]    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [@craftercms/studio-ui-styles]    ╵
[INFO] [@craftercms/studio-ui-styles]   src/bootstrap-5.3.scss 17:9  root stylesheet
[INFO] [@craftercms/studio-ui-styles]     at Object.wrapException (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:1250:17)
[INFO] [@craftercms/studio-ui-styles]     at /Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:71174:25
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.$protected (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:3841:15)
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.call$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28694:12)
[INFO] [@craftercms/studio-ui-styles]     at _awaitOnObject_closure.call$1 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28682:32)
[INFO] [@craftercms/studio-ui-styles]     at Object._rootRunUnary (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4216:18)
[INFO] [@craftercms/studio-ui-styles]     at StaticClosure.<anonymous> (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:100086:16)
[INFO] [@craftercms/studio-ui-styles]     at _CustomZone.runUnary$2$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:30091:39)
[INFO] [@craftercms/studio-ui-styles]     at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:29163:51)
[INFO] [@craftercms/studio-ui-styles]     at Object._Future__propagateToListeners (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4012:93) {
[INFO] [@craftercms/studio-ui-styles]   formatted: "Error: Can't find stylesheet to import.\n" +
[INFO] [@craftercms/studio-ui-styles]     '   ╷\n' +
[INFO] [@craftercms/studio-ui-styles]     "17 │ @import '../../static-assets/libs/bootstrap/scss/functions';\n" +
[INFO] [@craftercms/studio-ui-styles]     '   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
[INFO] [@craftercms/studio-ui-styles]     '   ╵\n' +
[INFO] [@craftercms/studio-ui-styles]     '  src/bootstrap-5.3.scss 17:9  root stylesheet',
[INFO] [@craftercms/studio-ui-styles]   line: 17,
[INFO] [@craftercms/studio-ui-styles]   column: 9,
[INFO] [@craftercms/studio-ui-styles]   file: '/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/ui/scss/src/bootstrap-5.3.scss',
[INFO] [@craftercms/studio-ui-styles]   status: 1
[INFO] [@craftercms/studio-ui-styles] }
[INFO] [@craftercms/studio-ui-styles] Error compiling user-dashboard/user-dashboard.scss Error: Can't find stylesheet to import.
[INFO] [@craftercms/studio-ui-styles]    ╷
[INFO] [@craftercms/studio-ui-styles] 20 │ @import '../../../../static-assets/libs/bootstrap/scss/mixins';
[INFO] [@craftercms/studio-ui-styles]    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [@craftercms/studio-ui-styles]    ╵
[INFO] [@craftercms/studio-ui-styles]   src/user-dashboard/user-dashboard.scss 20:9  root stylesheet
[INFO] [@craftercms/studio-ui-styles]     at Object.wrapException (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:1250:17)
[INFO] [@craftercms/studio-ui-styles]     at /Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:71174:25
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.$protected (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:3841:15)
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.call$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28694:12)
[INFO] [@craftercms/studio-ui-styles]     at _awaitOnObject_closure.call$1 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28682:32)
[INFO] [@craftercms/studio-ui-styles]     at Object._rootRunUnary (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4216:18)
[INFO] [@craftercms/studio-ui-styles]     at StaticClosure.<anonymous> (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:100086:16)
[INFO] [@craftercms/studio-ui-styles]     at _CustomZone.runUnary$2$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:30091:39)
[INFO] [@craftercms/studio-ui-styles]     at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:29163:51)
[INFO] [@craftercms/studio-ui-styles]     at Object._Future__propagateToListeners (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4012:93) {
[INFO] [@craftercms/studio-ui-styles]   formatted: "Error: Can't find stylesheet to import.\n" +
[INFO] [@craftercms/studio-ui-styles]     '   ╷\n' +
[INFO] [@craftercms/studio-ui-styles]     "20 │ @import '../../../../static-assets/libs/bootstrap/scss/mixins';\n" +
[INFO] [@craftercms/studio-ui-styles]     '   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
[INFO] [@craftercms/studio-ui-styles]     '   ╵\n' +
[INFO] [@craftercms/studio-ui-styles]     '  src/user-dashboard/user-dashboard.scss 20:9  root stylesheet',
[INFO] [@craftercms/studio-ui-styles]   line: 20,
[INFO] [@craftercms/studio-ui-styles]   column: 9,
[INFO] [@craftercms/studio-ui-styles]   file: '/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/ui/scss/src/user-dashboard/user-dashboard.scss',
[INFO] [@craftercms/studio-ui-styles]   status: 1
[INFO] [@craftercms/studio-ui-styles] }
[INFO] [@craftercms/studio-ui-styles] Error compiling temp.scss Error: Can't find stylesheet to import.
[INFO] [@craftercms/studio-ui-styles]    ╷
[INFO] [@craftercms/studio-ui-styles] 18 │ @import '../../static-assets/libs/bootstrap/scss/mixins';
[INFO] [@craftercms/studio-ui-styles]    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [@craftercms/studio-ui-styles]    ╵
[INFO] [@craftercms/studio-ui-styles]   src/_studio-view.scss 18:9  @import
[INFO] [@craftercms/studio-ui-styles]   src/temp.scss 3465:9        root stylesheet
[INFO] [@craftercms/studio-ui-styles]     at Object.wrapException (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:1250:17)
[INFO] [@craftercms/studio-ui-styles]     at /Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:71174:25
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.$protected (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:3841:15)
[INFO] [@craftercms/studio-ui-styles]     at _wrapJsFunctionForAsync_closure.call$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28694:12)
[INFO] [@craftercms/studio-ui-styles]     at _awaitOnObject_closure.call$1 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:28682:32)
[INFO] [@craftercms/studio-ui-styles]     at Object._rootRunUnary (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4216:18)
[INFO] [@craftercms/studio-ui-styles]     at StaticClosure.<anonymous> (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:100086:16)
[INFO] [@craftercms/studio-ui-styles]     at _CustomZone.runUnary$2$2 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:30091:39)
[INFO] [@craftercms/studio-ui-styles]     at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:29163:51)
[INFO] [@craftercms/studio-ui-styles]     at Object._Future__propagateToListeners (/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/node_modules/sass/sass.dart.js:4012:93) {
[INFO] [@craftercms/studio-ui-styles]   formatted: "Error: Can't find stylesheet to import.\n" +
[INFO] [@craftercms/studio-ui-styles]     '   ╷\n' +
[INFO] [@craftercms/studio-ui-styles]     "18 │ @import '../../static-assets/libs/bootstrap/scss/mixins';\n" +
[INFO] [@craftercms/studio-ui-styles]     '   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
[INFO] [@craftercms/studio-ui-styles]     '   ╵\n' +
[INFO] [@craftercms/studio-ui-styles]     '  src/_studio-view.scss 18:9  @import\n' +
[INFO] [@craftercms/studio-ui-styles]     '  src/temp.scss 3465:9        root stylesheet',
[INFO] [@craftercms/studio-ui-styles]   line: 18,
[INFO] [@craftercms/studio-ui-styles]   column: 9,
[INFO] [@craftercms/studio-ui-styles]   file: '/Users/rart/Workspace/craftercms/develop-ee/src/studio-ui/ui/scss/src/_studio-view.scss',
[INFO] [@craftercms/studio-ui-styles]   status: 1
[INFO] [@craftercms/studio-ui-styles] }
[INFO] [@craftercms/studio-ui-styles] [CSS] search.css
[INFO] [@craftercms/studio-ui-styles] [CSS] graphiql.css
[INFO] [@craftercms/studio-ui-styles] [CSS] guest.css
[INFO] [@craftercms/studio-ui-styles] [CSS] uppy.css
[INFO] [@craftercms/studio-ui-styles] [CSS] browse.css
[INFO] [@craftercms/studio-ui-styles] [CSS] forms-engine.css
[INFO] [@craftercms/studio-ui-styles] [CSS] typography.css
[INFO] [@craftercms/studio-ui-styles] [CSS] tinymce-ace.css
[INFO] [@craftercms/studio-ui-styles] [CSS] ../themes/cstudioTheme/base.css
[INFO] ✨  Finished without errors.
```

**Comment by rart** [comment]
Verified.

**Comment by rart** [comment]
Issues still exist on Mac OS. Please research how to make `sed` work for all platforms.

**Comment by rart** [comment]
✅
