### ISSUE TITLE
[groovy-sandbox] Classes using `getter` methods fail

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6245]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When a Groovy class has a property and a getter method for the property, an exception is thrown during the execution.

### Describe the solution you'd like

Sample script:

```
class Test {
    private String message
    
    public String getMessage() {
        return this.message
    }
}

def t = new Test()
t.message = "this is a test"

return t.getMessage()
```

We want the `getter` method to be executed without issues.

The logs look like this:
```
Caused by: java.lang.StackOverflowError
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:693)
	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:450)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:812)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:800)
	at sun.reflect.GeneratedMethodAccessor340.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1845)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3773)
	at Test.getProperty(test.get.groovy)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:469)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:392)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:297)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:390)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:394)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty$1.callStatic(Unknown Source)
	at Test.getMessage(test.get.groovy:5)
```

**Comment by sumerjabri** [comment]
Related to https://github.com/craftersoftware/craftercms/issues/604

**Comment by phuongnq** [comment]
Fixed in https://github.com/craftercms/groovy-sandbox/pull/13

**Comment by phuongnq** [comment]
@sumerjabri We still have this issue in the sandbox with Groovy v4. A workaround for this:

```
class Test {
    private String message

    public String getMessage() {
        return this.@message
    }
}

def t = new Test()
t.message = "this is a test"

return t.getMessage()
```

So we will use `this.@message` instead of `this.message`. The reason is that `this.message` is a property access to the sandbox and it will try to get this from the method `getMessage()` which will cause an infinite loop. `this.@message` on the other hand, is a field direct access and won't cause a loop.
Will this workaround be a solution for this?

Another note, if you don't define the `getMessage()`:
```
class Test {
    private String message
}

def t = new Test()
t.message = "this is a test"

return t.getMessage()
```

On another note, we can also define `message` as public and access the `getMessage()` without explicitly implement the getter in the sandbox:

```
class Test {
    def message
}

def t = new Test()
t.message = "this is a test"
return t.getMessage()
```

**Comment by sumerjabri** [comment]
Per discussion with @russdanner and @avasquez614 we're okay with this. (Another possible path is to call the field `myMessage` and getMessage shouldn't have a problem -- that should be verified.)
