### ISSUE TITLE
[craftercms] Search upgrade from 4.0.x to 4.1.3 is broken

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6462]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `search-upgrade` from 4.0.(6,7) to 4.1.3-SNAPSHOT is throwing an error

### Steps to reproduce

Steps:

1. Create  a site in latest 4.0.x
2. Upgrade search to latest 4.1.3-SNAPSHOT
3. See the issue

### Relevant log output

```shell
========================================================================                                                                                                         
Search upgrade started                                                                                                                                                           
========================================================================                                                                                                         
Downloading Elasticsearch 7 from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.0-linux-x86_64.tar.gz                                                   
Extracting ES tar file                                                                                                                                                           
Elasticsearch is starting. To follow the log, you can run:                                                                                                                       
tail -F /opt/crafter/bundles/41/crafter/temp/upgrade/update-es.log                                                                                                               
Create ElasticSearch client                                                                                                                                                      
Check ES cluster status                                                                                                                                                          
Failed to check cluster status: Connection refused                                                                                                                               
ES not ready yet, will retry after 5s   
WARNING: A terminally deprecated method in java.lang.System has been called                                                                                                      
WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Elasticsearch (file:/opt/crafter/bundles/41/crafter/temp/upgrade/elasticsearch-7.10.0/lib/elas
ticsearch-7.10.0.jar)                                                                                                                                                            
WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Elasticsearch                                                                          
WARNING: System::setSecurityManager will be removed in a future release                                                                                                          
WARNING: A terminally deprecated method in java.lang.System has been called                                                                                                      
WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Security (file:/opt/crafter/bundles/41/crafter/temp/upgrade/elasticsearch-7.10.0/lib/elasticse
arch-7.10.0.jar)                                                                                                                                                                 
WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Security                                                                               
WARNING: System::setSecurityManager will be removed in a future release                                                                                                          
uncaught exception in thread [main]                                                                                                                                              
ElasticsearchException[failed to bind service]; nested: IndexFormatTooNewException[Format version is not supported (resource SimpleFSIndexInput(path="/opt/crafter/bundles/407/cr
after/data/indexes-es/nodes/0/_state/_25.cfs") [slice=_25.fdt]): 4 (needs to be between 1 and 3)];                                                                               
Likely root cause: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource SimpleFSIndexInput(path="/opt/crafter/bundles/407/crafter/data/i
ndexes-es/nodes/0/_state/_25.cfs") [slice=_25.fdt]): 4 (needs to be between 1 and 3)                                                                                             
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)                                                                                             
        at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)                                                                                                    
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255)                                                                                               
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:130)                                                     
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:123)                                               
        at org.apache.lucene.codecs.lucene87.Lucene87StoredFieldsFormat.fieldsReader(Lucene87StoredFieldsFormat.java:131)                                                        
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:127)                                                                  
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)                                                                                                   
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:66)                                                                             
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:58)                                                                             
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720)                                                                                      
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:81)                                                                                 
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)                                                                                                 
        at org.elasticsearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:267)                                                            
        at org.elasticsearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:409)                                                                                      
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:330)                                                                                                
        at org.elasticsearch.node.Node.<init>(Node.java:362)                                                                                                                     
        at org.elasticsearch.node.Node.<init>(Node.java:289)                                                                                                                     
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)                                                                                                    
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)                                                                                                       
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)                                                                                                        
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)                                                                                                
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)                                                                                             
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
```

**Comment by jmendeza** [comment]
Please notice that `upgrade-search` script (which will tell the search engine to re-index internally to the new format) should run when upgrading from 3.1.x versions (running ES 6) only.
When upgrading from 4.0.x (running ES 7) the indices are not compatible at all, so we need to reprocess the content and rebuild the indexes completely.

We should consider updating the [docs ](https://docs.craftercms.org/en/4.1/by-role/developer/upgrade/index.html) for clarification about that distinction.
cc @yacdaniel @sumerjabri @alhambrav

**Comment by yacdaniel** [comment]
Verified.
