### ISSUE TITLE
Project creation failing ocasionally due to OpenSearch indexing error in Deployer

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6593]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The creation of projects or sites fails occasionally due to an OpenSearch indexing error in Deployer. 

### Steps to reproduce

Steps:

1. Go to Global Menu.
2. Create a new projects one after the other rapidly.
3. At one point the creation of the site will fail with the following error: 
```
Internal server error: org.craftercms.studio.api.v1.exception.DeployerTargetException: Failed to create site 'test2' ID 'test2' based on blueprint 'org.craftercms.blueprint.editorial'. The deployer targets couldn't be created. Rolling back site creation.
```

### Relevant log output

```shell
Checking the Deployer logs, the following error will appear:

2024-03-01 13:05:16.933  INFO 18908 --- [http-nio-9191-exec-5] impl.pipeline.DefaultUpgradePipelineImpl : ============================================================
2024-03-01 13:05:16.933  INFO 18908 --- [http-nio-9191-exec-5] org.craftercms.deployer.impl.TargetImpl  : Closing target 'test2-authoring'...
2024-03-01 13:05:16.935  INFO 18908 --- [http-nio-9191-exec-5] org.craftercms.deployer.impl.TargetImpl  : Stopping current and pending deployments for target 'test2-authoring'
2024-03-01 13:05:16.935  INFO 18908 --- [http-nio-9191-exec-5] org.craftercms.deployer.impl.TargetImpl  : Releasing resources for target 'test2-authoring'
2024-03-01 13:05:16.996  INFO 18908 --- [http-nio-9191-exec-5] aftercms.deployer.impl.TargetServiceImpl : Executing create hooks for target 'test2-authoring'
2024-03-01 13:05:16.996  INFO 18908 --- [http-nio-9191-exec-5] .impl.lifecycle.CreateIndexLifecycleHook : Creating OpenSearch index for target 'test2-authoring'
2024-03-01 13:05:16.998  INFO 18908 --- [http-nio-9191-exec-5] ensearch.impl.OpenSearchAdminServiceImpl : Creating index test2-authoring_v1
2024-03-01 13:05:16.999  INFO 18908 --- [http-nio-9191-exec-5] ensearch.impl.OpenSearchAdminServiceImpl : Creating alias test2-authoring
2024-03-01 13:05:17.000 ERROR 18908 --- [http-nio-9191-exec-5] cms.deployer.impl.rest.ExceptionHandlers : Request /api/1/target/create_if_not_exists failed with status 500 INTERNAL_SERVER_ERROR
org.craftercms.deployer.api.exceptions.TargetServiceException: Failed to load target for configuration file '/home/juanvasquez/crafter/craftersupport41/craftercms/crafter-authoring/data/deployer/targets/test2-authoring.yaml'; nested exception is org.craftercms.deployer.api.exceptions.DeployerException: Error creating index for target 'test2-authoring'; nested exception is org.craftercms.search.opensearch.exception.OpenSearchException: [test2-authoring] Error creating index test2-authoring_v1
	at org.craftercms.deployer.impl.TargetServiceImpl.loadTarget(TargetServiceImpl.java:494)
	at org.craftercms.deployer.impl.TargetServiceImpl.resolveTargetFromConfigFile(TargetServiceImpl.java:450)
	at org.craftercms.deployer.impl.TargetServiceImpl.createTarget(TargetServiceImpl.java:245)
	at org.craftercms.deployer.impl.rest.TargetController.createTarget(TargetController.java:370)
	at org.craftercms.deployer.impl.rest.TargetController.createTargetIfNotExists(TargetController.java:128)
	at org.craftercms.deployer.impl.rest.TargetController$$FastClassBySpringCGLIB$$b2995acb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	at org.craftercms.deployer.impl.rest.TargetController$$EnhancerBySpringCGLIB$$a7ca3e89.createTargetIfNotExists(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:898)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.craftercms.deployer.api.exceptions.DeployerException: Error creating index for target 'test2-authoring'; nested exception is org.craftercms.search.opensearch.exception.OpenSearchException: [test2-authoring] Error creating index test2-authoring_v1
	at org.craftercms.deployer.impl.lifecycle.CreateIndexLifecycleHook.doExecute(CreateIndexLifecycleHook.java:45)
	at org.craftercms.deployer.impl.lifecycle.AbstractLifecycleHook.execute(AbstractLifecycleHook.java:53)
	at org.craftercms.deployer.impl.TargetServiceImpl.executeCreateHooks(TargetServiceImpl.java:653)
	at org.craftercms.deployer.impl.TargetServiceImpl.loadTarget(TargetServiceImpl.java:483)
	... 64 more
Caused by: org.craftercms.search.opensearch.exception.OpenSearchException: [test2-authoring] Error creating index test2-authoring_v1
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.doCreateIndex(OpenSearchAdminServiceImpl.java:214)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.createIndex(OpenSearchAdminServiceImpl.java:156)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.createIndex(OpenSearchAdminServiceImpl.java:148)
	at org.craftercms.deployer.impl.lifecycle.CreateIndexLifecycleHook.doExecute(CreateIndexLifecycleHook.java:43)
	... 67 more
Caused by: OpenSearchStatusException[OpenSearch exception [type=index_create_block_exception, reason=blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];]]
	at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:209)
	at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2235)
	at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2212)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1931)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1901)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1865)
	at org.opensearch.client.IndicesClient.create(IndicesClient.java:159)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.doCreateIndex(OpenSearchAdminServiceImpl.java:212)
	... 70 more
	Suppressed: org.opensearch.client.ResponseException: method [PUT], host [http://localhost:9201], URI [/test2-authoring_v1?master_timeout=30s&timeout=30s], status line [HTTP/1.1 403 Forbidden]
{"error":{"root_cause":[{"type":"index_create_block_exception","reason":"blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];"}],"type":"index_create_block_exception","reason":"blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];"},"status":403}
		at org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
		at org.opensearch.client.RestClient.performRequest(RestClient.java:345)
		at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
		at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1918)
		... 74 more
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/90878288/55f34557-1b9d-4d4a-b9e1-70c06b089b13)

**Comment by Euquimides** [comment]
Regarding this ticket, important to add that it seems to be reproducible with a fresh clone of Crafter and then creating a new site.

**Comment by jmendeza** [comment]
After checking with @Euquimides, this seems to be the normal OpenSearch behavior when disk utilization goes above configured high watermark (default 90%).
See https://opensearch.org/docs/2.15/install-and-configure/configuring-opensearch/cluster-settings/


> cluster.routing.allocation.disk.watermark.high (String): Controls the high watermark. OpenSearch will attempt to relocate shards away from a node whose disk usage is above the percentage defined. This can also be entered as a ratio value, like 0.85. Finally, this can also be set to a byte value, like 400mb. This setting affects the allocation of all shards. Default is 90%.



Opensearch logs:
```
[2024-10-03T15:27:15,743][WARN ][o.o.c.r.a.DiskThresholdMonitor] [jm-precision-5560] Putting index create block on cluster as all nodes are breaching high disk watermark. Number of nodes above high watermark: 1.
[2024-10-03T15:27:15,744][WARN ][o.o.c.r.a.DiskThresholdMonitor] [jm-precision-5560] high disk watermark [90%] exceeded on [6DxKwOwiTJCoMSFm-Ee-lA][jm-precision-5560][/home/jonathanmendez/dev/repos/develop/ce/crafter-authoring/data/indexes/nodes/0] free: 34.3gb[7.3%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete
```


Watermark can be increased in `bin/opensearch/config/opensearch.yml`, e.g.:
```
cluster.routing.allocation.disk.watermark.high: "95%"
```

cc @sumerjabri

**Comment by Euquimides** [comment]
Hi @sumerjabri ! Should the above solution provided by @jmendeza should be implemented into `OpenSearch` configuration or added as a note in the documentation?

**Comment by sumerjabri** [comment]
@alhambrav please add the low disk issue to a troubleshooting guide. If you're low on disk, you see that issue in the logs, etc.

**Comment by Euquimides** [comment]
Hi @alhambrav ! Just a quick note: increasing the watermark in opensearch configuration might also apply or fix issues with duplication of projects, not only with project creation.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/system-admin/maintenance/troubleshooting.html#low-disk
