### ISSUE TITLE
[studio]Published pages does not appear in the dashboard "Recently Published" widget

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#670]
Published pages does not appear in the dashboard "Recently Published" widget.  To reproduce:

1. Create a new site using the Website_Editorial blueprint
2. Create a new Page Article
3. Publish the newly created page

<img width="1433" alt="screen shot 2017-03-31 at 5 27 52 pm" src="https://cloud.githubusercontent.com/assets/25483966/24570066/8adb5cde-1637-11e7-85e8-868344ce4c63.png">

4. Go to the dashboard to check the "Recently Published" widget, your newly published page is not listed there.

<img width="1430" alt="screen shot 2017-03-31 at 5 21 51 pm" src="https://cloud.githubusercontent.com/assets/25483966/24569974/0e119038-1637-11e7-9cdf-2167876fa42b.png">

5. Check the logs, this is what my log said:

[ERROR] 2017-03-31 17:21:22,598 [Incoming-1,StudioCluster,Vita-Alhambras-MacBook-Pro-35681] [git.GitContentRepository] | Error when publishing site myawesomesite to environment live
org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
object b66952413be2d4a89fddbc94cd82b5e9e39d2877
type commit
tag 2017-03-31T171406-04
tagger PersonIdent[admin admin, evaladmin@example.com, Fri Mar 31 17:21:22 2017 -0400]

TODO: DB: comment}' already exists
	at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:193)
	at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:164)
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.publish(GitContentRepository.java:753)
	at org.craftercms.studio.impl.v1.deployment.EnvironmentDeployer.onEnvironmentDeploymentEvent(EnvironmentDeployer.java:37)
	at org.craftercms.studio.impl.v1.service.event.EventServiceImpl.onEnvironmentDeploymentEvent(EventServiceImpl.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jgroups.blocks.MethodCall.invoke(MethodCall.java:286)
	at org.jgroups.blocks.RpcDispatcher.handle(RpcDispatcher.java:344)
	at org.jgroups.blocks.RequestCorrelator.handleRequest(RequestCorrelator.java:472)
	at org.jgroups.blocks.RequestCorrelator.receiveMessage(RequestCorrelator.java:377)
	at org.jgroups.blocks.RequestCorrelator.receive(RequestCorrelator.java:250)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:684)
	at org.jgroups.JChannel.up(JChannel.java:760)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1033)
	at org.jgroups.stack.Protocol.up(Protocol.java:420)
	at org.jgroups.protocols.RSVP.up(RSVP.java:237)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:182)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:447)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:447)
	at org.jgroups.stack.Protocol.up(Protocol.java:420)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:294)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:474)
	at org.jgroups.protocols.pbcast.NAKACK2.deliverBatch(NAKACK2.java:982)
	at org.jgroups.protocols.pbcast.NAKACK2.removeAndPassUp(NAKACK2.java:912)
	at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:846)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:618)
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:152)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:155)
	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:200)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:310)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:285)
	at org.jgroups.protocols.Discovery.up(Discovery.java:295)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1577)
	at org.jgroups.protocols.TP$3.run(TP.java:1511)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/618
