### ISSUE TITLE
Consider adding a message in the backend about upgrading the database depending of the version

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6999]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When upgrading CrafterCMS from 3.1.x or 4.0.x to 4.2, an upgrade of the database is required. If this isn't made, an error will show up when running the `post-upgrade` script and login to Studio:

```
[ERROR] 2024-06-28T11:34:23,733 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-06-28 11:34:23 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB'). 
[ERROR] 2024-06-28T11:34:23,733 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-06-28 11:34:23 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255). 
[INFO] 2024-06-28T11:34:23,734 [main] [db.DbScriptUpgradeOperation] | Execute the DB script 'upgrade-4.1.6-to-4.1.7.sql' 
[ERROR] 2024-06-28T11:34:23,735 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-06-28 11:34:23 14 [ERROR] Incorrect definition of table mysql.proc: expected column 'definer' at position 11 to have type varchar(, found type char(141). 
```

Right now, the script of `upgrade-target` does not give any indication to upgrade the database before running `post-upgrade` script. Since no message is shown, the user might forget about upgrading the database.

### Describe the solution you'd like

Add some kind of indication or message about upgrading the database in the backend, depending of the version.

**Comment by Euquimides** [comment]
Hi @phuongnq ! While validating this ticket I noticed that it seems that 4.1.x also requires the upgrade of the database as with other versions? When upgrading 4.1.4 -> 4.2, if I don't run the `upgradedb`script, I get the following error:

```
[ERROR] 2024-07-24T11:57:35,563 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB'). 
[ERROR] 2024-07-24T11:57:35,563 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255). 
[INFO] 2024-07-24T11:57:35,580 [main] [pipeline.DefaultUpgradePipelineImpl] | ============================================================ 
[INFO] 2024-07-24T11:57:35,580 [main] [pipeline.DefaultUpgradePipelineImpl] | Starting execution of upgrade pipeline: system 
[INFO] 2024-07-24T11:57:35,580 [main] [pipeline.DefaultUpgradePipelineImpl] | ------- Starting execution of operation UpdateVersionUpgradeOperation ------- 
[ERROR] 2024-07-24T11:57:35,584 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB'). 
[ERROR] 2024-07-24T11:57:35,584 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255). 
[INFO] 2024-07-24T11:57:35,586 [main] [providers.DbVersionProvider] | Database version updated to '4.2-t' 
[INFO] 2024-07-24T11:57:35,586 [main] [pipeline.DefaultUpgradePipelineImpl] | ------- Execution of operation UpdateVersionUpgradeOperation completed ------- 
[INFO] 2024-07-24T11:57:35,586 [main] [pipeline.DefaultUpgradePipelineImpl] | ------- Starting execution of operation DbScriptUpgradeOperation ------- 
[ERROR] 2024-07-24T11:57:35,586 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB'). 
[ERROR] 2024-07-24T11:57:35,587 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255). 
[INFO] 2024-07-24T11:57:35,588 [main] [db.DbScriptUpgradeOperation] | Execute the DB script '4.1.5-to-4.2.0.sql' 
[WARN] 2024-07-24T11:57:35,591 [main] [server.ErrorPacket] | Error: 1728-HY000: Cannot load from mysql.proc. The table is probably corrupted 
[ERROR] 2024-07-24T11:57:35,591 [Exec Stream Pumper] [exec.ManagedProcess] | mariadbd: 2024-07-24 11:57:35 14 [ERROR] Incorrect definition of table mysql.proc: expected column 'definer' at position 11 to have type varchar(, found type char(141). 
Error executing: /*
 * Copyright (C) 2007-2023 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
CREATE PROCEDURE deleteSiteRelatedItems(
    IN siteId VARCHAR(50))
BEGIN
	DECLARE id BIGINT(20);
    IF EXISTS (SELECT (1) FROM site WHERE site_id = siteId AND deleted = 0)
    THEN
		SELECT s.id into id
		FROM site s
		WHERE site_id = siteId AND deleted = 0;
        DELETE FROM item WHERE site_id = id;
        DELETE FROM user_properties WHERE site_id = id;
        DELETE FROM dependency WHERE site = siteId;
        DELETE FROM publish_request WHERE site = siteId;
        DELETE FROM navigation_order_sequence WHERE site = siteId;
        DELETE FROM gitlog WHERE site_id = siteId;
        DELETE FROM remote_repository WHERE site_id = siteId;
        DELETE FROM audit WHERE site_id = id;
    END IF;
END
.  Cause: java.sql.SQLException: (conn=14) Cannot load from mysql.proc. The table is probably corrupted
[ERROR] 2024-07-24T11:57:35,591 [main] [db.DbScriptUpgradeOperation] | Failed to execute the DB script '4.1.5-to-4.2.0.sql' 
org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: /*
 * Copyright (C) 2007-2023 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
CREATE PROCEDURE deleteSiteRelatedItems(
    IN siteId VARCHAR(50))
BEGIN
	DECLARE id BIGINT(20);
    IF EXISTS (SELECT (1) FROM site WHERE site_id = siteId AND deleted = 0)
    THEN
		SELECT s.id into id
		FROM site s
		WHERE site_id = siteId AND deleted = 0;
        DELETE FROM item WHERE site_id = id;
        DELETE FROM user_properties WHERE site_id = id;
        DELETE FROM dependency WHERE site = siteId;
        DELETE FROM publish_request WHERE site = siteId;
        DELETE FROM navigation_order_sequence WHERE site = siteId;
        DELETE FROM gitlog WHERE site_id = siteId;
        DELETE FROM remote_repository WHERE site_id = siteId;
        DELETE FROM audit WHERE site_id = id;
    END IF;
END
.  Cause: java.sql.SQLException: (conn=14) Cannot load from mysql.proc. The table is probably corrupted
	at org.apache.ibatis.jdbc.ScriptRunner.executeLineByLine(ScriptRunner.java:161) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:121) ~[mybatis-3.5.16.jar:3.5.16]
	at org.craftercms.studio.impl.v2.upgrade.operations.db.DbScriptUpgradeOperation.doExecute(DbScriptUpgradeOperation.java:125) [classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.operations.AbstractUpgradeOperation.doExecute(AbstractUpgradeOperation.java:103) [classes/:4.2.0-SNAPSHOT]
	at org.craftercms.commons.upgrade.impl.operations.AbstractUpgradeOperation.execute(AbstractUpgradeOperation.java:96) [crafter-commons-upgrade-manager-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.craftercms.commons.upgrade.impl.pipeline.DefaultUpgradePipelineImpl.execute(DefaultUpgradePipelineImpl.java:82) [crafter-commons-upgrade-manager-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.upgradeDatabaseAndConfiguration(StudioUpgradeManagerImpl.java:120) [classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.startUpgrade(StudioUpgradeManagerImpl.java:283) [classes/:4.2.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvent(ApplicationListenerMethodAdapter.java:341) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvents(ApplicationListenerMethodAdapter.java:334) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.handleResult(ApplicationListenerMethodAdapter.java:317) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:239) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvent(ApplicationListenerMethodAdapter.java:341) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvents(ApplicationListenerMethodAdapter.java:334) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.handleResult(ApplicationListenerMethodAdapter.java:317) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:239) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvent(ApplicationListenerMethodAdapter.java:341) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvents(ApplicationListenerMethodAdapter.java:334) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.handleResult(ApplicationListenerMethodAdapter.java:317) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:239) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvent(ApplicationListenerMethodAdapter.java:341) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.publishEvents(ApplicationListenerMethodAdapter.java:334) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.handleResult(ApplicationListenerMethodAdapter.java:317) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:239) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:385) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:993) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:628) [spring-context-6.1.11.jar:6.1.11]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:394) [spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:274) [spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:102) [spring-web-6.1.11.jar:6.1.11]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3997) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4424) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599) [catalina.jar:10.1.26]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:654) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911) [catalina.jar:10.1.26]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:10.1.26]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) [?:?]
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:385) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:332) [catalina.jar:10.1.26]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:776) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) [catalina.jar:10.1.26]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) [catalina.jar:10.1.26]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:10.1.26]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874) [catalina.jar:10.1.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:757) [catalina.jar:10.1.26]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) [bootstrap.jar:10.1.26]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473) [bootstrap.jar:10.1.26]
Caused by: java.sql.SQLException: (conn=14) Cannot load from mysql.proc. The table is probably corrupted
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:306) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:189) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1235) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1174) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1093) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1017) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:1034) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.Statement.execute(Statement.java:1163) ~[mariadb-java-client-3.4.1.jar:?]
	at org.mariadb.jdbc.Statement.execute(Statement.java:502) ~[mariadb-java-client-3.4.1.jar:?]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182) ~[commons-dbcp2-2.12.0.jar:2.12.0]
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182) ~[commons-dbcp2-2.12.0.jar:2.12.0]
	at org.apache.ibatis.jdbc.ScriptRunner.executeStatement(ScriptRunner.java:250) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.jdbc.ScriptRunner.handleLine(ScriptRunner.java:225) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.jdbc.ScriptRunner.executeLineByLine(ScriptRunner.java:154) ~[mybatis-3.5.16.jar:3.5.16]
	... 101 more
[INFO] 2024-07-24T11:57:35,598 [main] [pipeline.DefaultUpgradePipelineImpl] | ------- Execution of operation DbScriptUpgradeOperation completed ------- 
[WARN] 2024-07-24T11:57:35,598 [main] [support.XmlWebApplicationContext] | Exception encountered during context initialization - cancelling refresh attempt: java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl]
Method [public void org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.startUpgrade() throws org.craftercms.commons.upgrade.exception.UpgradeException,org.craftercms.commons.entitlements.exception.EntitlementException,org.craftercms.commons.config.ConfigurationException]
Resolved arguments: 
```
Once I run the `upgradedb` script, the error doesn't show anymore and Studio seems to start correctly. Could you please take a look at this? Thanks!

**Comment by phuongnq** [comment]
Thanks @Euquimides I sent PR to add 4.1.x to the list showing the upgrade db instruction.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
