### ISSUE TITLE
Fitness BP drop targets accepting incorrect components

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7046]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In the Fitness BP, drop targets are accepting incorrect components, which then returns an FTL error. 

It is expected from the fix that the BP's drop target effectively accepts only its assigned components. 

### Steps to reproduce

Steps:

1. Create a new project with Fitness BP.
2. Using the right sidebar, create content by adding a `Service` component near `Workout` section of the BP. 
3. See the issue: the component will be accepted but this will return an FTL error in the BP. 

### Relevant log output

```shell
18-Jul-2024 11:26:01.905 SEVERE [http-nio-8080-exec-5] freemarker.log._JULLoggerFactory$JULLogger.error Error executing FreeMarker template
	FreeMarker template error:
	No component template defined in SiteItem[storeName='e817e99e-79f4-4be1-bb09-aac2a5c67a4b.xml', storeUrl='/site/components/component-services/e817e99e-79f4-4be1-bb09-aac2a5c67a4b.xml', folder=false]

	----
	FTL stack trace ("~" means nesting-related):
	- Failed at: @renderComponent component=section  [in template "templates/web/entry.ftl" at line 59, column 17]
	~ Reached through: #nested  [in template "templates/system/common/ice.ftl" in macro "div" at line 126, column 205]
	~ Reached through: #nested  [in template "templates/system/common/ice.ftl" in macro "tag" at line 47, column 18]
	~ Reached through: @tag $tag="div" $model=$model $field=...  [in template "templates/system/common/ice.ftl" in macro "div" at line 126, column 3]
	- Reached through: @crafter.div $field="pageSections_o" ...  [in template "templates/web/entry.ftl" at line 58, column 15]
	~ Reached through: #nested  [in template "templates/system/common/ice.ftl" in macro "div" at line 126, column 205]
	~ Reached through: #nested  [in template "templates/system/common/ice.ftl" in macro "tag" at line 47, column 18]
	~ Reached through: @tag $tag="div" $model=$model $field=...  [in template "templates/system/common/ice.ftl" in macro "div" at line 126, column 3]
	- Reached through: @crafter.div $field="pageSections_o"  [in template "templates/web/entry.ftl" at line 54, column 9]
	----

	Java stack trace (for programmers):
	----
	freemarker.template.TemplateException: [... Exception message was already printed; see it above ...]
		at org.craftercms.engine.freemarker.RenderComponentDirective.getComponentTemplateName(RenderComponentDirective.java:271)
		at org.craftercms.engine.freemarker.RenderComponentDirective.getTemplate(RenderComponentDirective.java:260)
		at org.craftercms.engine.freemarker.RenderComponentDirective.execute(RenderComponentDirective.java:121)
		at freemarker.core.Environment.visit(Environment.java:461)
		at freemarker.core.UnifiedCall.accept(UnifiedCall.java:101)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeNestedContent(Environment.java:630)
		at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeNestedContent(Environment.java:630)
		at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.visit(Environment.java:407)
		at freemarker.core.BlockAssignment.accept(BlockAssignment.java:55)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:886)
		at freemarker.core.Environment.invokeMacro(Environment.java:822)
		at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:886)
		at freemarker.core.Environment.invokeMacro(Environment.java:822)
		at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
		at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
		at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
		at freemarker.core.Environment.visitIteratorBlock(Environment.java:654)
		at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
		at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
		at freemarker.core.Environment.visit(Environment.java:344)
		at freemarker.core.Environment.visit(Environment.java:386)
		at freemarker.core.Environment.invokeNestedContent(Environment.java:630)
		at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeNestedContent(Environment.java:630)
		at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.visit(Environment.java:407)
		at freemarker.core.BlockAssignment.accept(BlockAssignment.java:55)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:886)
		at freemarker.core.Environment.invokeMacro(Environment.java:822)
		at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
		at freemarker.core.Environment.visit(Environment.java:380)
		at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:886)
		at freemarker.core.Environment.invokeMacro(Environment.java:822)
		at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
		at freemarker.core.Environment.visit(Environment.java:344)
		at freemarker.core.Environment.visit(Environment.java:350)
		at freemarker.core.Environment.process(Environment.java:323)
		at freemarker.template.Template.process(Template.java:383)
		at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:365)
		at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:298)
		at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:252)
		at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:181)
		at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
		at org.craftercms.engine.view.UserAgentAwareCrafterPageView.renderActualView(UserAgentAwareCrafterPageView.java:56)
		at org.craftercms.engine.view.CrafterPageView.renderMergedOutputModel(CrafterPageView.java:160)
		at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
		at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1431)
		at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1167)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.servlet.filter.HttpHeadersRewriteFilter.doFilterInternal(HttpHeadersRewriteFilter.java:87)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.commons.web.AddResponseHeaderFilter.doFilterInternal(AddResponseHeaderFilter.java:62)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.scripting.impl.ScriptFilter.doFilter(ScriptFilter.java:106)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
		at org.craftercms.engine.util.spring.security.ForbiddenUrlsFilter.doFilter(ForbiddenUrlsFilter.java:57)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150)
		at org.craftercms.engine.util.spring.security.ConfigAwarePreAuthenticationFilter.doFilter(ConfigAwarePreAuthenticationFilter.java:77)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150)
		at org.craftercms.engine.util.spring.security.ConfigAwarePreAuthenticationFilter.doFilter(ConfigAwarePreAuthenticationFilter.java:77)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.craftercms.engine.util.spring.security.ConfigAwarePreAuthenticationFilter.doFilter(ConfigAwarePreAuthenticationFilter.java:80)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.url.rewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:74)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.servlet.filter.HttpProxyFilter.doFilterInternal(HttpProxyFilter.java:145)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
		at org.craftercms.engine.util.spring.security.preview.PreviewAccessTokenFilter.doFilter(PreviewAccessTokenFilter.java:88)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:53)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:77)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:78)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:70)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.security.web.header.HeaderWriterFilter.doHeadersBefore(HeaderWriterFilter.java:82)
		at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:72)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Screenshots and/or videos

https://github.com/user-attachments/assets/901d2254-8a5f-4af2-97b7-c1679c47e803

**Comment by sumerjabri** [comment]
Is this symptomatic of something in XB?

**Comment by rart** [comment]
The issue is assets have names with spaces ( #7068 ).

@jvega190 please fix asset names on the BP and increment version.

**Comment by jvega190** [comment]
@rart there were no assets with spaces in its names. Though there was an issue with a datasource where the services component was not supposed to be in the allowed types (comments in PR)

**Comment by rart** [comment]
Sorry, I confused the tickets. It is https://github.com/craftercms/craftercms/issues/7055 the one that I meant to comment around the assets and assign.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
