### ISSUE TITLE
siteName variable is not replaced in serverless target

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#7086]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`siteName` variable is not replaced when deployer runs the target.

### Steps to reproduce

Steps:

1. Enable Studio serverless delivery
2. Create a project and publish to live
3. See the issue in deployer logs

### Relevant log output

```shell
2024-07-24 14:56:33.247  INFO 616442 --- [deployment-3] org.craftercms.deployer.impl.TargetImpl  : Creating deployment pipeline for target 'wordify2-s
erverless-delivery'                                                                                                                                   
2024-07-24 14:56:33.269 ERROR 616442 --- [deployment-3] org.craftercms.deployer.impl.TargetImpl  : Failed to init target 'wordify2-serverless-delivery
'                                                                                                                                                     
org.craftercms.deployer.api.exceptions.DeployerException: Failed to initialize pipeline processor 's3SyncProcessor'; nested exception is java.lang.Ill
egalArgumentException: Illegal character in path at index 28: s3://authoring-bucket/sites/{siteName}/                                                 
        at org.craftercms.deployer.impl.DeploymentPipelineFactoryImpl.getPipeline(DeploymentPipelineFactoryImpl.java:73)                              
        at org.craftercms.deployer.impl.TargetImpl.init(TargetImpl.java:199)                                                                          
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)                                                  
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)                                                  
        at java.base/java.lang.Thread.run(Thread.java:1583)                                                                                           Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 28: s3://authoring-bucket/sites/{siteName}/                         
        at java.base/java.net.URI.create(URI.java:932)                                                                                                
        at org.craftercms.deployer.impl.processors.aws.AbstractS3Processor.doInit(AbstractS3Processor.java:80)                                        
        at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.doInit(S3SyncProcessor.java:86)                                                
        at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.init(AbstractDeploymentProcessor.java:128)                             
        at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.init(AbstractMainDeploymentProcessor.java:44)                      
        at org.craftercms.deployer.impl.DeploymentPipelineFactoryImpl.getPipeline(DeploymentPipelineFactoryImpl.java:67)                              
        ... 4 more                                                                                                                                    
Caused by: java.net.URISyntaxException: Illegal character in path at index 28: s3://authoring-bucket/sites/{siteName}/                                
        at java.base/java.net.URI$Parser.fail(URI.java:2995)                                                                                          
        at java.base/java.net.URI$Parser.checkChars(URI.java:3166)                                                                                    
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248)                                                                             
        at java.base/java.net.URI$Parser.parse(URI.java:3196)                                                                                         
        at java.base/java.net.URI.<init>(URI.java:645)                                                                                                
        at java.base/java.net.URI.create(URI.java:930)
        ... 9 more
```

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
