### ISSUE TITLE
Workflow is not cancelled when renaming an item's parent

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7122]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Workflow is not cancelled (or even informed to the user) when renaming an in-workflow content item's parent.
When renaming a page or a folder, workflow should be cancelled for any scheduled children.
This should happen in any rename/move operation:

- Rename
- Edit page URL
- Cut-paste

### Steps to reproduce

Steps:

1. Create a new site based on editorial blueprint
2. Initial publish
3. Edit some asset. e.g: /static-assets/css/main.css
4. Schedule the edited asset to be published in the future.
5. Rename /static-assets/css folder
6. Notice that the UI does not alert about cancelling workflow for the scheduled item. The publish request indeed remains in the DB and is eventually processed by the publisher.
7. When trying to publish the item, operation fails with this error in the logs:
```
[WARN] 2024-08-07T12:30:11,656 [studio.clockTaskExecutor-12] [deployment.PublishingManagerImpl] | Item in site 'ed1' path '/static-assets/css/main.css' doesn't exist in the database nor the git repository. Skipping publishing of this item. 
[ERROR] 2024-08-07T12:30:11,662 [studio.clockTaskExecutor-12] [job.StudioPublisherTask] | Failed to publish '1' items in site 'ed1' 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:215) ~[classes/:4.1.6-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:128) ~[classes/:4.1.6-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:72) ~[classes/:4.1.6-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:89) ~[classes/:4.1.6-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by jmendeza** [comment]
In 5.0, the back-end is not accepting move/rename operations on items on workflow. Since move/rename effect extends to the children, the operation will fail if either the item itself or any children is "in workflow" (pending approval or scheduled).
The UI handles some of those cases and presents the user the list of affected packages. However, it does not allow to cancel those packages in order to proceed with the operation.
@rart @sumerjabri

**Comment by jvega190** [comment]
@sumerjabri @jmendeza I saw a couple of issues when testing this ticket:
- https://github.com/craftercms/craftercms/issues/7832: Site policy is not applying when creating folders (and probably other content?)
- https://github.com/craftercms/craftercms/issues/6112: When creating a folder with the same name as an existing one but uppercase (e.g. `test` existing, create `TEST`) in a path with no lowercase site policy, the new folder 'replaces' the original one. (both folders are in the repo, but only one in the DB). That's because the `content-exists` API returns false (case sensitive)

**Comment by sumerjabri** [comment]
The site policy ticket: https://github.com/craftercms/craftercms/issues/7832

**Comment by yacdaniel** [comment]
Verified fixed in `v5.0.0-SNAPSHOT` the worflow package affected is cancelled.
