### ISSUE TITLE
Log error on content write

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7157]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Studio logs display a JSON parse error on content write. 
Content update seems successful.

### Steps to reproduce

Steps:

1. Create a new site based on editorial
2. Edit any content
3. Save
4. See the error in the logs

### Relevant log output

```shell
[http-nio-8080-exec-2] INFO org.craftercms.studio.impl.v1.web.security.access.StudioPublishingAPIAccessDecisionVoter - Failed to parse request as JSON
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2648)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:685)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2055)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:780)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4992)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at org.craftercms.studio.impl.v1.web.security.access.StudioPublishingAPIAccessDecisionVoter.voteInternal(StudioPublishingAPIAccessDecisionVoter.java:70)
	at org.craftercms.studio.impl.v1.web.security.access.StudioAbstractAccessDecisionVoter.vote(StudioAbstractAccessDecisionVoter.java:61)
	at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:72)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.attemptAuthorization(AbstractSecurityInterceptor.java:253)
```

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v4.2. Thank you! Closing this ticket.
