### ISSUE TITLE
Publisher fails due to index 0 out of bounds exception

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#7205]
### CI Number

5289

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The publisher was disabled due to it not being able to handle the following:

[ERROR] 2024-08-22T14:40:35,535 [studio.clockTaskExecutor-39] [job.StudioPublisherTask] | Failed to publish items in site 
 java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
 	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
 	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
 	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
 	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
 	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:217) ~[classes/:4.1.3E]

### Relevant log output

```shell
[ERROR] 2024-08-22T14:40:35,535 [studio.clockTaskExecutor-39] [job.StudioPublisherTask] | Failed to publish items in site 
 java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
 	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
 	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
 	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
 	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
 	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:217) ~[classes/:4.1.3E]
```

**Comment by russdanner** [comment]
4.3.0 re-factors the publisher. Let's review this condition and establish that it cannot happen in the refactor.

**Comment by sumerjabri** [comment]
To be tested after the new publisher is merged. Assign to @russdanner when ready.

**Comment by yacdaniel** [comment]
Verified fixed in `v5.0.0-SNAPSHOT`  Tested a condition where `StudioPublisherTask.java:217  String author = itemsToDeploy.get(0).getUser();` `itemsToDeploy`  had 0 items in the request.
