### ISSUE TITLE
`elasticsearch` variable not longer available

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7242]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When we moved from ES to OS, Crafter kept the `elasticsearch` variable available for backwards compatibility. This variable seems to have been removed from 4.2, which will cause existing sites to need an extensive migration of their search queries when upgrading to 4.2. For now it will be good if we kept the `elasticsearch` service, and have clients slowly migrate to the new service, before we completely remove the old one.

### Steps to reproduce

Steps:

2. Click on '...'
3. Scroll down to '...'
4. See the issue

### Relevant log output

```shell
Caused by: groovy.lang.MissingPropertyException: No such property: elasticsearch for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:61) ~[groovy-4.0.22.jar:4.0.22]
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:281) ~[script-security-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:390) ~[groovy-sandbox-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:394) ~[groovy-sandbox-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.22.jar:4.0.22]
	at entry.run(entry.groovy:19) ~[?:?]
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:68) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.engine.view.CrafterPageView.executeScript(CrafterPageView.java:165) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.engine.view.CrafterPageView.renderMergedOutputModel(CrafterPageView.java:146) ~[classes/:4.2.0-SNAPSHOT]
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314) ~[spring-webmvc-6.1.12.jar:6.1.12]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1432) ~[spring-webmvc-6.1.12.jar:6.1.12]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1168) ~[spring-webmvc-6.1.12.jar:6.1.12]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106) ~[spring-webmvc-6.1.12.jar:6.1.12]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.12.jar:6.1.12]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.12.jar:6.1.12]
	... 165 more
```

**Comment by sumerjabri** [comment]
To be verified in CC3.

**Comment by avasquez614** [comment]
Verified in 4.2
