### ISSUE TITLE
Publish a blacklist matched item throw java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#7308]
### CI Number

5318

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Publish an item marked as a blacklist for publishing throw an error and the publisher is disabled

### Steps to reproduce

Steps:

1. Configure the publishing blacklist as mentioned in the doc: https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/index.html#publishing-blacklist to blacklist the Home item:

```
# Publishing blacklist configuration, items matching regexes on this list will never be published
studio.configuration.publishing.blacklist.regex: /site/website/index.xml
```

2. Start Studio and create a new site from Editorial BP
3. Do the initial publish
4. Edit Home page and publish again
5. Notice the error from catalina.out and the publisher is disabled. This is not an expected result

### Relevant log output

```shell
[INFO] 2024-09-20T15:05:36,877 [studio.clockTaskExecutor-10] [job.StudioPublisherTask] | Publish started in site 'ed' for target 'live' with '1' items ready to be published 
[INFO] 2024-09-20T15:05:36,879 [studio.clockTaskExecutor-10] [job.StudioPublisherTask] | Publish '1' items in site 'ed' to target 'live' 
[ERROR] 2024-09-20T15:05:36,887 [studio.clockTaskExecutor-10] [job.StudioPublisherTask] | Failed to publish '1' items in site 'ed' 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:215) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:128) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:72) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:89) ~[classes/:4.1.9-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[ERROR] 2024-09-20T15:05:36,902 [studio.clockTaskExecutor-10] [job.StudioPublisherTask] | Failed to publish items in site 'ed' 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.doPublishing(StudioPublisherTask.java:215) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioPublisherTask.executeInternal(StudioPublisherTask.java:128) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockTask.execute(StudioClockTask.java:72) ~[classes/:4.1.9-SNAPSHOT]
	at org.craftercms.studio.impl.v2.job.StudioClockExecutor.lambda$executeTasks$0(StudioClockExecutor.java:89) ~[classes/:4.1.9-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Screenshots and/or videos

![Screenshot from 2024-09-20 15-12-35](https://github.com/user-attachments/assets/db57c27b-0119-4369-a764-115e646ad70e)

**Comment by russdanner** [comment]
RD: Reviewed 1/24/25

**Comment by jmendeza** [comment]
This does not seem to be failing now in `develop`. Would you please confirm, @phuongnq ?

**Comment by phuongnq** [comment]
confirmed
