### ISSUE TITLE
Big site creation takes much longer than 4.1

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7326]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Creating a site with a lot of items (around 450k items) is taking several hours longer in 4.2 than 4.1 

### Steps to reproduce

Steps:

1. Try to create a site based on a repo that has around 450k items (I can privately provide that repo if necessary).
2. Track the time the site creation takes. For the site in question, it's been 19 hours and it's still creating, in specific it's still on the item insertion phase.

We were able to determine that the site is stuck in this call stack attached below

### Relevant log output

```shell
"http-nio-8080-exec-36" #505 [1230] daemon prio=5 os_prio=0 cpu=3609045.49ms elapsed=44163.68s tid=0x00007f6ce19377f0 nid=1230 runnable  [0x00007f6ccd7e9000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.poll(java.base@21.0.4/Native Method)
	at sun.nio.ch.NioSocketImpl.park(java.base@21.0.4/NioSocketImpl.java:191)
	at sun.nio.ch.NioSocketImpl.timedRead(java.base@21.0.4/NioSocketImpl.java:280)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@21.0.4/NioSocketImpl.java:304)
	at sun.nio.ch.NioSocketImpl.read(java.base@21.0.4/NioSocketImpl.java:346)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@21.0.4/NioSocketImpl.java:796)
	at java.net.Socket$SocketInputStream.read(java.base@21.0.4/Socket.java:1099)
	at java.io.BufferedInputStream.fill(java.base@21.0.4/BufferedInputStream.java:291)
	at java.io.BufferedInputStream.read1(java.base@21.0.4/BufferedInputStream.java:347)
	at java.io.BufferedInputStream.implRead(java.base@21.0.4/BufferedInputStream.java:420)
	at java.io.BufferedInputStream.read(java.base@21.0.4/BufferedInputStream.java:399)
	at org.mariadb.jdbc.client.socket.impl.PacketReader.readReusablePacket(PacketReader.java:62)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:164)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:1235)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:1174)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:1093)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:1017)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:1034)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1163)
	at org.mariadb.jdbc.Statement.execute(Statement.java:502)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:182)
	at org.apache.ibatis.jdbc.ScriptRunner.executeStatement(ScriptRunner.java:250)
	at org.apache.ibatis.jdbc.ScriptRunner.handleLine(ScriptRunner.java:225)
	at org.apache.ibatis.jdbc.ScriptRunner.executeLineByLine(ScriptRunner.java:154)
	at org.apache.ibatis.jdbc.ScriptRunner.runScript(ScriptRunner.java:121)
	at org.craftercms.studio.impl.v2.dal.StudioDBScriptRunnerImpl.execute(StudioDBScriptRunnerImpl.java:99)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.processCreatedFiles(SiteServiceImpl.java:466)
```

**Comment by avasquez614** [comment]
Verified fix
