### ISSUE TITLE
Duplicate fails on a serverless deployment when using the aws-cloudformed-s3 target template

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7331]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you have a serverless deployment, and Studio configured to create Deployer targets with the `aws-cloudformed-s3` template, Studio seems to timeout while waiting for the Deployer to create the target.

### Steps to reproduce

Steps:

1. Configure a serverless Deployment, making sure Studio has this property set
```
# The template name for serverless deployer targets (supported: aws-s3, aws-cloudformed-s3)
studio.serverless.delivery.deployer.target.template: aws-cloudformed-s3
```
3. Create a site
4. Try to duplicate the site. It should fail
5. See the timeout error in the log

### Relevant log output

```
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9191/api/1/target/duplicate/s3-us-east-1/editorial": Read timed out
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:915) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:895) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:730) ~[spring-web-6.1.13.jar:6.1.13]
	at org.craftercms.studio.impl.v2.deployment.AbstractDeployer.doDuplicateTarget(AbstractDeployer.java:237) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.deployment.ServerlessDeliveryDeployer.duplicateTargets(ServerlessDeliveryDeployer.java:74) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.deployment.CompositeDeployer.duplicateTargets(CompositeDeployer.java:78) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.service.site.internal.SitesServiceInternalImpl.doDuplicate(SitesServiceInternalImpl.java:506) ~[classes/:4.2.0-SNAPSHOT]
	... 169 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:250) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:56) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:331) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:193) ~[httpcore5-5.3.jar:5.3]
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.lambda$execute$0(InternalExecRuntime.java:236) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:791) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:233) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:121) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:199) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:150) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:113) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:110) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:174) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:87) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient5-5.4.jar:5.4]
	at org.apache.hc.client5.http.classic.HttpClient.executeOpen(HttpClient.java:183) ~[httpclient5-5.4.jar:5.4]
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:99) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:70) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:889) ~[spring-web-6.1.13.jar:6.1.13]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:730) ~[spring-web-6.1.13.jar:6.1.13]
	at org.craftercms.studio.impl.v2.deployment.AbstractDeployer.doDuplicateTarget(AbstractDeployer.java:237) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.deployment.ServerlessDeliveryDeployer.duplicateTargets(ServerlessDeliveryDeployer.java:74) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.deployment.CompositeDeployer.duplicateTargets(CompositeDeployer.java:78) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.service.site.internal.SitesServiceInternalImpl.doDuplicate(SitesServiceInternalImpl.java:506) ~[classes/:4.2.0-SNAPSHOT]
	... 169 more
```

**Comment by jmendeza** [comment]
Added configuration property for deployer http requests response timeout, default to 5 minutes (previously it was timing out after 3m)
```
# Response timeout in seconds for deployer http requests
studio.deployer.request.timeoutSeconds: 300
```
We might want to document this property @sumerjabri @alhambrav

**Comment by avasquez614** [comment]
Verified
