### ISSUE TITLE
Deployer upload to S3 fails on a publish all in serverless target

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7338]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When doing a reprocess all on a serverless target, Deployer tries to upload files to S3 that are actually blobs (so the file doesn't exist in the filesystem, just a `.blob`)

### Steps to reproduce

Steps:

1. Configure Studio/Deployer for serverless
2. Create a site in Studio so a serverless target is created in Deployer
3. Do a publish all.
4. Observer how the deployment of the target fails with a file not found issue

### Relevant log output

```shell
ion: java.nio.file.NoSuchFileException: /opt/crafter/data/repos/aws/craftercmscom/static-assets/CrafterSquare.svg
	at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.uploadFiles(S3SyncProcessor.java:144)
	at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.doMainProcess(S3SyncProcessor.java:105)
	at org.craftercms.deployer.impl.processors.AbstractMainDeploymentProcessor.doExecute(AbstractMainDeploymentProcessor.java:57)
	at org.craftercms.deployer.impl.processors.AbstractDeploymentProcessor.execute(AbstractDeploymentProcessor.java:169)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.executeProcessors(DeploymentPipelineImpl.java:101)
	at org.craftercms.deployer.impl.DeploymentPipelineImpl.execute(DeploymentPipelineImpl.java:72)
	at org.craftercms.deployer.impl.TargetImpl$DeploymentTask.run(TargetImpl.java:445)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /opt/crafter/data/repos/aws/craftercmscom/static-assets/CrafterSquare.svg
	at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:110)
	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
	at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody.<init>(FileAsyncRequestBody.java:77)
	at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody.<init>(FileAsyncRequestBody.java:52)
	at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody$DefaultBuilder.build(FileAsyncRequestBody.java:238)
	at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody$DefaultBuilder.build(FileAsyncRequestBody.java:197)
	at software.amazon.awssdk.transfer.s3.internal.GenericS3TransferManager.uploadFile(GenericS3TransferManager.java:184)
	at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.lambda$uploadFiles$1(S3SyncProcessor.java:137)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.uploadFiles(S3SyncProcessor.java:138)
	... 11 more
Caused by: java.nio.file.NoSuchFileException: /opt/crafter/data/repos/aws/craftercmscom/static-assets/CrafterSquare.svg
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
	at java.base/java.nio.file.Files.size(Files.java:2462)
	at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody.lambda$new$0(FileAsyncRequestBody.java:77)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
	... 26 more
```

**Comment by jmendeza** [comment]
Updated to handle the not-found scenario when a .blob exists for the path.
Updated logging.
Now it will not stop when there is an error, which is more consistent with 4.1 behavior.

**Comment by avasquez614** [comment]
Verified
