### ISSUE TITLE
Duplicate of a big site fails when using AWS OpenSearch

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7377]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

When using an AWS OpenSearch and trying to duplicate the a big site (> 400k items), duplicating the OpenSearch indices fails with a weird exception

### Steps to reproduce

Steps:

1. Make sure you have configure Studio to use an AWS OpenSearch cluster
2. Create a site with > 400k items
3. Try to duplicate the site
4. After waiting some time, duplicate fails. If you check the Deployer log, you should see and exception like the one attached

### Relevant log output

```shell
org.craftercms.deployer.api.exceptions.TargetServiceException: Failed to load target for configuration file '/opt/crafter/data/deployer/targets/pcom-development-42-dup-authoring.yaml'; nested exception is OpenSearchStatusException[Unable to parse response body]; nested: ResponseException[method [POST], host [https://search-test-opensearch-XXXYYYZZZ.us-east-1.es.amazonaws.com.us-east-1.es.amazonaws.com], URI [/_reindex?scroll=5m&slices=1&refresh=true&requests_per_second=-1&wait_for_completion=true&timeout=1m], status line [HTTP/1.1 502 Bad Gateway]
{
  "message": "Empty or invalid response",
}
];
	at org.craftercms.deployer.impl.TargetServiceImpl.loadTarget(TargetServiceImpl.java:418)
	at org.craftercms.deployer.impl.TargetServiceImpl.resolveTargetFromConfigFile(TargetServiceImpl.java:372)
	at org.craftercms.deployer.impl.TargetServiceImpl.duplicateTarget(TargetServiceImpl.java:307)
	at org.craftercms.deployer.impl.rest.TargetController.duplicateTarget(TargetController.java:407)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:174)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.craftercms.deployer.impl.rest.TargetController$$SpringCGLIB$$0.duplicateTarget(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: OpenSearchStatusException[Unable to parse response body]; nested: ResponseException[method [POST], host [https://search-test-opensearch-XXXYYYZZZ.us-east-1.es.amazonaws.com.us-east-1.es.amazonaws.com], URI [/_reindex?scroll=5m&slices=1&refresh=true&requests_per_second=-1&wait_for_completion=true&timeout=1m], status line [HTTP/1.1 502 Bad Gateway]
{
  "message": "Empty or invalid response",
}
];
	at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2215)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1931)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1884)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1852)
	at org.opensearch.client.RestHighLevelClient.reindex(RestHighLevelClient.java:399)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.doReindex(OpenSearchAdminServiceImpl.java:332)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.doDuplicateIndex(OpenSearchAdminServiceImpl.java:372)
	at org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl.duplicateIndex(OpenSearchAdminServiceImpl.java:365)
	at org.craftercms.deployer.impl.lifecycle.DuplicateIndexHook.doExecute(DuplicateIndexHook.java:48)
	at org.craftercms.deployer.impl.lifecycle.AbstractLifecycleHook.execute(AbstractLifecycleHook.java:53)
	at org.craftercms.deployer.impl.TargetServiceImpl.executeDuplicateHooks(TargetServiceImpl.java:576)
	at org.craftercms.deployer.impl.TargetServiceImpl.loadTarget(TargetServiceImpl.java:406)
	... 66 more
	Suppressed: ParsingException[Failed to parse object: expecting field with name [error] but found [message]]
		at org.opensearch.core.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:63)
		at org.opensearch.OpenSearchException.failureFromXContent(OpenSearchException.java:657)
		at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:202)
		at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2235)
		at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2212)
		... 77 more
Caused by: org.opensearch.client.ResponseException: method [POST], host [https://search-test-opensearch-XXXYYYZZZ.us-east-1.es.amazonaws.com.us-east-1.es.amazonaws.com], URI [/_reindex?scroll=5m&slices=1&refresh=true&requests_per_second=-1&wait_for_completion=true&timeout=1m], status line [HTTP/1.1 502 Bad Gateway]
{
  "message": "Empty or invalid response",
}

	at org.opensearch.client.RestClient.convertResponse(RestClient.java:479)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:371)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:346)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1918)
	... 76 more
```

**Comment by jmendeza** [comment]
Updated search so the reindex is submitted as a task without waiting.
Then the task status is retrieved periodically (every 5 seconds by default) until completed/failed/cancelled.
Deployer target has now new config properties: 

Under `target.search.openSearch.`
```
      client:
        # Number of slices to divide the reindex task
        reindexSlices: 0
        # Max time in seconds to wait for a reindex task to finish
        reindexTimeoutSeconds: 300
```

**Comment by avasquez614** [comment]
Verified
