### ISSUE TITLE
Deployer task exception Thread limit exceeded replacing blocked worker

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#7393]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

The error could happen in some conditions where number of tasks exceeds the ForkJoinPool

### Steps to reproduce

Steps:

2. Click on '...'
3. Scroll down to '...'
4. See the issue

### Relevant log output

```shell
2024-10-14 23:01:23.810 ERROR 19 --- [ForkJoinPool.commonPool-worker-130] oyer.impl.processors.aws.S3SyncProcessor : Error uploading file: /templates/web/components/xxxxxxx.ftl
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2000)
	at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3737)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3723)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	at org.craftercms.deployer.impl.processors.aws.S3SyncProcessor.lambda$uploadFiles$1(S3SyncProcessor.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
```

**Comment by phuongnq** [comment]
@avasquez614 FYI

**Comment by avasquez614** [comment]
Verified
