### ISSUE TITLE
During conflict resolution, content writes fail silently

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7434]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x

### Describe the issue

When a pull from remote causes merge conflicts, the sandbox repo is not locked in any way, so other users can try to edit content.

- If a user tries to write a content item that is not affected by the git-pull, the operation will fail with no message to the user (even though there will be an error in the logs)
- If the content edited is affected by the pull, the operation will also fail and then reset while trying to cleanup. This will be equivalent to "keep our version" for the item path.

### Steps to reproduce

Steps:

1. Create a site from a remote repository
2. Edit the same content item in both remote and sandbox repositories
3. Git pull. The UI will show the Resolve conflicts dialog
5. In a different tab, try to edit a different content item
6. The request seems successful, but the content was not saved

### Relevant log output

```shell
STDOUT: ''
STDERR: 'fatal: cannot do a partial commit during a merge.
'
	at org.craftercms.studio.impl.v2.utils.git.GitCli.handleErrorExitValue(GitCli.java:135) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.utils.git.GitCli.executeGitCommand(GitCli.java:107) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.utils.git.GitCli.commit(GitCli.java:223) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.api.v2.utils.GitRepositoryHelper.lambda$commitFiles$2(GitRepositoryHelper.java:1253) ~[classes/:4.2.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.repository.RetryingRepositoryOperationFacadeImpl.call(RetryingRepositoryOperationFacadeImpl.java:36) ~[classes/:4.2.0-SNAPSHOT]
```

**Comment by sumerjabri** [comment]
Let's start by locking the repo until it's merged/accepted after a pull.

**Comment by jmendeza** [comment]
@sumerjabri I think locking the whole repo across requests might increase complexity (lock entire repo, keep a lock owner, expire the lock?, etc)
[Suggested solution](https://github.com/craftercms/studio/pull/3822) is to refuse to perform any writes to the repository if it is in a merge state (i.e: MERGE_HEAD exists)

**Comment by Euquimides** [comment]
Hi! Verified fix for v5.0.0. Thank you!
