### ISSUE TITLE
Repository watcher sometimes fails with sandbox branch containing `/`

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7476]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Sometimes, when a site git branch contains `/`, e.g.: `bugfix/123`, the repository watcher fails to register for the site during startup.
This would prevent the sync-from-repo from being triggered on external changes to the repository

### Steps to reproduce

Steps:

TBD

### Relevant log output

```shell
[ERROR] 2024-11-01T09:09:29,976 [studioTaskExecutor-1] [sync.RepositoryWatcherImpl] | Failed to register site 'bigone-branch' 
java.nio.file.NoSuchFileException: /home/jonathanmendez/dev/repos/develop/ce/crafter-authoring/data/repos/sites/bigone-branch/sandbox/.git/refs/heads/test.jm/bugfix
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115) ~[?:?]
	at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:244) ~[?:?]
	at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266) ~[?:?]
	at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:357) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by avasquez614** [comment]
Shared with @jmendeza that the issue might actually be sites that have branches that contain dots (`.`)

**Comment by jmendeza** [comment]
Updated to create the directory when missing. It will also try to re-create and register again if the dir is deleted

**Comment by avasquez614** [comment]
Verified
