### ISSUE TITLE
write-content API fails to upload file

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7561]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

An error is thrown when trying to upload an asset.
In a local test environment, upload works properly when running on Tomcat 10.1.30 (the one used before upgrading to version 11.0.1)

### Steps to reproduce

Steps:

1. Create a site from editorial blueprint
2. Edit an article
3. Scroll to Image field. Click on "Replace" > "Upload Images"
4. Choose an image and try to upload
5. The upload fails:
![Screenshot from 2024-11-26 12-19-04](https://github.com/user-attachments/assets/9a735ef1-fba7-4f74-b888-0b1f9f4366c2)
6. See error in the logs about multi-part configuration not found

### Relevant log output

```shell
[ERROR] 2024-11-26T12:18:49,922 [http-nio-8080-exec-50] [impl.DefaultExceptionHandler] | POST http://localhost:8080/studio/api/1/services/api/1/content/write-content.json?path=%2Fstatic-assets%2Fitem%2Fimages%2F2024%2F11%2F26%2F&site=ed1 failed 
java.lang.IllegalStateException: Unable to process parts as no multi-part configuration has been provided
	at org.apache.catalina.connector.Request.parseParts(Request.java:2426) ~[catalina.jar:11.0.1]
	at org.apache.catalina.connector.Request.doParseParameters(Request.java:2807) ~[catalina.jar:11.0.1]
	at org.apache.catalina.connector.Request.parseParameters(Request.java:2754) ~[catalina.jar:11.0.1]
	at org.apache.catalina.connector.Request.getParameter(Request.java:1043) ~[catalina.jar:11.0.1]
	at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:152) ~[catalina.jar:11.0.1]
	at jakarta.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:160) ~[servlet-api.jar:6.1]
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.getParameter(StrictHttpFirewall.java:779) ~[spring-security-web-6.4.1.jar:6.4.1]
	at jakarta.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:160) ~[servlet-api.jar:6.1]
	at org.craftercms.studio.impl.v1.web.security.access.StudioContentAPIAccessDecisionVoter.voteInternal(StudioContentAPIAccessDecisionVoter.java:61) ~[classes/:5.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v1.web.security.access.StudioAbstractAccessDecisionVoter.vote(StudioAbstractAccessDecisionVoter.java:61) ~[classes/:5.0.0-SNAPSHOT]
	at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:72) ~[spring-security-core-6.4.1.jar:6.4.1]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.attemptAuthorization(AbstractSecurityInterceptor.java:253) ~[spring-security-core-6.4.1.jar:6.4.1]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:222) ~[spring-security-core-6.4.1.jar:6.4.1]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.craftercms.studio.impl.v2.security.authentication.basic.ConditionalBasicAuthenticationFilter.doFilterInternal(ConditionalBasicAuthenticationFilter.java:58) ~[classes/:5.0.0-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersBefore(HeaderWriterFilter.java:82) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:72) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.4.1.jar:6.4.1]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.0.jar:6.2.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:53) ~[classes/:5.0.0-SNAPSHOT]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.0.jar:6.2.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:77) ~[classes/:5.0.0-SNAPSHOT]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.0.jar:6.2.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:78) ~[crafter-commons-utilities-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.0.jar:6.2.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.0.jar:6.2.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.craftercms.studio.impl.v1.web.filter.MultiReadHttpServletRequestWrapperFilter.doFilter(MultiReadHttpServletRequestWrapperFilter.java:33) ~[classes/:5.0.0-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:70) ~[log4j-jakarta-web-2.24.2.jar:2.24.2]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109) ~[catalina.jar:11.0.1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:11.0.1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79) ~[catalina.jar:11.0.1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[catalina.jar:11.0.1]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[catalina.jar:11.0.1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:11.0.1]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663) ~[catalina.jar:11.0.1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:11.0.1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:11.0.1]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:395) ~[tomcat-coyote.jar:11.0.1]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:11.0.1]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-coyote.jar:11.0.1]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746) ~[tomcat-coyote.jar:11.0.1]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:11.0.1]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148) ~[tomcat-util.jar:11.0.1]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[tomcat-util.jar:11.0.1]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-util.jar:11.0.1]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by phuongnq** [comment]
@sumerjabri @jmendeza 
There are two issues with the new Tomcat 11:

* Missing of multi-part configuration => I added this in the `web.xml`
* Tomcat will automatically read the stream of the request whenever we call `getParameter()`. See: https://github.com/apache/tomcat/blob/11.0.2/java/org/apache/catalina/connector/Request.java#L1044.
=> In our current implementation, we call this here and there to parse parameters for Groovy variables and also in `StudioContentAPIAccessDecisionVoter` for API v1. A sample of this: https://github.com/phuongnq/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/web/security/access/StudioContentAPIAccessDecisionVoter.java#L61
For this reason, we cannot read the stream as it is to get multipart in the API `write-content`. Instead, I updated to read the parts using `request.getParts()` where Tomcat parsed for usage.

The PRs include:
1. Upgrade Tomcat to the latest 11.0.2 (We upgraded the jars to 11.0.2 but the embedded Tomcat was in 11.0.1)
2. Modify Studio to fix as of above
3. As of Tomcat 11.0.2, I have noticed that Tomcat also fixed the issue we encountered in https://github.com/craftercms/craftercms/issues/7551 so I have revered our custom bean for it. Please refer to the changelog here:
https://tomcat.apache.org/tomcat-11.0-doc/changelog.html
> [69478](https://bz.apache.org/bugzilla/show_bug.cgi?id=69478): Correct a regression introduced in 11.0.0-M19 that meant when calling setHttpOnly(boolean) or setSecure(boolean) for a cookie, the respective flags were set regardless of the value passed to the method

Detail in the ticket:
https://bz.apache.org/bugzilla/show_bug.cgi?id=69478 

I include this to the PR along with the upgrade Tomcat to 11.0.2. Please let me know if we are ok with this or prefer a separate PR

**Comment by sumerjabri** [comment]
@phuongnq I also updated the Docker images to 11.0.2. However, Deployer (Spring Boot) is still running 10.1. We must wait for Spring Boot 3.5 before getting Deployer to Tomcat v11.

Will we need to change Deployer once we go to Tomcat 11 on Deployer?

**Comment by jmendeza** [comment]
Verified. It is working now in v 5.0
